import FontAwesome from "@expo/vector-icons/FontAwesome";
import Constants from "expo-constants";
import * as Device from "expo-device";
import * as LocalAuthentication from "expo-local-authentication";
import * as Notifications from "expo-notifications";
import { useFocusEffect, useRouter } from "expo-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import {
  ActivityIndicator,
  Alert,
  KeyboardAvoidingView,
  Linking,
  Modal,
  Platform,
  Pressable,
  ScrollView,
  StyleSheet,
  Switch,
  Text,
  TextInput,
  View,
} from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";

import { AppLockSection } from "@/components/account/AppLockSection";
import {
  accountStyles as styles,
  EXPERIENCE_LEVEL_OPTIONS,
  POSITION_OPTIONS,
  publish_accountStyles,
  SPECIFIC_POSITION_OPTIONS,
  type ExperienceLevelValue,
  type PositionValue,
  type SpecificPositionValue,
} from "@/components/account/accountStyles";
import { PreferencesSection } from "@/components/account/PreferencesSection";
import { ProfileSection } from "@/components/account/ProfileSection";
import { ReferralSection } from "@/components/account/ReferralSection";
import { VerificationRequestModal } from "@/components/account/VerificationRequestModal";
import PlayerAvatar from "@/components/PlayerAvatar";
import { PhotoUploadField } from "@/components/photo";
import { useAccountIntroReplay } from "@/context/AccountIntroReplayContext";
import { useAdminMode } from "@/context/AdminModeContext";
import { useAppearance } from "@/context/AppearanceContext";
import { useAppLock } from "@/context/AppLockContext";
import { useAuth } from "@/context/AuthContext";
import { useProfileAdmin } from "@/context/ProfileAdminContext";
import { useReplayOpeningTheme } from "@/context/ReplayOpeningThemeContext";
import { useReviewMode } from "@/context/ReviewModeContext";
import { useAvatarPhoto } from "@/hooks/useAvatarPhoto";
import { useHubVenueResolve } from "@/hooks/useHubVenueResolve";
import {
  clampMaxDriveMinutes,
  cleanInstagram,
  DEFAULT_MAX_DRIVE_MINUTES,
  formatProfileSaveError,
  MAX_DRIVE_STEP,
  MAX_MAX_DRIVE_MINUTES,
  maxDriveLabel,
  MIN_MAX_DRIVE_MINUTES,
  supabaseLooksLikeMissingColumn,
} from "@/lib/accountHelpers";
import { APPEARANCE_OPTIONS } from "@/lib/appearance";
import { siteOrigin } from "@/lib/env";
import { fetchActionPhotoUrl } from "@/lib/photoUpload";
import {
  normalizeProfileUsername,
  USERNAME_TAKEN_USER_MESSAGE,
  usernameMatchesAutoGeneratedFromNames,
} from "@/lib/profileIdentityFields";
import { getInstallationContext, resolveExpoPushTokenForApp, shouldRegisterPushToken } from "@/lib/pushToken";
import { REVIEW_MODE_SECRET, REVIEW_MODE_TAP_TARGET } from "@/lib/reviewMode";
import { postMobilePushPreference, postMobilePushToken } from "@/lib/siteApi";
import { hostScore } from "@/lib/starRatings";
import { getNearestVenues, getNearestVenuesFromApi, type VenueDistanceRow } from "@/lib/venueDistance";
import { serviceRegionForVenueName } from "@/lib/venueServiceRegion";
import { headline, themeColor, useThemedStyles } from "@/theme";
import { INSTAGRAM_HANDLE } from "@/lib/brand";
import { openBrandInstagram } from "@/lib/openBrandInstagram";

const SUPPORT_EMAIL = "pickupct@gmail.com";
const SUPPORT_MAILTO = `mailto:${SUPPORT_EMAIL}`;
const DELETE_CONFIRM_WORD = "delete";

type ProfileRow = {
  first_name: string | null;
  last_name: string | null;
  approved: boolean | null;
  instagram: string | null;
  phone: string | null;
  zip_code: string | null;
  nearest_venue: string | null;
  playing_position: string | null;
  username: string | null;
  push_notifications_enabled: boolean | null;
  marketing_push_enabled: boolean | null;
  max_drive_minutes: number | null;
  primary_position: string | null;
  secondary_positions: string[] | null;
  experience_level: string | null;
  date_of_birth: string | null;
  club_name: string | null;
  roster_url: string | null;
  verification_level: string | null;
};

const PROFILE_SELECT_WITH_PUSH =
  "first_name,last_name,approved,instagram,phone,zip_code,nearest_venue,playing_position,username,push_notifications_enabled,marketing_push_enabled,max_drive_minutes,primary_position,secondary_positions,experience_level,date_of_birth,club_name,roster_url,verification_level";

const PROFILE_SELECT_WITHOUT_PUSH =
  "first_name,last_name,approved,instagram,phone,zip_code,nearest_venue,playing_position,username,max_drive_minutes,primary_position,secondary_positions,experience_level,date_of_birth,club_name,roster_url,verification_level";

const EXPERIENCE_LABELS: Record<string, string> = {
  recreational: "Recreational",
  club: "Club",
  hs_varsity: "High School Varsity",
  college: "College",
  semi_pro: "Semi-Pro",
  pro: "Pro",
};

const MONTHS_SHORT = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

// Parse an ISO "YYYY-MM-DD" without timezone drift -> "Mar 28, 2004".
function formatDob(dob: string | null): string | null {
  if (!dob) return null;
  const m = /^(\d{4})-(\d{2})-(\d{2})/.exec(dob.trim());
  if (m) {
    const year = Number(m[1]);
    const month = Number(m[2]) - 1;
    const day = Number(m[3]);
    if (month >= 0 && month < 12 && day >= 1 && day <= 31) {
      return `${MONTHS_SHORT[month]} ${day}, ${year}`;
    }
  }
  return null;
}

type IconName = React.ComponentProps<typeof FontAwesome>["name"];

export default function SettingsScreen() {
  useThemedStyles(publish_s);
  useThemedStyles(publish_accountStyles);

  const router = useRouter();
  const push = router.push as (href: string) => void;
  const insets = useSafeAreaInsets();
  const { replay: replayAccountIntro } = useAccountIntroReplay();
  const replayOpeningThemeCtx = useReplayOpeningTheme();
  const { session, supabase, isReady, signOut } = useAuth();
  const { enabled: adminModeEnabled, isReady: adminModeReady, setEnabled: setAdminModeEnabled } = useAdminMode();
  const { enabled: reviewModeEnabled, setEnabled: setReviewModeEnabled } = useReviewMode();
  const { isAdmin } = useProfileAdmin();
  const { preference: appearance, setPreference: setAppearance } = useAppearance();
  const {
    hasPin,
    lockEnabled,
    requestEnrollment,
    changePin,
    removePin,
    biometricsEnabled,
    biometricsAvailable,
    setBiometricsEnabled,
    refreshBiometricAvailability,
    lockNow,
  } = useAppLock();

  const accessToken = session?.access_token ?? null;
  const signedEmail = session?.user?.email ?? null;

  const [lockUi, setLockUi] = useState<"idle" | "change" | "remove">("idle");
  const [changeOld, setChangeOld] = useState("");
  const [changeNewA, setChangeNewA] = useState("");
  const [changeNewB, setChangeNewB] = useState("");
  const [removeCurrent, setRemoveCurrent] = useState("");
  const [lockBusy, setLockBusy] = useState(false);
  const [lockMsg, setLockMsg] = useState<string | null>(null);
  const [passwordResetBusy, setPasswordResetBusy] = useState(false);

  const [profile, setProfile] = useState<ProfileRow | null>(null);
  const [editModalOpen, setEditModalOpen] = useState(false);
  const [editFirstName, setEditFirstName] = useState("");
  const [editLastName, setEditLastName] = useState("");
  const [editPlayingPosition, setEditPlayingPosition] = useState<PositionValue | null>(null);
  const [editPrimaryPosition, setEditPrimaryPosition] = useState<SpecificPositionValue | null>(null);
  const [editSecondaryPositions, setEditSecondaryPositions] = useState<SpecificPositionValue[]>([]);
  const [editExperienceLevel, setEditExperienceLevel] = useState<ExperienceLevelValue | null>(null);
  const [editDateOfBirth, setEditDateOfBirth] = useState("");
  const [editClubName, setEditClubName] = useState("");
  const [editRosterUrl, setEditRosterUrl] = useState("");
  const [editInstagram, setEditInstagram] = useState("");
  const [editPhone, setEditPhone] = useState("");
  const [editZipCode, setEditZipCode] = useState("");
  const [editUsername, setEditUsername] = useState("");
  const [editBusy, setEditBusy] = useState(false);
  const [editMsg, setEditMsg] = useState<string | null>(null);
  const [profileSaveError, setProfileSaveError] = useState<string | null>(null);
  const [editOk, setEditOk] = useState(false);
  const [positionPickerOpen, setPositionPickerOpen] = useState(false);
  const [primaryPositionPickerOpen, setPrimaryPositionPickerOpen] = useState(false);
  const [experienceLevelPickerOpen, setExperienceLevelPickerOpen] = useState(false);
  const [verificationModalOpen, setVerificationModalOpen] = useState(false);
  const [actionPhotoUrl, setActionPhotoUrl] = useState<string | null>(null);
  const { avatarUrl, setAvatarUrl, avatarUploading, pickAndUploadAvatar } = useAvatarPhoto();

  const [waiverAccepted, setWaiverAccepted] = useState<boolean | null>(null);
  const [waiverLoading, setWaiverLoading] = useState(true);

  const [deleteAccountBusy, setDeleteAccountBusy] = useState(false);
  const [deleteConfirmModalOpen, setDeleteConfirmModalOpen] = useState(false);
  const [deleteConfirmInput, setDeleteConfirmInput] = useState("");
  /** Server preview warning (upcoming games, hosted runs); set means the delete request carries confirm_upcoming. */
  const [deleteUpcomingWarning, setDeleteUpcomingWarning] = useState<string | null>(null);

  const [pushEnabled, setPushEnabled] = useState(true);
  const [pushBusy, setPushBusy] = useState(false);
  const [pushMsg, setPushMsg] = useState<string | null>(null);
  const [marketingPushEnabled, setMarketingPushEnabled] = useState(false);
  const [marketingPushBusy, setMarketingPushBusy] = useState(false);
  const [marketingPushMsg, setMarketingPushMsg] = useState<string | null>(null);
  const [hostInvitesEnabled, setHostInvitesEnabled] = useState(true);
  const [hostInvitesBusy, setHostInvitesBusy] = useState(false);
  const [hostInvitesMsg, setHostInvitesMsg] = useState<string | null>(null);
  const [maxDriveMinutes, setMaxDriveMinutes] = useState(DEFAULT_MAX_DRIVE_MINUTES);
  const [maxDriveBusy, setMaxDriveBusy] = useState(false);
  const [maxDriveMsg, setMaxDriveMsg] = useState<string | null>(null);

  const [aboutTapCount, setAboutTapCount] = useState(0);
  const [reviewCodeModalOpen, setReviewCodeModalOpen] = useState(false);
  const [reviewCodeInput, setReviewCodeInput] = useState("");

  const [hosting, setHosting] = useState<{ sessionsHosted: number; avgOverall: number | null } | null>(null);
  const [creditsCount, setCreditsCount] = useState<number | null>(null);

  const { hubRegionResolving, hubVenueResolveDone } = useHubVenueResolve(profile, (venue) =>
    setProfile((p) => (p ? { ...p, nearest_venue: venue } : p)),
  );

  const openEdit = useCallback(() => setEditModalOpen(true), []);

  const appVersion = Constants.expoConfig?.version ?? Constants.nativeAppVersion ?? null;

  useEffect(() => {
    void refreshBiometricAvailability();
  }, [refreshBiometricAvailability]);

  const saveActionPhoto = useCallback(
    async (url: string | null) => {
      const userId = session?.user?.id;
      if (!supabase || !userId) throw new Error("Please sign in again.");
      const { error } = await supabase.from("profiles").update({ action_photo_url: url }).eq("id", userId);
      if (error) throw new Error(error.message || "Could not save the action photo.");
      setActionPhotoUrl(url);
    },
    [supabase, session?.user?.id],
  );

  function submitReviewCode() {
    if (reviewCodeInput.trim() === REVIEW_MODE_SECRET) {
      void setReviewModeEnabled(true);
      setReviewCodeModalOpen(false);
      setReviewCodeInput("");
      Alert.alert("Review Mode", "App Review Mode is now active.");
    } else {
      Alert.alert("Review Mode", "Incorrect code.");
    }
  }

  function openReviewCodeEntry() {
    setReviewCodeInput("");
    if (Platform.OS === "ios" && typeof Alert.prompt === "function") {
      Alert.prompt(
        "Review Mode",
        "Enter the review secret code.",
        [
          { text: "Cancel", style: "cancel" },
          {
            text: "Activate",
            onPress: (value?: string) => {
              if (String(value ?? "").trim() === REVIEW_MODE_SECRET) {
                void setReviewModeEnabled(true);
                Alert.alert("Review Mode", "App Review Mode is now active.");
              } else {
                Alert.alert("Review Mode", "Incorrect code.");
              }
            },
          },
        ],
        "secure-text",
      );
      return;
    }
    setReviewCodeModalOpen(true);
  }

  const closeDeleteConfirmModal = useCallback(() => {
    setDeleteConfirmModalOpen(false);
    setDeleteConfirmInput("");
    setDeleteUpcomingWarning(null);
  }, []);

  const performDeleteAccount = useCallback(async () => {
    if (deleteConfirmInput !== DELETE_CONFIRM_WORD) return;
    const origin = siteOrigin();
    if (!origin || !accessToken) {
      Alert.alert("Can’t delete account", "Missing server URL or session. Try again after signing in.");
      return;
    }
    setDeleteAccountBusy(true);
    try {
      const r = await fetch(`${origin}/api/account/delete`, {
        method: "DELETE",
        headers: {
          Accept: "application/json",
          "Content-Type": "application/json",
          Authorization: `Bearer ${accessToken}`,
        },
        body: JSON.stringify({ confirm_upcoming: deleteUpcomingWarning != null }),
        cache: "no-store",
      });
      if (!r.ok) {
        const j = (await r.json().catch(() => null)) as {
          error?: string;
          failures?: { name?: string | null; error?: string }[];
        } | null;
        const failed = (j?.failures ?? [])
          .map((f) => (f.name ? `${f.name}: ${f.error ?? "not settled"}` : f.error ?? ""))
          .filter(Boolean);
        const base = typeof j?.error === "string" ? j.error : "Something went wrong. Try again later.";
        Alert.alert("Couldn’t delete account", failed.length ? `${base}\n\n${failed.join("\n")}` : base);
        return;
      }
      closeDeleteConfirmModal();
      await signOut();
      router.replace("/login");
    } catch {
      Alert.alert("Couldn’t delete account", "Check your connection and try again.");
    } finally {
      setDeleteAccountBusy(false);
    }
  }, [accessToken, closeDeleteConfirmModal, deleteConfirmInput, deleteUpcomingWarning, router, signOut]);

  const startDeleteAccountFlow = useCallback(async () => {
    const origin = siteOrigin();
    if (!origin || !accessToken) {
      Alert.alert("Can’t delete account", "Missing server URL or session. Try again after signing in.");
      return;
    }
    let warning: string | null = null;
    setDeleteAccountBusy(true);
    try {
      const r = await fetch(`${origin}/api/account/delete`, {
        headers: { Accept: "application/json", Authorization: `Bearer ${accessToken}` },
        cache: "no-store",
      });
      const j = (await r.json().catch(() => null)) as {
        error?: string;
        preview?: { confirmation_required?: boolean; message?: string | null };
      } | null;
      if (!r.ok || !j?.preview) {
        Alert.alert("Couldn’t delete account", typeof j?.error === "string" ? j.error : "Something went wrong. Try again later.");
        return;
      }
      if (j.preview.confirmation_required) warning = j.preview.message || "You have upcoming games.";
    } catch {
      Alert.alert("Couldn’t delete account", "Check your connection and try again.");
      return;
    } finally {
      setDeleteAccountBusy(false);
    }
    if (warning) {
      const upcoming = warning;
      Alert.alert("Before you delete your account", upcoming, [
        { text: "Cancel", style: "cancel" },
        {
          text: "Give up and continue",
          style: "destructive",
          onPress: () => {
            setDeleteConfirmInput("");
            setDeleteUpcomingWarning(upcoming);
            setDeleteConfirmModalOpen(true);
          },
        },
      ]);
      return;
    }
    Alert.alert(
      "Are you sure you want to delete your account?",
      "You will lose everything — your stats, RSVPs, credits, and profile. This cannot be undone.",
      [
        { text: "Cancel", style: "cancel" },
        {
          text: "Continue",
          onPress: () => {
            setDeleteConfirmInput("");
            setDeleteConfirmModalOpen(true);
          },
        },
      ],
    );
  }, [accessToken]);

  const deleteConfirmMatches = deleteConfirmInput === DELETE_CONFIRM_WORD;

  const usernameAutoFromName = useMemo(
    () => usernameMatchesAutoGeneratedFromNames(editUsername, editFirstName, editLastName),
    [editUsername, editFirstName, editLastName],
  );

  const profileRegionCode = useMemo(() => serviceRegionForVenueName(profile?.nearest_venue), [profile?.nearest_venue]);

  const loadProfile = useCallback(async () => {
    const uid = session?.user?.id;
    if (!isReady || !supabase || !uid) return;
    try {
      let res = await supabase.from("profiles").select(PROFILE_SELECT_WITH_PUSH).eq("id", uid).maybeSingle();
      if (res.error) {
        console.error("[settings loadProfile] Supabase error", JSON.stringify(res.error));
        if (
          supabaseLooksLikeMissingColumn(res.error, "push_notifications_enabled") ||
          supabaseLooksLikeMissingColumn(res.error, "marketing_push_enabled") ||
          supabaseLooksLikeMissingColumn(res.error, "max_drive_minutes")
        ) {
          res = await supabase.from("profiles").select(PROFILE_SELECT_WITHOUT_PUSH).eq("id", uid).maybeSingle();
          if (res.error) {
            console.error("[settings loadProfile] fallback select error", JSON.stringify(res.error));
            setProfile(null);
            return;
          }
          const row = res.data as Omit<ProfileRow, "push_notifications_enabled"> | null;
          setProfile(
            row
              ? {
                  ...row,
                  push_notifications_enabled: true,
                  marketing_push_enabled: false,
                  max_drive_minutes:
                    row.max_drive_minutes == null
                      ? DEFAULT_MAX_DRIVE_MINUTES
                      : clampMaxDriveMinutes(Number(row.max_drive_minutes)),
                }
              : null,
          );
          return;
        }
        setProfile(null);
        return;
      }
      const row = res.data as ProfileRow | null;
      setProfile(
        row
          ? {
              ...row,
              max_drive_minutes:
                row.max_drive_minutes == null
                  ? DEFAULT_MAX_DRIVE_MINUTES
                  : clampMaxDriveMinutes(Number(row.max_drive_minutes)),
            }
          : null,
      );
    } catch (e) {
      console.error("[settings loadProfile] exception", e);
      setProfile(null);
    }
  }, [isReady, supabase, session?.user?.id]);

  // Separate from loadProfile so a pending allow_host_invites migration cannot break the main profile load.
  const loadHostInvitePref = useCallback(async () => {
    const uid = session?.user?.id;
    if (!isReady || !supabase || !uid) return;
    const { data, error } = await supabase.from("profiles").select("allow_host_invites").eq("id", uid).maybeSingle();
    if (error) {
      if (!supabaseLooksLikeMissingColumn(error, "allow_host_invites")) {
        console.error("[settings] allow_host_invites load error", JSON.stringify(error));
        setHostInvitesMsg(formatProfileSaveError(error));
      }
      setHostInvitesEnabled(true);
      return;
    }
    setHostInvitesEnabled((data as { allow_host_invites?: boolean | null } | null)?.allow_host_invites !== false);
  }, [isReady, supabase, session?.user?.id]);

  const loadPhotos = useCallback(async () => {
    const uid = session?.user?.id;
    if (!isReady || !supabase || !uid) return;
    const [avatarRes, photo] = await Promise.all([
      supabase.from("profiles").select("avatar_url").eq("id", uid).maybeSingle(),
      fetchActionPhotoUrl(supabase, uid),
    ]);
    if (!avatarRes.error && avatarRes.data) {
      setAvatarUrl((avatarRes.data as { avatar_url: string | null }).avatar_url?.trim() || null);
    }
    setActionPhotoUrl(photo);
  }, [isReady, supabase, session?.user?.id, setAvatarUrl]);

  const loadCredits = useCallback(async () => {
    const origin = siteOrigin();
    if (!origin || !accessToken) {
      setCreditsCount(0);
      return;
    }
    try {
      const r = await fetch(`${origin}/api/pickup/credits`, {
        headers: { Authorization: `Bearer ${accessToken}`, Accept: "application/json" },
        cache: "no-store",
      });
      const j = (await r.json().catch(() => null)) as
        | { credits?: Array<{ is_used?: boolean; is_expired?: boolean }> }
        | null;
      if (r.ok && j && Array.isArray(j.credits)) {
        setCreditsCount(j.credits.filter((c) => !c.is_used && !c.is_expired).length);
      } else {
        setCreditsCount(0);
      }
    } catch {
      setCreditsCount(0);
    }
  }, [accessToken]);

  const loadHosting = useCallback(async () => {
    const origin = siteOrigin();
    const uid = session?.user?.id;
    if (!origin || !accessToken || !uid) {
      setHosting(null);
      return;
    }
    try {
      const r = await fetch(`${origin}/api/sessions/host-rating?host_id=${encodeURIComponent(uid)}`, {
        headers: { Authorization: `Bearer ${accessToken}`, Accept: "application/json" },
      });
      const j = (await r.json().catch(() => null)) as { avg_overall?: number | null; sessions_hosted?: number } | null;
      if (!r.ok || !j) {
        setHosting(null);
        return;
      }
      setHosting({
        sessionsHosted: Number(j.sessions_hosted ?? 0),
        avgOverall: typeof j.avg_overall === "number" ? j.avg_overall : null,
      });
    } catch {
      setHosting(null);
    }
  }, [accessToken, session?.user?.id]);

  const loadWaiverStatus = useCallback(async () => {
    if (!isReady) return;
    const origin = siteOrigin();
    if (!origin || !accessToken) {
      setWaiverLoading(false);
      setWaiverAccepted(null);
      return;
    }
    setWaiverLoading(true);
    try {
      const r = await fetch(`${origin}/api/waiver/status`, {
        method: "GET",
        headers: { Accept: "application/json", Authorization: `Bearer ${accessToken}` },
        cache: "no-store",
      });
      const j = (await r.json().catch(() => null)) as { accepted?: boolean } | null;
      setWaiverAccepted(r.ok && j ? Boolean(j.accepted) : null);
    } catch (e) {
      console.warn("[settings] loadWaiverStatus error:", e);
      setWaiverAccepted(null);
    } finally {
      setWaiverLoading(false);
    }
  }, [isReady, accessToken]);

  useFocusEffect(
    useCallback(() => {
      void loadProfile();
      void loadHostInvitePref();
      void loadWaiverStatus();
    }, [loadProfile, loadHostInvitePref, loadWaiverStatus]),
  );

  useEffect(() => {
    void loadPhotos();
    void loadCredits();
    void loadHosting();
  }, [loadPhotos, loadCredits, loadHosting]);

  useEffect(() => {
    if (!profile || editBusy) return;
    setEditFirstName(String(profile.first_name ?? ""));
    setEditLastName(String(profile.last_name ?? ""));
    const rawPos = String(profile.playing_position ?? "").trim();
    setEditPlayingPosition(
      (POSITION_OPTIONS as readonly { value: string }[]).some((o) => o.value === rawPos) ? (rawPos as PositionValue) : null,
    );
    setEditInstagram(profile.instagram ? String(profile.instagram).replace(/^@/, "") : "");
    setEditPhone(String(profile.phone ?? ""));
    setEditZipCode(String(profile.zip_code ?? "").replace(/\D/g, "").slice(0, 5));
    setEditUsername(String(profile.username ?? ""));
    setPushEnabled(profile.push_notifications_enabled !== false);
    setMarketingPushEnabled(profile.marketing_push_enabled === true);
    const storedMax = profile.max_drive_minutes == null ? DEFAULT_MAX_DRIVE_MINUTES : Number(profile.max_drive_minutes);
    setMaxDriveMinutes(clampMaxDriveMinutes(storedMax));
    const rawPrimary = String(profile.primary_position ?? "").trim();
    setEditPrimaryPosition(
      (SPECIFIC_POSITION_OPTIONS as readonly { value: string }[]).some((o) => o.value === rawPrimary)
        ? (rawPrimary as SpecificPositionValue)
        : null,
    );
    const rawSecondary = Array.isArray(profile.secondary_positions) ? profile.secondary_positions : [];
    setEditSecondaryPositions(
      rawSecondary.filter((p): p is SpecificPositionValue =>
        (SPECIFIC_POSITION_OPTIONS as readonly { value: string }[]).some((o) => o.value === p),
      ),
    );
    const rawExp = String(profile.experience_level ?? "").trim();
    setEditExperienceLevel(
      (EXPERIENCE_LEVEL_OPTIONS as readonly { value: string }[]).some((o) => o.value === rawExp)
        ? (rawExp as ExperienceLevelValue)
        : null,
    );
    setEditDateOfBirth(String(profile.date_of_birth ?? ""));
    setEditClubName(String(profile.club_name ?? ""));
    setEditRosterUrl(String(profile.roster_url ?? ""));
  }, [profile, editBusy]);

  async function onSaveProfile() {
    setEditMsg(null);
    setProfileSaveError(null);
    setEditOk(false);

    if (!supabase) {
      setProfileSaveError("Save failed: Supabase client is not available. Check app configuration.");
      return;
    }

    const userId = session?.user?.id;
    if (!userId) {
      setProfileSaveError("Save failed: Not signed in.");
      return;
    }

    const firstName = editFirstName.trim();
    const lastName = editLastName.trim();
    const playingPosition = editPlayingPosition;
    const instagram = cleanInstagram(editInstagram);
    const phone = editPhone.trim();
    const zipDigits = editZipCode.replace(/\D/g, "").slice(0, 5);
    const usernameRaw = editUsername.trim();
    const storedUsername = (profile?.username ?? "").trim();
    let usernameResolved: string | null = null;
    if (usernameRaw) {
      const matchesStored = storedUsername.length > 0 && usernameRaw.toLowerCase() === storedUsername.toLowerCase();
      const norm = normalizeProfileUsername(usernameRaw);
      if (!matchesStored && !norm) {
        setProfileSaveError("Save failed: Username must be 3–30 characters, lowercase letters and numbers only.");
        return;
      }
      usernameResolved = matchesStored ? storedUsername : norm!;
    }

    const zipStored = zipDigits.length === 5 ? zipDigits : null;

    setEditBusy(true);
    try {
      let nearestVenues: VenueDistanceRow[] = [];
      if (zipStored) {
        const originForVenues = siteOrigin();
        if (originForVenues) {
          try {
            nearestVenues = await getNearestVenuesFromApi(zipStored, originForVenues, accessToken);
          } catch (e) {
            console.error("[onSaveProfile] getNearestVenuesFromApi exception", e);
          }
        }
        if (nearestVenues.length === 0) {
          nearestVenues = getNearestVenues(zipStored);
        }
      }
      const maxMin =
        profile?.max_drive_minutes == null
          ? DEFAULT_MAX_DRIVE_MINUTES
          : clampMaxDriveMinutes(Number(profile.max_drive_minutes));
      const nearestVenue = nearestVenues.filter((r) => r.estimatedMinutes <= maxMin)[0]?.venue ?? null;

      const updatedAt = new Date().toISOString();
      const coreUpdate = {
        first_name: firstName || null,
        last_name: lastName || null,
        playing_position: playingPosition ?? null,
        instagram: instagram || null,
        phone: phone || null,
        zip_code: zipStored,
        username: usernameResolved,
        updated_at: updatedAt,
        primary_position: editPrimaryPosition ?? null,
        secondary_positions: editSecondaryPositions.length > 0 ? editSecondaryPositions : null,
        experience_level: editExperienceLevel ?? null,
        date_of_birth: editDateOfBirth.trim() || null,
        club_name: editClubName.trim() || null,
        roster_url: editRosterUrl.trim() || null,
      };

      const origin = siteOrigin();
      if (origin && accessToken) {
        try {
          const r = await fetch(`${origin}/api/account/profile`, {
            method: "PATCH",
            headers: {
              Accept: "application/json",
              "Content-Type": "application/json",
              Authorization: `Bearer ${accessToken}`,
            },
            body: JSON.stringify({ ...coreUpdate, nearest_venue: nearestVenue }),
            cache: "no-store",
          });
          const j = (await r.json().catch(() => null)) as { ok?: boolean; error?: string } | null;
          if (!r.ok) {
            const errLine =
              typeof j?.error === "string" && j.error.trim() ? j.error.trim() : `HTTP ${r.status} ${r.statusText || ""}`.trim();
            setProfileSaveError(`Save failed: ${errLine}`);
            return;
          }
          if (j && j.ok === false && typeof j.error === "string" && j.error.trim()) {
            setProfileSaveError(`Save failed: ${j.error.trim()}`);
            return;
          }
        } catch (e) {
          console.error("[onSaveProfile] /api/account/profile fetch exception", e);
          setProfileSaveError(`Save failed: ${formatProfileSaveError(e)}`);
          return;
        }
      } else {
        let data: { id: string }[] | null = null;
        let error: { message?: string; code?: string } | null = null;

        try {
          const withVenue = await supabase
            .from("profiles")
            .update({ ...coreUpdate, nearest_venue: nearestVenue })
            .eq("id", userId)
            .select("id");
          data = withVenue.data;
          error = withVenue.error;
          if (error && supabaseLooksLikeMissingColumn(error, "nearest_venue")) {
            console.error("[onSaveProfile] retrying without nearest_venue", JSON.stringify(error));
            const noVenue = await supabase.from("profiles").update(coreUpdate).eq("id", userId).select("id");
            data = noVenue.data;
            error = noVenue.error;
          }
        } catch (e) {
          console.error("[onSaveProfile] profiles.update exception", e);
          setProfileSaveError(`Save failed: ${formatProfileSaveError(e)}`);
          return;
        }

        if (error) {
          console.error("[onSaveProfile] supabase.from('profiles').update error", JSON.stringify(error));
          const code = (error as { code?: string }).code;
          const dup = code === "23505" || /profiles_username_lower_unique|duplicate key/i.test(error.message ?? "");
          setProfileSaveError(`Save failed: ${dup ? USERNAME_TAKEN_USER_MESSAGE : formatProfileSaveError(error)}`);
          return;
        }

        if (!data?.length) {
          console.error("[onSaveProfile] update returned 0 rows", { userId });
          setProfileSaveError(
            "Save failed: Save did not update any profile row (no match or not permitted). Your account may be missing a profile row.",
          );
          return;
        }
      }

      const nextFields = {
        first_name: firstName || null,
        last_name: lastName || null,
        playing_position: playingPosition ?? null,
        instagram: instagram || null,
        phone: phone || null,
        zip_code: zipDigits.length === 5 ? zipDigits : null,
        username: usernameResolved,
        nearest_venue: nearestVenue,
        primary_position: editPrimaryPosition ?? null,
        secondary_positions: editSecondaryPositions.length > 0 ? editSecondaryPositions : null,
        experience_level: editExperienceLevel ?? null,
        date_of_birth: editDateOfBirth.trim() || null,
        club_name: editClubName.trim() || null,
        roster_url: editRosterUrl.trim() || null,
      };
      setProfile((p) => (p ? { ...p, ...nextFields } : p));
      setEditFirstName(firstName);
      setEditLastName(lastName);
      setEditPlayingPosition(playingPosition);
      setEditInstagram(instagram || "");
      setEditPhone(phone);
      setEditZipCode(zipDigits.length === 5 ? zipDigits : "");
      setEditUsername(usernameResolved ?? "");
      setEditOk(true);
      setEditMsg("Saved.");
    } catch (e) {
      console.error("[onSaveProfile] exception", e);
      setProfileSaveError(`Save failed: ${formatProfileSaveError(e)}`);
    } finally {
      setEditBusy(false);
    }
  }

  async function onSaveMaxDriveMinutes(nextRaw: number) {
    const next = clampMaxDriveMinutes(nextRaw);
    if (maxDriveBusy) return;
    setMaxDriveMsg(null);
    if (!supabase) {
      setMaxDriveMsg("Supabase client is not available. Check app configuration.");
      return;
    }
    const uid = session?.user?.id;
    if (!uid) {
      setMaxDriveMsg("Sign in again to change this.");
      return;
    }

    const prev = maxDriveMinutes;
    setMaxDriveMinutes(next);
    setMaxDriveBusy(true);
    try {
      const res = await supabase
        .from("profiles")
        .update({ max_drive_minutes: next, updated_at: new Date().toISOString() })
        .eq("id", uid)
        .select("id");
      if (res.error) {
        setMaxDriveMinutes(prev);
        setMaxDriveMsg(formatProfileSaveError(res.error));
        return;
      }
      if (!res.data?.length) {
        setMaxDriveMinutes(prev);
        setMaxDriveMsg("Save did not update any profile row.");
        return;
      }
      setProfile((p) => (p ? { ...p, max_drive_minutes: next } : p));
    } catch (e) {
      setMaxDriveMinutes(prev);
      setMaxDriveMsg(formatProfileSaveError(e));
    } finally {
      setMaxDriveBusy(false);
    }
  }

  async function onTogglePushNotifications(next: boolean) {
    if (pushBusy) return;
    setPushMsg(null);
    if (!supabase) {
      setPushMsg("Supabase client is not available. Check app configuration.");
      return;
    }
    if (!accessToken) {
      setPushMsg("Sign in again to change this.");
      return;
    }
    const uid = session?.user?.id;
    if (!uid) {
      setPushMsg("Sign in again to change this.");
      return;
    }

    const prev = pushEnabled;
    setPushEnabled(next);
    setPushBusy(true);
    try {
      try {
        const res = await supabase
          .from("profiles")
          .update({ push_notifications_enabled: next, updated_at: new Date().toISOString() })
          .eq("id", uid)
          .select("id");
        if (res.error) {
          console.log("[push-pref] profiles.update Supabase error JSON:", JSON.stringify(res.error));
          setPushEnabled(prev);
          setPushMsg(formatProfileSaveError(res.error));
          return;
        }
        if (!res.data?.length) {
          console.log("[push-pref] profiles.update returned 0 rows", { userId: uid });
          setPushEnabled(prev);
          setPushMsg(
            "Save did not update any profile row (no match or not permitted). Your account may be missing a profile row.",
          );
          return;
        }
      } catch (e) {
        console.log("[push-pref] profiles.update exception:", e);
        setPushEnabled(prev);
        setPushMsg(formatProfileSaveError(e));
        return;
      }

      setProfile((p) =>
        p ? { ...p, push_notifications_enabled: next, marketing_push_enabled: next ? p.marketing_push_enabled : false } : p,
      );

      if (!next) {
        setMarketingPushEnabled(false);
        try {
          await supabase
            .from("profiles")
            .update({ marketing_push_enabled: false, updated_at: new Date().toISOString() })
            .eq("id", uid);
        } catch (e) {
          console.log("[push-pref] marketing_push_enabled off exception:", e);
        }
        try {
          const { error: delErr } = await supabase.from("user_push_devices").delete().eq("user_id", uid);
          if (delErr) console.log("[push-pref] user_push_devices.delete Supabase error JSON:", JSON.stringify(delErr));
        } catch (e) {
          console.log("[push-pref] user_push_devices.delete exception:", e);
        }
        try {
          const res = await postMobilePushPreference(accessToken, false);
          if (!res.ok) console.log("[push-pref] postMobilePushPreference(false) failed:", res.error);
        } catch (e) {
          console.log("[push-pref] postMobilePushPreference(false) exception:", e);
        }
      } else if (Device.isDevice) {
        try {
          if (!shouldRegisterPushToken()) return;

          const { status: existing } = await Notifications.getPermissionsAsync();
          let finalStatus = existing;
          if (existing !== "granted") {
            const req = await Notifications.requestPermissionsAsync();
            finalStatus = req.status;
          }
          if (finalStatus === "granted") {
            const installationContext = getInstallationContext();
            if (installationContext === "storeClient") return;

            const expoPushToken = await resolveExpoPushTokenForApp();
            const platform = Platform.OS === "ios" ? "ios" : Platform.OS === "android" ? "android" : null;
            if (expoPushToken && platform) {
              const reg = await postMobilePushToken(accessToken, expoPushToken, platform, installationContext);
              if (!reg.ok) console.log("[push-pref] postMobilePushToken failed:", reg.error);
            }
          }
        } catch (e) {
          console.log("[push-pref] token re-register exception:", e);
        }
      }
    } finally {
      setPushBusy(false);
    }
  }

  async function onToggleMarketingPush(next: boolean) {
    if (marketingPushBusy) return;
    setMarketingPushMsg(null);
    if (!pushEnabled && next) {
      setMarketingPushMsg("Turn on push notifications first.");
      return;
    }
    if (!supabase) {
      setMarketingPushMsg("Supabase client is not available. Check app configuration.");
      return;
    }
    if (!accessToken) {
      setMarketingPushMsg("Sign in again to change this.");
      return;
    }
    const uid = session?.user?.id;
    if (!uid) {
      setMarketingPushMsg("Sign in again to change this.");
      return;
    }

    const prev = marketingPushEnabled;
    setMarketingPushEnabled(next);
    setMarketingPushBusy(true);
    try {
      const res = await supabase
        .from("profiles")
        .update({ marketing_push_enabled: next, updated_at: new Date().toISOString() })
        .eq("id", uid)
        .select("id");
      if (res.error) {
        setMarketingPushEnabled(prev);
        setMarketingPushMsg(
          supabaseLooksLikeMissingColumn(res.error, "marketing_push_enabled")
            ? "Marketing push preference is not available yet. Apply the latest database migration."
            : formatProfileSaveError(res.error),
        );
        return;
      }
      if (!res.data?.length) {
        setMarketingPushEnabled(prev);
        setMarketingPushMsg("Save did not update any profile row.");
        return;
      }

      try {
        await supabase
          .from("user_push_devices")
          .update({ marketing_push_enabled: next, updated_at: new Date().toISOString() })
          .eq("user_id", uid);
      } catch (e) {
        console.log("[marketing-push] user_push_devices sync exception:", e);
      }

      setProfile((p) => (p ? { ...p, marketing_push_enabled: next } : p));
    } catch (e) {
      setMarketingPushEnabled(prev);
      setMarketingPushMsg(formatProfileSaveError(e));
    } finally {
      setMarketingPushBusy(false);
    }
  }

  async function onToggleHostInvites(next: boolean) {
    if (hostInvitesBusy) return;
    setHostInvitesMsg(null);
    const uid = session?.user?.id;
    if (!supabase || !uid) {
      setHostInvitesMsg("Sign in again to change this.");
      return;
    }
    const prev = hostInvitesEnabled;
    setHostInvitesEnabled(next);
    setHostInvitesBusy(true);
    try {
      const res = await supabase
        .from("profiles")
        .update({ allow_host_invites: next, updated_at: new Date().toISOString() })
        .eq("id", uid)
        .select("id");
      if (res.error) {
        setHostInvitesEnabled(prev);
        setHostInvitesMsg(
          supabaseLooksLikeMissingColumn(res.error, "allow_host_invites")
            ? "Host invite setting is not available yet. Apply the latest database migration."
            : formatProfileSaveError(res.error),
        );
        return;
      }
      if (!res.data?.length) {
        setHostInvitesEnabled(prev);
        setHostInvitesMsg("Save did not update any profile row.");
      }
    } catch (e) {
      setHostInvitesEnabled(prev);
      setHostInvitesMsg(formatProfileSaveError(e));
    } finally {
      setHostInvitesBusy(false);
    }
  }

  async function onToggleBiometrics(next: boolean) {
    setLockMsg(null);
    if (!next) {
      await setBiometricsEnabled(false);
      return;
    }
    if (!biometricsAvailable) {
      setLockMsg("Biometrics aren’t available on this device.");
      return;
    }
    const r = await LocalAuthentication.authenticateAsync({
      promptMessage: "Turn on Face ID for Competitive Together",
      cancelLabel: "Cancel",
    });
    if (r.success) await setBiometricsEnabled(true);
  }

  async function onSendPasswordReset() {
    if (!supabase || !signedEmail || passwordResetBusy) return;
    setPasswordResetBusy(true);
    try {
      const { error } = await supabase.auth.resetPasswordForEmail(signedEmail, {
        redirectTo: "ctpickup://reset-password",
      });
      if (error) {
        console.error("[settings] resetPasswordForEmail failed", error);
        Alert.alert("Reset email", "Could not send reset email. Please try again.");
        return;
      }
      Alert.alert("Reset email", `Password reset email sent to ${signedEmail}`);
    } finally {
      setPasswordResetBusy(false);
    }
  }

  if (!isReady || !signedEmail) {
    return (
      <View style={styles.center}>
        <ActivityIndicator size="large" color={themeColor().text} />
      </View>
    );
  }

  const fullName = [profile?.first_name, profile?.last_name].filter(Boolean).join(" ").trim();
  const uname = (profile?.username ?? "").trim();
  const primaryPos = (profile?.primary_position ?? "").trim();
  const secondaryPos = Array.isArray(profile?.secondary_positions) ? (profile!.secondary_positions as string[]).filter(Boolean) : [];
  const positionsValue = [primaryPos, ...secondaryPos].filter(Boolean).join(" · ") || "Not set";
  const expLabel = profile?.experience_level
    ? EXPERIENCE_LABELS[profile.experience_level] ?? profile.experience_level
    : null;
  const isSelfDeclared = profile?.verification_level === "self";
  const hostScoreValue = hosting && hosting.sessionsHosted > 0 ? hostScore(hosting.avgOverall) : null;

  return (
    <View style={styles.screen}>
      <Modal
        visible={reviewCodeModalOpen}
        transparent
        animationType="fade"
        onRequestClose={() => setReviewCodeModalOpen(false)}
      >
        <View style={styles.reviewModalBackdrop}>
          <View style={styles.reviewModalCard}>
            <Text style={styles.reviewModalTitle}>Review Mode</Text>
            <Text style={styles.reviewModalSub}>Enter the review secret code.</Text>
            <TextInput
              value={reviewCodeInput}
              onChangeText={setReviewCodeInput}
              autoCapitalize="characters"
              autoCorrect={false}
              secureTextEntry
              placeholder="Secret code"
              placeholderTextColor={themeColor().muted}
              style={styles.reviewModalInput}
            />
            <View style={styles.reviewModalActions}>
              <Pressable style={styles.reviewModalBtnGhost} onPress={() => setReviewCodeModalOpen(false)}>
                <Text style={styles.reviewModalBtnGhostText}>Cancel</Text>
              </Pressable>
              <Pressable style={styles.reviewModalBtnPrimary} onPress={() => submitReviewCode()}>
                <Text style={styles.reviewModalBtnPrimaryText}>Activate</Text>
              </Pressable>
            </View>
          </View>
        </View>
      </Modal>
      <Modal visible={deleteConfirmModalOpen} transparent animationType="fade" onRequestClose={closeDeleteConfirmModal}>
        <View style={styles.reviewModalBackdrop}>
          <View style={styles.reviewModalCard}>
            <Text style={styles.reviewModalTitle}>Confirm account deletion</Text>
            {deleteUpcomingWarning ? <Text style={styles.reviewModalSub}>{deleteUpcomingWarning}</Text> : null}
            <Text style={styles.reviewModalSub}>
              Type <Text style={{ fontWeight: "800", color: themeColor().text }}>{DELETE_CONFIRM_WORD}</Text> below to permanently
              delete your account.
            </Text>
            <TextInput
              value={deleteConfirmInput}
              onChangeText={setDeleteConfirmInput}
              autoCapitalize="none"
              autoCorrect={false}
              autoComplete="off"
              placeholder={DELETE_CONFIRM_WORD}
              placeholderTextColor={themeColor().muted}
              style={styles.reviewModalInput}
              editable={!deleteAccountBusy}
            />
            <View style={styles.reviewModalActions}>
              <Pressable style={styles.reviewModalBtnGhost} onPress={closeDeleteConfirmModal} disabled={deleteAccountBusy}>
                <Text style={styles.reviewModalBtnGhostText}>Cancel</Text>
              </Pressable>
              <Pressable
                style={[
                  styles.deleteConfirmModalBtn,
                  (!deleteConfirmMatches || deleteAccountBusy) && styles.deleteConfirmModalBtnDisabled,
                ]}
                onPress={() => void performDeleteAccount()}
                disabled={!deleteConfirmMatches || deleteAccountBusy}
              >
                {deleteAccountBusy ? (
                  <ActivityIndicator color={themeColor().text} size="small" />
                ) : (
                  <Text style={styles.deleteConfirmModalBtnText}>Delete account</Text>
                )}
              </Pressable>
            </View>
          </View>
        </View>
      </Modal>
      <Modal
        visible={editModalOpen}
        animationType="slide"
        presentationStyle="pageSheet"
        onRequestClose={() => setEditModalOpen(false)}
      >
        <View style={[styles.screen, { paddingTop: Platform.OS === "android" ? insets.top : 0 }]}>
          <View style={s.editModalHeader}>
            <Text style={s.editModalTitle}>Edit profile</Text>
            <Pressable onPress={() => setEditModalOpen(false)} hitSlop={12} style={s.editModalClose}>
              <FontAwesome name="close" size={20} color={themeColor().text} />
            </Pressable>
          </View>
          <KeyboardAvoidingView style={{ flex: 1 }} behavior={Platform.OS === "ios" ? "padding" : "height"}>
            <ScrollView contentContainerStyle={{ padding: 20, paddingBottom: 80 }} keyboardShouldPersistTaps="handled">
              <View style={s.actionPhotoField}>
                <PhotoUploadField
                  bucket="action-photos"
                  name="action"
                  label="Action photo"
                  hint="Optional. A shot of you playing, shown as a banner on your profile."
                  aspect="wide"
                  value={actionPhotoUrl}
                  onChange={saveActionPhoto}
                />
              </View>
              <ProfileSection
                editFirstName={editFirstName}
                setEditFirstName={setEditFirstName}
                editLastName={editLastName}
                setEditLastName={setEditLastName}
                editPlayingPosition={editPlayingPosition}
                setEditPlayingPosition={setEditPlayingPosition}
                editPrimaryPosition={editPrimaryPosition}
                setEditPrimaryPosition={setEditPrimaryPosition}
                editSecondaryPositions={editSecondaryPositions}
                setEditSecondaryPositions={setEditSecondaryPositions}
                editExperienceLevel={editExperienceLevel}
                setEditExperienceLevel={setEditExperienceLevel}
                editDateOfBirth={editDateOfBirth}
                setEditDateOfBirth={setEditDateOfBirth}
                editClubName={editClubName}
                setEditClubName={setEditClubName}
                editRosterUrl={editRosterUrl}
                setEditRosterUrl={setEditRosterUrl}
                editInstagram={editInstagram}
                setEditInstagram={setEditInstagram}
                editPhone={editPhone}
                setEditPhone={setEditPhone}
                editZipCode={editZipCode}
                setEditZipCode={setEditZipCode}
                editUsername={editUsername}
                setEditUsername={setEditUsername}
                editBusy={editBusy}
                profileNearestVenue={profile?.nearest_venue ?? null}
                profileRegionCode={profileRegionCode}
                profileZipCode={profile?.zip_code ?? null}
                hubRegionResolving={hubRegionResolving}
                hubVenueResolveDone={hubVenueResolveDone}
                usernameAutoFromName={usernameAutoFromName}
                positionPickerOpen={positionPickerOpen}
                setPositionPickerOpen={setPositionPickerOpen}
                primaryPositionPickerOpen={primaryPositionPickerOpen}
                setPrimaryPositionPickerOpen={setPrimaryPositionPickerOpen}
                experienceLevelPickerOpen={experienceLevelPickerOpen}
                setExperienceLevelPickerOpen={setExperienceLevelPickerOpen}
                profileSaveError={profileSaveError}
                editMsg={editMsg}
                editOk={editOk}
                onSave={() => void onSaveProfile()}
              />
            </ScrollView>
          </KeyboardAvoidingView>
        </View>
      </Modal>

      <KeyboardAvoidingView style={styles.scroll} behavior={Platform.OS === "ios" ? "padding" : "height"}>
        <ScrollView
          contentContainerStyle={[s.content, { paddingBottom: insets.bottom + 48 }]}
          keyboardShouldPersistTaps="handled"
        >
          <SettingsSection title="Shortcuts">
            <View style={s.group}>
              {isAdmin ? <Row icon="shield" label="Admin" onPress={() => push("/(tabs)/admin")} /> : null}
              <Row icon="trophy" label="Tournaments" onPress={() => push("/(tabs)/tournaments")} last />
            </View>
          </SettingsSection>

          <SettingsSection title="Account">
            <View style={s.group}>
              <Pressable
                style={s.row}
                onPress={pickAndUploadAvatar}
                disabled={avatarUploading}
                accessibilityLabel="Change profile photo"
              >
                <PlayerAvatar
                  person={{ first_name: profile?.first_name ?? null, last_name: profile?.last_name ?? null, avatar_url: avatarUrl }}
                  size={32}
                  style={s.rowAvatar}
                />
                <View style={{ flex: 1 }}>
                  <Text style={s.rowLabel}>Profile photo</Text>
                  <Text style={s.rowHint}>Crop to just you</Text>
                </View>
                {avatarUploading ? <ActivityIndicator color={themeColor().muted} /> : <Chevron />}
              </Pressable>
              <Row icon="user" label="Name" value={fullName || "Not set"} onPress={openEdit} />
              <Row icon="at" label="Username" value={uname ? `@${uname}` : "Not set"} onPress={openEdit} />
              <Row icon="envelope" label="Email" value={signedEmail} />
              <Row icon="phone" label="Phone" value={(profile?.phone ?? "").trim() || "Not set"} onPress={openEdit} last />
            </View>
          </SettingsSection>

          <SettingsSection title="Soccer">
            <View style={s.group}>
              <Row icon="shield" label="Positions" value={positionsValue} onPress={openEdit} />
              <Row icon="line-chart" label="Experience" value={expLabel ?? "Not set"} onPress={openEdit} />
              <Row icon="users" label="Club" value={(profile?.club_name ?? "").trim() || "Not set"} onPress={openEdit} />
              <Row
                icon="calendar-o"
                label="Date of birth"
                value={formatDob(profile?.date_of_birth ?? null) ?? "Not set"}
                onPress={openEdit}
                last
              />
            </View>
            {isSelfDeclared ? (
              <Pressable onPress={() => setVerificationModalOpen(true)} style={s.group}>
                <View style={s.noteBlock}>
                  <Text style={s.noteTitle}>Not verified</Text>
                  <Text style={s.noteBody}>
                    Your playing background is self-declared. Submit proof or get vouched to confirm your level.
                  </Text>
                </View>
              </Pressable>
            ) : null}
          </SettingsSection>

          <SettingsSection title="Verification">
            <View style={s.group}>
              <Row
                icon="instagram"
                label="Instagram"
                value={profile?.verification_level === "instagram" ? "Verified" : isSelfDeclared ? "Not verified" : undefined}
                onPress={() => push("/instagram-verification")}
                last
              />
            </View>
          </SettingsSection>

          <SettingsSection title="Preferences">
            <PreferencesSection
              pushEnabled={pushEnabled}
              pushBusy={pushBusy}
              pushMsg={pushMsg}
              onTogglePush={(v) => void onTogglePushNotifications(v)}
              pushDisabled={!accessToken}
              marketingPushEnabled={marketingPushEnabled}
              marketingPushBusy={marketingPushBusy}
              marketingPushMsg={marketingPushMsg}
              onToggleMarketingPush={(v) => void onToggleMarketingPush(v)}
              marketingPushDisabled={!accessToken}
              hostInvitesEnabled={hostInvitesEnabled}
              hostInvitesBusy={hostInvitesBusy}
              hostInvitesMsg={hostInvitesMsg}
              onToggleHostInvites={(v) => void onToggleHostInvites(v)}
              hostInvitesDisabled={!accessToken}
              maxDriveMinutes={maxDriveMinutes}
              maxDriveBusy={maxDriveBusy}
              maxDriveMsg={maxDriveMsg}
              maxDriveLabel={maxDriveLabel}
              minDrive={MIN_MAX_DRIVE_MINUTES}
              maxDrive={MAX_MAX_DRIVE_MINUTES}
              driveStep={MAX_DRIVE_STEP}
              onMaxDriveChange={setMaxDriveMinutes}
              onMaxDriveCommit={(v) => void onSaveMaxDriveMinutes(v)}
              maxDriveDisabled={!accessToken}
            />
            <View style={s.group}>
              <Row
                icon="map-marker"
                label="Region"
                value={profileRegionCode ?? ((profile?.nearest_venue ?? "").trim() || "Not set")}
                onPress={openEdit}
              />
              <Row icon="map-o" label="ZIP code" value={(profile?.zip_code ?? "").trim() || "Not set"} onPress={openEdit} last={!isAdmin} />
              {isAdmin ? (
                <View style={[s.row, s.rowLast]}>
                  <FontAwesome name="shield" size={17} color={themeColor().pitchText} style={s.rowIcon} />
                  <Text style={s.rowLabel}>Admin mode</Text>
                  <Switch
                    value={adminModeEnabled}
                    onValueChange={(v) => void setAdminModeEnabled(v)}
                    disabled={!adminModeReady}
                    trackColor={{ false: themeColor().overlayStrong, true: themeColor().pitch }}
                    thumbColor={themeColor().text}
                  />
                </View>
              ) : null}
            </View>
          </SettingsSection>

          <SettingsSection title="Appearance">
            <View style={s.group} accessibilityRole="radiogroup">
              {APPEARANCE_OPTIONS.map((opt, i) => {
                const selected = appearance === opt.value;
                return (
                  <Pressable
                    key={opt.value}
                    style={[s.row, i === APPEARANCE_OPTIONS.length - 1 && s.rowLast]}
                    onPress={() => void setAppearance(opt.value)}
                    accessibilityRole="radio"
                    accessibilityState={{ selected }}
                  >
                    <Text style={s.rowLabel}>
                      {opt.label}
                      {opt.value === "light" ? <Text style={s.rowHint}> (default)</Text> : null}
                    </Text>
                    <View style={[s.radio, selected && s.radioOn]}>
                      {selected ? <View style={s.radioDot} /> : null}
                    </View>
                  </Pressable>
                );
              })}
            </View>
          </SettingsSection>

          <SettingsSection title="Hosting">
            <View style={s.group}>
              {hostScoreValue != null ? (
                <View style={s.row}>
                  <FontAwesome name="star-o" size={17} color={themeColor().pitchText} style={s.rowIcon} />
                  <Text style={s.rowLabel}>Host score {hostScoreValue}/100</Text>
                </View>
              ) : null}
              <Row icon="plus-circle" label="Host a game" onPress={() => push("/session-create")} />
              <Row icon="history" label="Run history" onPress={() => push("/run-history")} last />
            </View>
          </SettingsSection>

          <SettingsSection title="Invite friends and credits">
            <View style={s.group}>
              <Row icon="ticket" label="Available credits" value={String(creditsCount ?? 0)} last />
            </View>
            <ReferralSection accessToken={accessToken} />
          </SettingsSection>

          <SettingsSection title="Legal">
            <View style={s.group}>
              <Row icon="file-o" label="Terms of Service" onPress={() => push("/terms")} />
              <Row icon="shield" label="Privacy Policy" onPress={() => push("/privacy-policy")} />
              <Row
                icon="file-text-o"
                label="Waiver"
                value={waiverLoading ? "…" : waiverAccepted ? "Accepted" : "Required"}
                valueColor={!waiverLoading && waiverAccepted ? themeColor().pitchText : undefined}
                onPress={() => push("/waiver")}
              />
              <Row icon="list-alt" label="Rules" onPress={() => push("/rules")} last />
            </View>
          </SettingsSection>

          <SettingsSection title="Help and about">
            <View style={s.group}>
              <Row icon="question-circle" label="Help" onPress={() => push("/help")} />
              <Row icon="envelope-o" label="Contact support" onPress={() => void Linking.openURL(SUPPORT_MAILTO)} />
              <Row icon="instagram" label="Instagram" value={`@${INSTAGRAM_HANDLE}`} onPress={() => void openBrandInstagram()} />
              <Row
                icon="info-circle"
                label="About this app"
                value={appVersion ? `v${appVersion}` : undefined}
                onPress={() => {
                  const next = aboutTapCount + 1;
                  setAboutTapCount(next);
                  if (next < REVIEW_MODE_TAP_TARGET) return;
                  setAboutTapCount(0);
                  openReviewCodeEntry();
                }}
                last
              />
            </View>
          </SettingsSection>

          <SettingsSection title="Security">
            <View style={s.inset}>
              <AppLockSection
                hasPin={hasPin}
                lockEnabled={lockEnabled}
                onEnableAppLock={requestEnrollment}
                lockUi={lockUi}
                setLockUi={setLockUi}
                changeOld={changeOld}
                setChangeOld={setChangeOld}
                changeNewA={changeNewA}
                setChangeNewA={setChangeNewA}
                changeNewB={changeNewB}
                setChangeNewB={setChangeNewB}
                removeCurrent={removeCurrent}
                setRemoveCurrent={setRemoveCurrent}
                lockBusy={lockBusy}
                setLockBusy={setLockBusy}
                lockMsg={lockMsg}
                setLockMsg={setLockMsg}
                biometricsEnabled={biometricsEnabled}
                biometricsAvailable={biometricsAvailable}
                onToggleBiometrics={(v) => void onToggleBiometrics(v)}
                changePin={changePin}
                removePin={removePin}
                lockNow={lockNow}
              />
            </View>
            <View style={s.group}>
              <Row
                icon="key"
                label={passwordResetBusy ? "Sending reset email…" : "Reset password"}
                onPress={() => void onSendPasswordReset()}
                last
              />
            </View>
          </SettingsSection>

          {__DEV__ ? (
            <SettingsSection title="Developer">
              <Pressable style={[styles.devReplayRow, s.devRow]} onPress={() => void replayAccountIntro()}>
                <Text style={styles.devReplayText}>Replay Account intro (dev only)</Text>
              </Pressable>
              <Pressable
                style={[styles.devReplayRow, s.devRow]}
                onPress={() => void replayOpeningThemeCtx?.replayOpeningTheme()}
              >
                <Text style={styles.devReplayText}>Replay opening theme (dev only)</Text>
              </Pressable>
            </SettingsSection>
          ) : null}

          <View style={s.section}>
            {reviewModeEnabled ? (
              <Pressable
                style={[styles.aboutRow, styles.reviewModeOffRow, s.flushRow]}
                onPress={() => {
                  Alert.alert("Turn off Review Mode?", "Client approval bypass will be disabled.", [
                    { text: "Cancel", style: "cancel" },
                    { text: "Turn off", onPress: () => void setReviewModeEnabled(false) },
                  ]);
                }}
              >
                <Text style={styles.reviewModeOffText}>Turn off App Review Mode</Text>
              </Pressable>
            ) : null}
            <Pressable style={[styles.aboutRow, s.flushRow]} onPress={() => void signOut()}>
              <View style={styles.aboutLeft}>
                <View style={styles.aboutIconWrap}>
                  <FontAwesome name="sign-out" size={18} color={themeColor().text} />
                </View>
                <Text style={styles.aboutText}>Sign out</Text>
              </View>
              <FontAwesome name="chevron-right" size={14} color={themeColor().muted} />
            </Pressable>
          </View>

          <View style={s.section}>
            <Pressable
              style={s.deleteBtn}
              disabled={deleteAccountBusy || !accessToken}
              onPress={() => void startDeleteAccountFlow()}
              accessibilityRole="button"
            >
              {deleteAccountBusy ? (
                <ActivityIndicator color={themeColor().coralText} />
              ) : (
                <Text style={[s.deleteText, !accessToken && styles.disabled]}>Delete account</Text>
              )}
            </Pressable>
          </View>
        </ScrollView>
        <VerificationRequestModal
          visible={verificationModalOpen}
          onClose={() => setVerificationModalOpen(false)}
          onSubmitted={() => void loadProfile()}
        />
      </KeyboardAvoidingView>
    </View>
  );
}

function SettingsSection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <View style={s.section}>
      <Text style={s.sectionTitle}>{title}</Text>
      {children}
    </View>
  );
}

function Chevron() {
  return <FontAwesome name="chevron-right" size={13} color={themeColor().muted} />;
}

function Row({
  icon,
  label,
  value,
  valueColor,
  onPress,
  last,
}: {
  icon: IconName;
  label: string;
  value?: string;
  valueColor?: string;
  onPress?: () => void;
  last?: boolean;
}) {
  const content = (
    <>
      <FontAwesome name={icon} size={17} color={themeColor().pitchText} style={s.rowIcon} />
      <Text style={s.rowLabel}>{label}</Text>
      {value != null ? (
        <Text style={[s.rowValue, valueColor ? { color: valueColor } : null]} numberOfLines={1}>
          {value}
        </Text>
      ) : null}
      {onPress ? <Chevron /> : null}
    </>
  );
  if (!onPress) return <View style={[s.row, last && s.rowLast]}>{content}</View>;
  return (
    <Pressable style={({ pressed }) => [s.row, last && s.rowLast, pressed && s.pressed]} onPress={onPress}>
      {content}
    </Pressable>
  );
}

function make_s() {
  return StyleSheet.create({
    content: { paddingHorizontal: 20, paddingTop: 8 },
    section: { marginTop: 24 },
    sectionTitle: { fontSize: 15, fontFamily: "Inter_600SemiBold", fontWeight: "600", color: themeColor().muted },
    group: {
      marginTop: 12,
      paddingHorizontal: 16,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: themeColor().line,
      backgroundColor: themeColor().card,
    },
    row: {
      flexDirection: "row",
      alignItems: "center",
      minHeight: 52,
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: themeColor().line,
    },
    rowLast: { borderBottomWidth: 0 },
    pressed: { opacity: 0.7 },
    rowIcon: { width: 28 },
    rowAvatar: { marginRight: 12 },
    rowLabel: { flex: 1, color: themeColor().text, fontSize: 16, fontFamily: "Inter_500Medium", fontWeight: "500" },
    rowHint: { color: themeColor().muted, fontSize: 14, fontFamily: "Inter_400Regular", fontWeight: "400" },
    rowValue: {
      color: themeColor().muted,
      fontSize: 14,
      fontFamily: "Inter_400Regular",
      marginRight: 8,
      maxWidth: "55%",
      textAlign: "right",
    },
    radio: {
      width: 22,
      height: 22,
      borderRadius: 11,
      borderWidth: 2,
      borderColor: themeColor().line,
      alignItems: "center",
      justifyContent: "center",
    },
    radioOn: { borderColor: themeColor().accent },
    radioDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: themeColor().accent },
    noteBlock: { paddingVertical: 12, gap: 4 },
    noteTitle: { color: themeColor().text, fontSize: 14, fontFamily: "Inter_600SemiBold", fontWeight: "600" },
    noteBody: { color: themeColor().muted, fontSize: 13, fontFamily: "Inter_400Regular", lineHeight: 18 },
    inset: { marginTop: 12 },
    devRow: { marginTop: 12 },
    flushRow: { marginTop: 12 },
    deleteBtn: { paddingVertical: 12, alignItems: "center" },
    deleteText: { color: themeColor().coralText, fontSize: 16, fontFamily: "Inter_600SemiBold", fontWeight: "600" },
    editModalHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 20,
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: themeColor().overlay,
    },
    editModalTitle: { color: themeColor().text, fontSize: 20, ...headline },
    editModalClose: { padding: 4 },
    actionPhotoField: { marginBottom: 24 },
  });
}
let s = make_s();
function publish_s() {
  s = make_s();
}
