import { useAccountIntroReplay } from "@/context/AccountIntroReplayContext";
import { useReplayOpeningTheme } from "@/context/ReplayOpeningThemeContext";
import { useAdminMode } from "@/context/AdminModeContext";
import { useAuth } from "@/context/AuthContext";
import { useProfileAdmin } from "@/context/ProfileAdminContext";
import { useAppLock } from "@/context/AppLockContext";
import { siteOrigin } from "@/lib/env";
import {
  normalizeProfileUsername,
  PROFILE_USERNAME_MAX_LEN,
  USERNAME_TAKEN_USER_MESSAGE,
  usernameMatchesAutoGeneratedFromNames,
} from "@/lib/profileIdentityFields";
import { getNearestVenues, getNearestVenuesFromApi, type VenueDistanceRow } from "@/lib/venueDistance";
import { getInstallationContext, resolveExpoPushTokenForApp, shouldRegisterPushToken } from "@/lib/pushToken";
import { hapticTap } from "@/lib/haptics";
import { fetchPickupStanding, postMobilePushPreference, postMobilePushToken } from "@/lib/siteApi";
import * as LocalAuthentication from "expo-local-authentication";
import * as Notifications from "expo-notifications";
import * as Device from "expo-device";
import Constants from "expo-constants";
import { useReviewMode } from "@/context/ReviewModeContext";
import { REVIEW_MODE_SECRET, REVIEW_MODE_TAP_TARGET } from "@/lib/reviewMode";
import { useFocusEffect, useRouter } from "expo-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import {
  ActivityIndicator,
  Alert,
  KeyboardAvoidingView,
  Linking,
  Platform,
  Pressable,
  RefreshControl,
  ScrollView,
  Switch,
  Modal,
  Text,
  TextInput,
  View,
} from "react-native";
import FontAwesome from "@expo/vector-icons/FontAwesome";
import { AppLockSection } from "@/components/account/AppLockSection";
import { PreferencesSection } from "@/components/account/PreferencesSection";
import { ProfileSection } from "@/components/account/ProfileSection";
import { ReferralSection } from "@/components/account/ReferralSection";
import { ReliabilitySection } from "@/components/account/ReliabilitySection";
import {
  accountStyles as styles,
  LIME,
  POSITION_OPTIONS,
  type PositionValue,
} from "@/components/account/accountStyles";

const SUPPORT_EMAIL = "pickupct@gmail.com";
const SUPPORT_MAILTO = `mailto:${SUPPORT_EMAIL}`;

const MIN_MAX_DRIVE_MINUTES = 35;
const MAX_MAX_DRIVE_MINUTES = 90;
const DEFAULT_MAX_DRIVE_MINUTES = 50;
const MAX_DRIVE_STEP = 5;
function clampMaxDriveMinutes(value: number): number {
  const stepped = Math.round(value / MAX_DRIVE_STEP) * MAX_DRIVE_STEP;
  return Math.min(MAX_MAX_DRIVE_MINUTES, Math.max(MIN_MAX_DRIVE_MINUTES, stepped));
}

function maxDriveLabel(minutes: number): string {
  return `Up to ${minutes} min drive`;
}

type ProfileRow = {
  first_name: string | null;
  last_name: string | null;
  approved: boolean | null;
  instagram: string | null;
  phone: string | null;
  zip_code: string | null;
  nearest_venue: string | null;
  playing_position: string | null;
  username: string | null;
  push_notifications_enabled: boolean | null;
  marketing_push_enabled: boolean | null;
  max_drive_minutes: number | null;
};

const PROFILE_SELECT_WITH_PUSH =
  "first_name,last_name,approved,instagram,phone,zip_code,nearest_venue,playing_position,username,push_notifications_enabled,marketing_push_enabled,max_drive_minutes";

const PROFILE_SELECT_WITHOUT_PUSH =
  "first_name,last_name,approved,instagram,phone,zip_code,nearest_venue,playing_position,username,max_drive_minutes";

function supabaseLooksLikeMissingColumn(err: { message?: string } | null | undefined, col: string): boolean {
  const msg = err?.message ?? "";
  if (!msg) return false;
  const re = new RegExp(col.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "i");
  return re.test(msg) && (/column/i.test(msg) || /schema cache/i.test(msg) || /Could not find/i.test(msg));
}

function cleanInstagram(s: string): string {
  return s.trim().replace(/^@/, "").replace(/\s+/g, "");
}

function formatProfileSaveError(err: unknown): string {
  if (err && typeof err === "object" && "message" in err) {
    const o = err as { message?: string; details?: string; hint?: string; code?: string };
    const parts = [o.message, o.details, o.hint].filter((s) => typeof s === "string" && s.trim());
    if (parts.length) return parts.join(" — ");
    if (o.code) return `Error code ${o.code}`;
  }
  if (err instanceof Error) return err.message;
  return String(err);
}

export default function AccountScreen() {
  const router = useRouter();
  const { replay: replayAccountIntro } = useAccountIntroReplay();
  const replayOpeningThemeCtx = useReplayOpeningTheme();
  const { session, supabase, isReady, signOut } = useAuth();
  const { enabled: adminModeEnabled, isReady: adminModeReady, setEnabled: setAdminModeEnabled } = useAdminMode();
  const { enabled: reviewModeEnabled, setEnabled: setReviewModeEnabled } = useReviewMode();
  const { isAdmin, isReady: profileAdminReady } = useProfileAdmin();
  const {
    hasPin,
    changePin,
    removePin,
    biometricsEnabled,
    biometricsAvailable,
    setBiometricsEnabled,
    refreshBiometricAvailability,
    lockNow,
  } = useAppLock();

  const [lockUi, setLockUi] = useState<"idle" | "change" | "remove">("idle");
  const [changeOld, setChangeOld] = useState("");
  const [changeNewA, setChangeNewA] = useState("");
  const [changeNewB, setChangeNewB] = useState("");
  const [removeCurrent, setRemoveCurrent] = useState("");
  const [lockBusy, setLockBusy] = useState(false);
  const [lockMsg, setLockMsg] = useState<string | null>(null);

  const [profile, setProfile] = useState<ProfileRow | null>(null);

  const [editFirstName, setEditFirstName] = useState("");
  const [editLastName, setEditLastName] = useState("");
  const [editPlayingPosition, setEditPlayingPosition] = useState<PositionValue | null>(null);
  const [editInstagram, setEditInstagram] = useState("");
  const [editPhone, setEditPhone] = useState("");
  const [editZipCode, setEditZipCode] = useState("");
  const [editUsername, setEditUsername] = useState("");
  const [editBusy, setEditBusy] = useState(false);
  const [editMsg, setEditMsg] = useState<string | null>(null);
  const [profileSaveError, setProfileSaveError] = useState<string | null>(null);
  const [editOk, setEditOk] = useState(false);
  const [positionPickerOpen, setPositionPickerOpen] = useState(false);

  const [waiverAccepted, setWaiverAccepted] = useState<boolean | null>(null);
  const [waiverVersion, setWaiverVersion] = useState<string | null>(null);
  const [waiverLoading, setWaiverLoading] = useState(true);

  const [reliabilityLoading, setReliabilityLoading] = useState(true);
  const [reliabilityLabel, setReliabilityLabel] = useState<string | null>(null);
  const [reliabilityScorePct, setReliabilityScorePct] = useState<number | null>(null);
  const [reliabilitySubtext, setReliabilitySubtext] = useState<string | null>(null);


  const [deleteAccountBusy, setDeleteAccountBusy] = useState(false);

  const [pushEnabled, setPushEnabled] = useState(true);
  const [pushBusy, setPushBusy] = useState(false);
  const [pushMsg, setPushMsg] = useState<string | null>(null);
  const [marketingPushEnabled, setMarketingPushEnabled] = useState(false);
  const [marketingPushBusy, setMarketingPushBusy] = useState(false);
  const [marketingPushMsg, setMarketingPushMsg] = useState<string | null>(null);
  const [maxDriveMinutes, setMaxDriveMinutes] = useState(DEFAULT_MAX_DRIVE_MINUTES);
  const [maxDriveBusy, setMaxDriveBusy] = useState(false);
  const [maxDriveMsg, setMaxDriveMsg] = useState<string | null>(null);
  const [refreshing, setRefreshing] = useState(false);
  const [aboutTapCount, setAboutTapCount] = useState(0);
  const [reviewCodeModalOpen, setReviewCodeModalOpen] = useState(false);
  const [reviewCodeInput, setReviewCodeInput] = useState("");

  const appVersion =
    Constants.expoConfig?.version ?? Constants.nativeAppVersion ?? "1.0.0";

  function submitReviewCode() {
    if (reviewCodeInput.trim() === REVIEW_MODE_SECRET) {
      void setReviewModeEnabled(true);
      setReviewCodeModalOpen(false);
      setReviewCodeInput("");
      Alert.alert("Review Mode", "App Review Mode is now active.");
    } else {
      Alert.alert("Review Mode", "Incorrect code.");
    }
  }

  function openReviewCodeEntry() {
    setReviewCodeInput("");
    if (Platform.OS === "ios" && typeof Alert.prompt === "function") {
      Alert.prompt(
        "Review Mode",
        "Enter the review secret code.",
        [
          { text: "Cancel", style: "cancel" },
          {
            text: "Activate",
            onPress: (value) => {
              if (String(value ?? "").trim() === REVIEW_MODE_SECRET) {
                void setReviewModeEnabled(true);
                Alert.alert("Review Mode", "App Review Mode is now active.");
              } else {
                Alert.alert("Review Mode", "Incorrect code.");
              }
            },
          },
        ],
        "secure-text",
      );
      return;
    }
    setReviewCodeModalOpen(true);
  }

  useEffect(() => {
    void refreshBiometricAvailability();
  }, [refreshBiometricAvailability]);

  const accessToken = session?.access_token ?? null;

  const usernameAutoFromName = useMemo(
    () => usernameMatchesAutoGeneratedFromNames(editUsername, editFirstName, editLastName),
    [editUsername, editFirstName, editLastName],
  );

  const loadProfile = useCallback(async () => {
    const uid = session?.user?.id;
    if (!isReady || !supabase || !uid) {
      return;
    }
    try {
      let res = await supabase.from("profiles").select(PROFILE_SELECT_WITH_PUSH).eq("id", uid).maybeSingle();
      if (res.error) {
        console.error("[account loadProfile] Supabase error", JSON.stringify(res.error));
        if (
          supabaseLooksLikeMissingColumn(res.error, "push_notifications_enabled") ||
          supabaseLooksLikeMissingColumn(res.error, "marketing_push_enabled") ||
          supabaseLooksLikeMissingColumn(res.error, "max_drive_minutes")
        ) {
          res = await supabase.from("profiles").select(PROFILE_SELECT_WITHOUT_PUSH).eq("id", uid).maybeSingle();
          if (res.error) {
            console.error("[account loadProfile] fallback select error", JSON.stringify(res.error));
            setProfile(null);
            return;
          }
          const row = res.data as Omit<ProfileRow, "push_notifications_enabled"> | null;
          setProfile(
            row
              ? {
                  ...row,
                  push_notifications_enabled: true,
                  marketing_push_enabled: false,
                  max_drive_minutes:
                    row.max_drive_minutes == null
                      ? DEFAULT_MAX_DRIVE_MINUTES
                      : clampMaxDriveMinutes(Number(row.max_drive_minutes)),
                }
              : null,
          );
          return;
        }
        setProfile(null);
        return;
      }
      const row = res.data as ProfileRow | null;
      setProfile(
        row
          ? {
              ...row,
              max_drive_minutes:
                row.max_drive_minutes == null
                  ? DEFAULT_MAX_DRIVE_MINUTES
                  : clampMaxDriveMinutes(Number(row.max_drive_minutes)),
            }
          : null,
      );
    } catch (e) {
      console.error("[account loadProfile] exception", e);
      setProfile(null);
    }
  }, [isReady, supabase, session?.user?.id]);

  useFocusEffect(
    useCallback(() => {
      void loadProfile();
    }, [loadProfile]),
  );

  // Re-fetch when auth/session becomes available after focus (useFocusEffect does not re-run when loadProfile's deps update).
  useEffect(() => {
    void loadProfile();
  }, [loadProfile]);

  useEffect(() => {
    if (!profile || editBusy) return;
    setEditFirstName(String(profile.first_name ?? ""));
    setEditLastName(String(profile.last_name ?? ""));
    const rawPos = String(profile.playing_position ?? "").trim();
    setEditPlayingPosition(
      (POSITION_OPTIONS as readonly { value: string }[]).some((o) => o.value === rawPos) ? (rawPos as PositionValue) : null,
    );
    setEditInstagram(profile.instagram ? String(profile.instagram).replace(/^@/, "") : "");
    setEditPhone(String(profile.phone ?? ""));
    setEditZipCode(String(profile.zip_code ?? "").replace(/\D/g, "").slice(0, 5));
    setEditUsername(String(profile.username ?? ""));
    setPushEnabled(profile.push_notifications_enabled !== false);
    setMarketingPushEnabled(profile.marketing_push_enabled === true);
    const storedMax =
      profile.max_drive_minutes == null ? DEFAULT_MAX_DRIVE_MINUTES : Number(profile.max_drive_minutes);
    setMaxDriveMinutes(clampMaxDriveMinutes(storedMax));
  }, [profile, editBusy]);

  const loadWaiverStatus = useCallback(async (opts?: { silent?: boolean }) => {
    if (!isReady) return;
    const origin = siteOrigin();
    if (!origin || !accessToken) {
      if (!opts?.silent) {
        setWaiverLoading(false);
        setWaiverAccepted(null);
        setWaiverVersion(null);
      }
      return;
    }
    if (!opts?.silent) setWaiverLoading(true);
    try {
      const r = await fetch(`${origin}/api/waiver/status`, {
        method: "GET",
        headers: {
          Accept: "application/json",
          Authorization: `Bearer ${accessToken}`,
        },
        cache: "no-store",
      });
      const j = (await r.json().catch(() => null)) as
        | { accepted?: boolean; currentVersion?: string }
        | null;
      if (!r.ok || !j) {
        setWaiverAccepted(null);
        setWaiverVersion(null);
      } else {
        setWaiverAccepted(Boolean(j.accepted));
        setWaiverVersion(typeof j.currentVersion === "string" ? j.currentVersion : null);
      }
    } catch {
      setWaiverAccepted(null);
      setWaiverVersion(null);
    } finally {
      if (!opts?.silent) setWaiverLoading(false);
    }
  }, [isReady, accessToken]);

  const loadReliability = useCallback(async (opts?: { silent?: boolean }) => {
    if (!isReady) return;
    if (!accessToken) {
      if (!opts?.silent) {
        setReliabilityLoading(false);
        setReliabilityLabel(null);
        setReliabilityScorePct(null);
        setReliabilitySubtext(null);
      }
      return;
    }
    if (!opts?.silent) setReliabilityLoading(true);
    const r = await fetchPickupStanding(accessToken);
    if (r.ok && r.data?.ok && r.data.reliability) {
      const rel = r.data.reliability;
      setReliabilityLabel(rel.user_label ?? null);
      setReliabilityScorePct(rel.score_pct == null ? null : Math.round(Number(rel.score_pct)));
      setReliabilitySubtext(rel.user_subtext ?? null);
    } else {
      setReliabilityLabel(null);
      setReliabilityScorePct(null);
      setReliabilitySubtext(null);
    }
    if (!opts?.silent) setReliabilityLoading(false);
  }, [isReady, accessToken]);

  const onRefresh = useCallback(async () => {
    setRefreshing(true);
    try {
      await Promise.all([
        loadProfile(),
        loadWaiverStatus({ silent: true }),
        loadReliability({ silent: true }),
      ]);
    } finally {
      setRefreshing(false);
    }
  }, [loadProfile, loadWaiverStatus, loadReliability]);

  async function onSaveProfile() {
    setEditMsg(null);
    setProfileSaveError(null);
    setEditOk(false);

    if (!supabase) {
      setProfileSaveError("Save failed: Supabase client is not available. Check app configuration.");
      return;
    }

    const userId = session?.user?.id;
    if (!userId) {
      setProfileSaveError("Save failed: Not signed in.");
      return;
    }

    const firstName = editFirstName.trim();
    const lastName = editLastName.trim();
    const playingPosition = editPlayingPosition;
    const instagram = cleanInstagram(editInstagram);
    const phone = editPhone.trim();
    const zipDigits = editZipCode.replace(/\D/g, "").slice(0, 5);
    const usernameRaw = editUsername.trim();
    const storedUsername = (profile?.username ?? "").trim();
    let usernameResolved: string | null = null;
    if (usernameRaw) {
      const matchesStored =
        storedUsername.length > 0 && usernameRaw.toLowerCase() === storedUsername.toLowerCase();
      const norm = normalizeProfileUsername(usernameRaw);
      if (!matchesStored && !norm) {
        setProfileSaveError(
          "Save failed: Username must be 3–30 characters, lowercase letters and numbers only.",
        );
        return;
      }
      usernameResolved = matchesStored ? storedUsername : norm!;
    }

    const zipStored = zipDigits.length === 5 ? zipDigits : null;

    setEditBusy(true);
    try {
      let nearestVenues: VenueDistanceRow[] = [];
      if (zipStored) {
        const originForVenues = siteOrigin();
        if (originForVenues) {
          try {
            nearestVenues = await getNearestVenuesFromApi(zipStored, originForVenues, accessToken);
          } catch (e) {
            console.error("[onSaveProfile] getNearestVenuesFromApi exception", e);
          }
        }
        if (nearestVenues.length === 0) {
          nearestVenues = getNearestVenues(zipStored);
        }
      }
      const nearestVenue = nearestVenues[0]?.venue ?? null;

      const updatedAt = new Date().toISOString();
      const coreUpdate = {
        first_name: firstName || null,
        last_name: lastName || null,
        playing_position: playingPosition ?? null,
        instagram: instagram || null,
        phone: phone || null,
        zip_code: zipStored,
        username: usernameResolved,
        updated_at: updatedAt,
      };

      const origin = siteOrigin();
      if (origin && accessToken) {
        try {
          const r = await fetch(`${origin}/api/account/profile`, {
            method: "PATCH",
            headers: {
              Accept: "application/json",
              "Content-Type": "application/json",
              Authorization: `Bearer ${accessToken}`,
            },
            body: JSON.stringify({ ...coreUpdate, nearest_venue: nearestVenue }),
            cache: "no-store",
          });
          const j = (await r.json().catch(() => null)) as { ok?: boolean; error?: string } | null;
          if (!r.ok) {
            const errLine =
              typeof j?.error === "string" && j.error.trim()
                ? j.error.trim()
                : `HTTP ${r.status} ${r.statusText || ""}`.trim();
            setProfileSaveError(`Save failed: ${errLine}`);
            return;
          }
          if (j && j.ok === false && typeof j.error === "string" && j.error.trim()) {
            setProfileSaveError(`Save failed: ${j.error.trim()}`);
            return;
          }
        } catch (e) {
          console.error("[onSaveProfile] /api/account/profile fetch exception", e);
          setProfileSaveError(`Save failed: ${formatProfileSaveError(e)}`);
          return;
        }
      } else {
        let data: { id: string }[] | null = null;
        let error: { message?: string; code?: string } | null = null;

        try {
          const withVenue = await supabase
            .from("profiles")
            .update({ ...coreUpdate, nearest_venue: nearestVenue })
            .eq("id", userId)
            .select("id");
          data = withVenue.data;
          error = withVenue.error;
          if (error && supabaseLooksLikeMissingColumn(error, "nearest_venue")) {
            console.error("[onSaveProfile] retrying without nearest_venue", JSON.stringify(error));
            const noVenue = await supabase.from("profiles").update(coreUpdate).eq("id", userId).select("id");
            data = noVenue.data;
            error = noVenue.error;
          }
        } catch (e) {
          console.error("[onSaveProfile] profiles.update exception", e);
          setProfileSaveError(`Save failed: ${formatProfileSaveError(e)}`);
          return;
        }

        if (error) {
          console.error("[onSaveProfile] supabase.from('profiles').update error", JSON.stringify(error));
          const code = (error as { code?: string }).code;
          const dup =
            code === "23505" ||
            /profiles_username_lower_unique|duplicate key/i.test(error.message ?? "");
          setProfileSaveError(
            `Save failed: ${
              dup ? USERNAME_TAKEN_USER_MESSAGE : formatProfileSaveError(error)
            }`,
          );
          return;
        }

        if (!data?.length) {
          console.error("[onSaveProfile] update returned 0 rows", { userId });
          setProfileSaveError(
            "Save failed: Save did not update any profile row (no match or not permitted). Your account may be missing a profile row.",
          );
          return;
        }
      }

      const nextFields = {
        first_name: firstName || null,
        last_name: lastName || null,
        playing_position: playingPosition ?? null,
        instagram: instagram || null,
        phone: phone || null,
        zip_code: zipDigits.length === 5 ? zipDigits : null,
        username: usernameResolved,
        nearest_venue: nearestVenue,
      };
      setProfile((p) => {
        if (p) {
          return { ...p, ...nextFields };
        }
        return {
          ...nextFields,
          approved: null,
          push_notifications_enabled: pushEnabled,
        };
      });
      setEditFirstName(firstName);
      setEditLastName(lastName);
      setEditPlayingPosition(playingPosition);
      setEditInstagram(instagram || "");
      setEditPhone(phone);
      setEditZipCode(zipDigits.length === 5 ? zipDigits : "");
      setEditUsername(usernameResolved ?? "");
      setEditOk(true);
      setEditMsg("Saved.");
    } catch (e) {
      console.error("[onSaveProfile] exception", e);
      setProfileSaveError(`Save failed: ${formatProfileSaveError(e)}`);
    } finally {
      setEditBusy(false);
    }
  }

  async function onSaveMaxDriveMinutes(nextRaw: number) {
    const next = clampMaxDriveMinutes(nextRaw);
    if (maxDriveBusy) return;
    setMaxDriveMsg(null);
    if (!supabase) {
      setMaxDriveMsg("Supabase client is not available. Check app configuration.");
      return;
    }
    const uid = session?.user?.id;
    if (!uid) {
      setMaxDriveMsg("Sign in again to change this.");
      return;
    }

    const prev = maxDriveMinutes;
    setMaxDriveMinutes(next);
    setMaxDriveBusy(true);
    try {
      const res = await supabase
        .from("profiles")
        .update({
          max_drive_minutes: next,
          updated_at: new Date().toISOString(),
        })
        .eq("id", uid)
        .select("id");
      const { error } = res;
      if (error) {
        setMaxDriveMinutes(prev);
        setMaxDriveMsg(formatProfileSaveError(error));
        return;
      }
      if (!res.data?.length) {
        setMaxDriveMinutes(prev);
        setMaxDriveMsg("Save did not update any profile row.");
        return;
      }
      setProfile((p) => (p ? { ...p, max_drive_minutes: next } : p));
    } catch (e) {
      setMaxDriveMinutes(prev);
      setMaxDriveMsg(formatProfileSaveError(e));
    } finally {
      setMaxDriveBusy(false);
    }
  }

  async function onTogglePushNotifications(next: boolean) {
    if (pushBusy) return;
    setPushMsg(null);
    if (!supabase) {
      setPushMsg("Supabase client is not available. Check app configuration.");
      return;
    }
    if (!accessToken) {
      setPushMsg("Sign in again to change this.");
      return;
    }
    const uid = session?.user?.id;
    if (!uid) {
      setPushMsg("Sign in again to change this.");
      return;
    }

    const prev = pushEnabled;
    setPushEnabled(next);
    setPushBusy(true);
    try {
      let data: { id: string }[] | null = null;
      try {
        const res = await supabase
          .from("profiles")
          .update({
            push_notifications_enabled: next,
            updated_at: new Date().toISOString(),
          })
          .eq("id", uid)
          .select("id");
        data = res.data;
        const { error } = res;
        if (error) {
          console.log("[push-pref] profiles.update Supabase error:", error);
          console.log("[push-pref] profiles.update Supabase error JSON:", JSON.stringify(error));
          setPushEnabled(prev);
          setPushMsg(formatProfileSaveError(error));
          return;
        }
        if (!data?.length) {
          console.log("[push-pref] profiles.update returned 0 rows", { userId: uid });
          setPushEnabled(prev);
          setPushMsg(
            "Save did not update any profile row (no match or not permitted). Your account may be missing a profile row.",
          );
          return;
        }
      } catch (e) {
        console.log("[push-pref] profiles.update exception:", e);
        setPushEnabled(prev);
        setPushMsg(formatProfileSaveError(e));
        return;
      }

      setProfile((p) =>
        p ? { ...p, push_notifications_enabled: next, marketing_push_enabled: next ? p.marketing_push_enabled : false } : p,
      );

      if (!next) {
        setMarketingPushEnabled(false);
        try {
          await supabase
            .from("profiles")
            .update({ marketing_push_enabled: false, updated_at: new Date().toISOString() })
            .eq("id", uid);
        } catch (e) {
          console.log("[push-pref] marketing_push_enabled off exception:", e);
        }
        try {
          const { error: delErr } = await supabase.from("user_push_devices").delete().eq("user_id", uid);
          if (delErr) {
            console.log("[push-pref] user_push_devices.delete Supabase error:", delErr);
            console.log("[push-pref] user_push_devices.delete Supabase error JSON:", JSON.stringify(delErr));
          }
        } catch (e) {
          console.log("[push-pref] user_push_devices.delete exception:", e);
        }
        try {
          const res = await postMobilePushPreference(accessToken, false);
          if (!res.ok) {
            console.log("[push-pref] postMobilePushPreference(false) failed:", res.error);
          }
        } catch (e) {
          console.log("[push-pref] postMobilePushPreference(false) exception:", e);
        }
      } else if (Device.isDevice) {
        try {
          if (!shouldRegisterPushToken()) return;

          const { status: existing } = await Notifications.getPermissionsAsync();
          let finalStatus = existing;
          if (existing !== "granted") {
            const req = await Notifications.requestPermissionsAsync();
            finalStatus = req.status;
          }
          if (finalStatus === "granted") {
            const installationContext = getInstallationContext();
            if (installationContext === "storeClient") return;

            const expoPushToken = await resolveExpoPushTokenForApp();
            const platform = Platform.OS === "ios" ? "ios" : Platform.OS === "android" ? "android" : null;
            if (expoPushToken && platform) {
              const reg = await postMobilePushToken(accessToken, expoPushToken, platform, installationContext);
              if (!reg.ok) {
                console.log("[push-pref] postMobilePushToken failed:", reg.error);
              }
            }
          }
        } catch (e) {
          console.log("[push-pref] token re-register exception:", e);
        }
      }
    } finally {
      setPushBusy(false);
    }
  }

  async function onToggleMarketingPush(next: boolean) {
    if (marketingPushBusy) return;
    setMarketingPushMsg(null);
    if (!pushEnabled && next) {
      setMarketingPushMsg("Turn on push notifications first.");
      return;
    }
    if (!supabase) {
      setMarketingPushMsg("Supabase client is not available. Check app configuration.");
      return;
    }
    if (!accessToken) {
      setMarketingPushMsg("Sign in again to change this.");
      return;
    }
    const uid = session?.user?.id;
    if (!uid) {
      setMarketingPushMsg("Sign in again to change this.");
      return;
    }

    const prev = marketingPushEnabled;
    setMarketingPushEnabled(next);
    setMarketingPushBusy(true);
    try {
      const res = await supabase
        .from("profiles")
        .update({
          marketing_push_enabled: next,
          updated_at: new Date().toISOString(),
        })
        .eq("id", uid)
        .select("id");
      const { error } = res;
      if (error) {
        setMarketingPushEnabled(prev);
        if (supabaseLooksLikeMissingColumn(error, "marketing_push_enabled")) {
          setMarketingPushMsg("Marketing push preference is not available yet. Apply the latest database migration.");
        } else {
          setMarketingPushMsg(formatProfileSaveError(error));
        }
        return;
      }
      if (!res.data?.length) {
        setMarketingPushEnabled(prev);
        setMarketingPushMsg("Save did not update any profile row.");
        return;
      }

      try {
        await supabase
          .from("user_push_devices")
          .update({ marketing_push_enabled: next, updated_at: new Date().toISOString() })
          .eq("user_id", uid);
      } catch (e) {
        console.log("[marketing-push] user_push_devices sync exception:", e);
      }

      setProfile((p) => (p ? { ...p, marketing_push_enabled: next } : p));
    } catch (e) {
      setMarketingPushEnabled(prev);
      setMarketingPushMsg(formatProfileSaveError(e));
    } finally {
      setMarketingPushBusy(false);
    }
  }

  async function onToggleBiometrics(next: boolean) {
    setLockMsg(null);
    if (!next) {
      await setBiometricsEnabled(false);
      return;
    }
    if (!biometricsAvailable) {
      setLockMsg("Biometrics aren’t available on this device.");
      return;
    }
    const r = await LocalAuthentication.authenticateAsync({
      promptMessage: "Turn on Face ID for CT Pickup",
      cancelLabel: "Cancel",
    });
    if (r.success) await setBiometricsEnabled(true);
  }

  if (!isReady || !profileAdminReady) {
    return (
      <View style={styles.center}>
        <ActivityIndicator size="large" color="#fff" />
      </View>
    );
  }

  const signedEmail = session?.user?.email;
  if (!signedEmail) {
    return (
      <View style={styles.center}>
        <ActivityIndicator size="large" color="#fff" />
      </View>
    );
  }

  return (
    <View style={styles.screen}>
      <Modal
        visible={reviewCodeModalOpen}
        transparent
        animationType="fade"
        onRequestClose={() => setReviewCodeModalOpen(false)}
      >
        <View style={styles.reviewModalBackdrop}>
          <View style={styles.reviewModalCard}>
            <Text style={styles.reviewModalTitle}>Review Mode</Text>
            <Text style={styles.reviewModalSub}>Enter the review secret code.</Text>
            <TextInput
              value={reviewCodeInput}
              onChangeText={setReviewCodeInput}
              autoCapitalize="characters"
              autoCorrect={false}
              secureTextEntry
              placeholder="Secret code"
              placeholderTextColor="rgba(255,255,255,0.35)"
              style={styles.reviewModalInput}
            />
            <View style={styles.reviewModalActions}>
              <Pressable style={styles.reviewModalBtnGhost} onPress={() => setReviewCodeModalOpen(false)}>
                <Text style={styles.reviewModalBtnGhostText}>Cancel</Text>
              </Pressable>
              <Pressable style={styles.reviewModalBtnPrimary} onPress={() => submitReviewCode()}>
                <Text style={styles.reviewModalBtnPrimaryText}>Activate</Text>
              </Pressable>
            </View>
          </View>
        </View>
      </Modal>
      <KeyboardAvoidingView style={styles.scroll} behavior={Platform.OS === "ios" ? "padding" : "height"}>
        <ScrollView
          contentContainerStyle={[styles.content, { paddingBottom: 200 }]}
          keyboardShouldPersistTaps="handled"
          refreshControl={
            <RefreshControl
              refreshing={refreshing}
              onRefresh={() => void onRefresh()}
              tintColor={LIME}
            />
          }
        >
          <Text style={styles.title}>Account</Text>
          <Text style={styles.sub}>
            Email sign-in, push, and your device passcode{"\n"}
            (same one-time email code Supabase sends you).
          </Text>

        <View style={[styles.card, styles.cardLime]}>
          <Text style={styles.signedLabel}>SIGNED IN</Text>
          <Text style={styles.email}>{signedEmail}</Text>
          <Text style={styles.signedAssist}>You&apos;re signed in on this device. Push reminders use your account.</Text>
          <Pressable style={styles.outlineBtnLime} onPress={() => void signOut()}>
            <Text style={styles.outlineBtnLimeText}>Sign out</Text>
          </Pressable>
        </View>

        <ProfileSection
          editFirstName={editFirstName}
          setEditFirstName={setEditFirstName}
          editLastName={editLastName}
          setEditLastName={setEditLastName}
          editPlayingPosition={editPlayingPosition}
          setEditPlayingPosition={setEditPlayingPosition}
          editInstagram={editInstagram}
          setEditInstagram={setEditInstagram}
          editPhone={editPhone}
          setEditPhone={setEditPhone}
          editZipCode={editZipCode}
          setEditZipCode={setEditZipCode}
          editUsername={editUsername}
          setEditUsername={setEditUsername}
          editBusy={editBusy}
          profileNearestVenue={profile?.nearest_venue ?? null}
          usernameAutoFromName={usernameAutoFromName}
          positionPickerOpen={positionPickerOpen}
          setPositionPickerOpen={setPositionPickerOpen}
          profileSaveError={profileSaveError}
          editMsg={editMsg}
          editOk={editOk}
          onSave={() => void onSaveProfile()}
        />

        <Text style={styles.sectionTitle}>Waiver</Text>
        <View style={styles.card}>
          {waiverLoading ? (
            <View style={styles.cardLoadingRow}>
              <ActivityIndicator color="#fff" />
              <Text style={styles.cardLoadingText}>Checking waiver…</Text>
            </View>
          ) : waiverAccepted ? (
            <>
              <View style={styles.statusRow}>
                <View style={[styles.statusPill, styles.statusPillGreen]}>
                  <Text style={[styles.statusPillText, styles.statusPillTextGreen]}>
                    Waiver accepted
                  </Text>
                </View>
              </View>
              {waiverVersion ? (
                <Text style={styles.cardSubtle}>Version {waiverVersion}</Text>
              ) : null}
            </>
          ) : (
            <>
              <View style={styles.statusRow}>
                <View style={[styles.statusPill, styles.statusPillAmber]}>
                  <Text style={[styles.statusPillText, styles.statusPillTextAmber]}>
                    Waiver required
                  </Text>
                </View>
              </View>
              <Text style={styles.cardSubtle}>
                Sign the liability waiver to RSVP for pickup and tournaments.
              </Text>
              <Pressable
                style={styles.outlineBtnLime}
                onPress={() => router.push("/waiver")}
              >
                <Text style={styles.outlineBtnLimeText}>Sign waiver</Text>
              </Pressable>
            </>
          )}
        </View>

        <ReliabilitySection
          loading={reliabilityLoading}
          label={reliabilityLabel}
          scorePct={reliabilityScorePct}
          subtext={reliabilitySubtext}
        />

        <PreferencesSection
          pushEnabled={pushEnabled}
          pushBusy={pushBusy}
          pushMsg={pushMsg}
          onTogglePush={(v) => void onTogglePushNotifications(v)}
          pushDisabled={!accessToken}
          marketingPushEnabled={marketingPushEnabled}
          marketingPushBusy={marketingPushBusy}
          marketingPushMsg={marketingPushMsg}
          onToggleMarketingPush={(v) => void onToggleMarketingPush(v)}
          marketingPushDisabled={!accessToken}
          maxDriveMinutes={maxDriveMinutes}
          maxDriveBusy={maxDriveBusy}
          maxDriveMsg={maxDriveMsg}
          maxDriveLabel={maxDriveLabel}
          minDrive={MIN_MAX_DRIVE_MINUTES}
          maxDrive={MAX_MAX_DRIVE_MINUTES}
          driveStep={MAX_DRIVE_STEP}
          onMaxDriveChange={setMaxDriveMinutes}
          onMaxDriveCommit={(v) => void onSaveMaxDriveMinutes(v)}
          maxDriveDisabled={!accessToken}
        />

        <ReferralSection accessToken={accessToken} />

        {isAdmin ? (
          <View style={styles.card}>
            <View style={styles.rowBetween}>
              <View style={{ flex: 1, paddingRight: 12 }}>
                <Text style={styles.fieldLabelStrong}>Admin Mode</Text>
                <Text style={styles.bioHint}>Show the Admin tab and pages on this device.</Text>
              </View>
              <Switch
                value={adminModeEnabled}
                onValueChange={(v) => void setAdminModeEnabled(v)}
                disabled={!adminModeReady}
                trackColor={{ false: "rgba(255,255,255,0.18)", true: LIME }}
                thumbColor="#f4f4f5"
              />
            </View>
          </View>
        ) : null}

        <AppLockSection
          hasPin={hasPin}
          lockUi={lockUi}
          setLockUi={setLockUi}
          changeOld={changeOld}
          setChangeOld={setChangeOld}
          changeNewA={changeNewA}
          setChangeNewA={setChangeNewA}
          changeNewB={changeNewB}
          setChangeNewB={setChangeNewB}
          removeCurrent={removeCurrent}
          setRemoveCurrent={setRemoveCurrent}
          lockBusy={lockBusy}
          setLockBusy={setLockBusy}
          lockMsg={lockMsg}
          setLockMsg={setLockMsg}
          biometricsEnabled={biometricsEnabled}
          biometricsAvailable={biometricsAvailable}
          onToggleBiometrics={(v) => void onToggleBiometrics(v)}
          changePin={changePin}
          removePin={removePin}
          lockNow={lockNow}
        />

      {__DEV__ ? (
        <>
          <Pressable
            style={styles.devReplayRow}
            onPress={() => {
              void replayAccountIntro();
            }}
          >
            <Text style={styles.devReplayText}>Replay Account intro (dev only)</Text>
          </Pressable>
          <Pressable
            style={[styles.devReplayRow, styles.devReplayRowGap]}
            onPress={() => void replayOpeningThemeCtx?.replayOpeningTheme()}
          >
            <Text style={styles.devReplayText}>Replay opening theme (dev only)</Text>
          </Pressable>
        </>
      ) : null}
        <Pressable style={styles.aboutRow} onPress={() => (router.push as (href: string) => void)("/rules")}>
          <View style={styles.aboutLeft}>
            <View style={styles.aboutIconWrap}>
              <FontAwesome name="list-alt" size={18} color="rgba(255,255,255,0.75)" />
            </View>
            <Text style={styles.aboutText}>Rules</Text>
          </View>
          <FontAwesome name="chevron-right" size={14} color="rgba(255,255,255,0.35)" />
        </Pressable>
        <Pressable
          style={styles.aboutRow}
          onPress={() => (router.push as (href: string) => void)("/help")}
        >
          <View style={styles.aboutLeft}>
            <View style={styles.aboutIconWrap}>
              <FontAwesome name="question-circle" size={18} color="rgba(255,255,255,0.75)" />
            </View>
            <Text style={styles.aboutText}>Help</Text>
          </View>
          <FontAwesome name="chevron-right" size={14} color="rgba(255,255,255,0.35)" />
        </Pressable>
        <Pressable
          style={styles.aboutRow}
          onPress={() => void Linking.openURL(SUPPORT_MAILTO)}
        >
          <View style={styles.aboutLeft}>
            <View style={styles.aboutIconWrap}>
              <FontAwesome name="envelope" size={18} color="rgba(255,255,255,0.75)" />
            </View>
            <Text style={styles.aboutText}>Contact Support</Text>
          </View>
          <FontAwesome name="chevron-right" size={14} color="rgba(255,255,255,0.35)" />
        </Pressable>
        <Pressable
          style={styles.aboutRow}
          onPress={() => (router.push as (href: string) => void)("/terms")}
        >
          <View style={styles.aboutLeft}>
            <View style={styles.aboutIconWrap}>
              <FontAwesome name="file-o" size={18} color="rgba(255,255,255,0.75)" />
            </View>
            <Text style={styles.aboutText}>Terms of Service</Text>
          </View>
          <FontAwesome name="chevron-right" size={14} color="rgba(255,255,255,0.35)" />
        </Pressable>
        <Pressable
          style={styles.aboutRow}
          onPress={() => (router.push as (href: string) => void)("/privacy-policy")}
        >
          <View style={styles.aboutLeft}>
            <View style={styles.aboutIconWrap}>
              <FontAwesome name="shield" size={18} color="rgba(255,255,255,0.75)" />
            </View>
            <Text style={styles.aboutText}>Privacy Policy</Text>
          </View>
          <FontAwesome name="chevron-right" size={14} color="rgba(255,255,255,0.35)" />
        </Pressable>

        <Pressable style={styles.aboutRow} onPress={() => (router.push as (href: string) => void)("/run-history")}>
          <View style={styles.aboutLeft}>
            <View style={styles.aboutIconWrap}>
              <FontAwesome name="history" size={18} color="rgba(255,255,255,0.75)" />
            </View>
            <Text style={styles.aboutText}>Run history</Text>
          </View>
          <FontAwesome name="chevron-right" size={14} color="rgba(255,255,255,0.35)" />
        </Pressable>
        <Pressable
          style={styles.aboutRow}
          onPress={() => {
            const next = aboutTapCount + 1;
            setAboutTapCount(next);
            if (next < REVIEW_MODE_TAP_TARGET) return;
            setAboutTapCount(0);
            openReviewCodeEntry();
          }}
        >
          <View style={styles.aboutLeft}>
            <View style={styles.aboutIconWrap}>
              <FontAwesome name="info-circle" size={18} color="rgba(255,255,255,0.75)" />
            </View>
            <View style={{ flex: 1 }}>
              <Text style={styles.aboutText}>About this app</Text>
              <Text style={styles.aboutVersionSub}>Version {appVersion}</Text>
            </View>
          </View>
          <FontAwesome name="chevron-right" size={14} color="rgba(255,255,255,0.35)" />
        </Pressable>

        {reviewModeEnabled ? (
          <Pressable
            style={[styles.aboutRow, styles.reviewModeOffRow]}
            onPress={() => {
              Alert.alert("Turn off Review Mode?", "Client approval bypass will be disabled.", [
                { text: "Cancel", style: "cancel" },
                { text: "Turn off", onPress: () => void setReviewModeEnabled(false) },
              ]);
            }}
          >
            <Text style={styles.reviewModeOffText}>Turn off App Review Mode</Text>
          </Pressable>
        ) : null}

        <Text style={[styles.sectionTitle, styles.dangerSectionTitle]}>Danger zone</Text>
        <Text style={styles.sectionSub}>
          Permanently remove your account and associated data from CT Pickup.
        </Text>
        <Pressable
          style={[styles.deleteAccountBtn, deleteAccountBusy && styles.disabled]}
          disabled={deleteAccountBusy || !accessToken}
          onPress={() => {
            const origin = siteOrigin();
            if (!origin || !accessToken) {
              Alert.alert("Can’t delete account", "Missing server URL or session. Try again after signing in.");
              return;
            }
            Alert.alert(
              "Delete your account?",
              "This will permanently delete your account and all your data. This cannot be undone.",
              [
                { text: "Cancel", style: "cancel" },
                {
                  text: "Delete",
                  style: "destructive",
                  onPress: () => {
                    void (async () => {
                      setDeleteAccountBusy(true);
                      try {
                        const r = await fetch(`${origin}/api/account/delete`, {
                          method: "DELETE",
                          headers: {
                            Accept: "application/json",
                            Authorization: `Bearer ${accessToken}`,
                          },
                          cache: "no-store",
                        });
                        if (!r.ok) {
                          const j = (await r.json().catch(() => null)) as { error?: string } | null;
                          Alert.alert(
                            "Couldn’t delete account",
                            typeof j?.error === "string" ? j.error : "Something went wrong. Try again later.",
                          );
                          return;
                        }
                        await signOut();
                        router.replace("/login");
                      } catch {
                        Alert.alert("Couldn’t delete account", "Check your connection and try again.");
                      } finally {
                        setDeleteAccountBusy(false);
                      }
                    })();
                  },
                },
              ],
            );
          }}
        >
          {deleteAccountBusy ? (
            <View style={styles.deleteAccountBtnBusy}>
              <ActivityIndicator color="#fff" />
              <Text style={styles.deleteAccountBtnText}>Deleting…</Text>
            </View>
          ) : (
            <Text style={styles.deleteAccountBtnText}>Delete account</Text>
          )}
        </Pressable>
        </ScrollView>
      </KeyboardAvoidingView>
    </View>
  );
}

