import { useAccountIntroReplay } from "@/context/AccountIntroReplayContext";
import { useReplayOpeningTheme } from "@/context/ReplayOpeningThemeContext";
import { useAdminMode } from "@/context/AdminModeContext";
import { useAuth } from "@/context/AuthContext";
import { useProfileAdmin } from "@/context/ProfileAdminContext";
import { useAppLock } from "@/context/AppLockContext";
import { siteOrigin } from "@/lib/env";
import {
  normalizeProfileUsername,
  PROFILE_USERNAME_MAX_LEN,
  USERNAME_TAKEN_USER_MESSAGE,
  usernameMatchesAutoGeneratedFromNames,
} from "@/lib/profileIdentityFields";
import { getNearestVenues, getNearestVenuesFromApi, type VenueDistanceRow } from "@/lib/venueDistance";
import { getInstallationContext, resolveExpoPushTokenForApp, shouldRegisterPushToken } from "@/lib/pushToken";
import { hapticTap } from "@/lib/haptics";
import { fetchPickupStanding, postMobilePushPreference, postMobilePushToken } from "@/lib/siteApi";
import * as LocalAuthentication from "expo-local-authentication";
import * as Notifications from "expo-notifications";
import * as Device from "expo-device";
import Constants from "expo-constants";
import { useReviewMode } from "@/context/ReviewModeContext";
import { REVIEW_MODE_SECRET, REVIEW_MODE_TAP_TARGET } from "@/lib/reviewMode";
import { useFocusEffect, useRouter } from "expo-router";
import { serviceRegionForVenueName } from "@/lib/venueServiceRegion";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import {
  ActivityIndicator,
  Alert,
  Image,
  KeyboardAvoidingView,
  Linking,
  Platform,
  Pressable,
  RefreshControl,
  ScrollView,
  StyleSheet,
  Switch,
  Modal,
  Text,
  TextInput,
  View,
} from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import Svg, { Circle, Defs, Ellipse, Polygon, RadialGradient, Stop } from "react-native-svg";
import FontAwesome from "@expo/vector-icons/FontAwesome";
import { Ionicons } from "@expo/vector-icons";
import { AppLockSection } from "@/components/account/AppLockSection";
import { PreferencesSection } from "@/components/account/PreferencesSection";
import { ProfileSection } from "@/components/account/ProfileSection";
import { ReferralSection } from "@/components/account/ReferralSection";
import { VerificationRequestModal } from "@/components/account/VerificationRequestModal";
import {
  accountStyles as styles,
  LIME,
  POSITION_OPTIONS,
  SPECIFIC_POSITION_OPTIONS,
  EXPERIENCE_LEVEL_OPTIONS,
  type PositionValue,
  type SpecificPositionValue,
  type ExperienceLevelValue,
} from "@/components/account/accountStyles";

const SUPPORT_EMAIL = "pickupct@gmail.com";
const SUPPORT_MAILTO = `mailto:${SUPPORT_EMAIL}`;
const DELETE_CONFIRM_WORD = "delete";

const MIN_MAX_DRIVE_MINUTES = 30;
const MAX_MAX_DRIVE_MINUTES = 90;
const DEFAULT_MAX_DRIVE_MINUTES = 50;
const MAX_DRIVE_STEP = 5;
function clampMaxDriveMinutes(value: number): number {
  const stepped = Math.round(value / MAX_DRIVE_STEP) * MAX_DRIVE_STEP;
  return Math.min(MAX_MAX_DRIVE_MINUTES, Math.max(MIN_MAX_DRIVE_MINUTES, stepped));
}

function maxDriveLabel(minutes: number): string {
  if (minutes >= MAX_MAX_DRIVE_MINUTES) return "Up to 90+ min drive";
  return `Up to ${minutes} min drive`;
}

type ProfileRow = {
  first_name: string | null;
  last_name: string | null;
  approved: boolean | null;
  instagram: string | null;
  phone: string | null;
  zip_code: string | null;
  nearest_venue: string | null;
  playing_position: string | null;
  username: string | null;
  push_notifications_enabled: boolean | null;
  marketing_push_enabled: boolean | null;
  max_drive_minutes: number | null;
  primary_position: string | null;
  secondary_positions: string[] | null;
  experience_level: string | null;
  date_of_birth: string | null;
  club_name: string | null;
  roster_url: string | null;
  verification_level: string | null;
};

const PROFILE_SELECT_WITH_PUSH =
  "first_name,last_name,approved,instagram,phone,zip_code,nearest_venue,playing_position,username,push_notifications_enabled,marketing_push_enabled,max_drive_minutes,primary_position,secondary_positions,experience_level,date_of_birth,club_name,roster_url,verification_level";

const PROFILE_SELECT_WITHOUT_PUSH =
  "first_name,last_name,approved,instagram,phone,zip_code,nearest_venue,playing_position,username,max_drive_minutes,primary_position,secondary_positions,experience_level,date_of_birth,club_name,roster_url,verification_level";

function supabaseLooksLikeMissingColumn(err: { message?: string } | null | undefined, col: string): boolean {
  const msg = err?.message ?? "";
  if (!msg) return false;
  const re = new RegExp(col.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "i");
  return re.test(msg) && (/column/i.test(msg) || /schema cache/i.test(msg) || /Could not find/i.test(msg));
}

function cleanInstagram(s: string): string {
  return s.trim().replace(/^@/, "").replace(/\s+/g, "");
}

function formatProfileSaveError(err: unknown): string {
  if (err && typeof err === "object" && "message" in err) {
    const o = err as { message?: string; details?: string; hint?: string; code?: string };
    const parts = [o.message, o.details, o.hint].filter((s) => typeof s === "string" && s.trim());
    if (parts.length) return parts.join(" — ");
    if (o.code) return `Error code ${o.code}`;
  }
  if (err instanceof Error) return err.message;
  return String(err);
}

/* ----------------------------------------------------------- tier + gems */

const TIER_COLORS: Record<string, string> = {
  diamond: "#9B59B6",
  platinum: "#E8E8E8",
  gold: "#E3B23C",
  silver: "#A8B0B5",
  bronze: "#B87333",
};

function tierColor(tier: string | null | undefined): string {
  return tier ? (TIER_COLORS[tier.toLowerCase()] ?? LIME) : LIME;
}

function tierLabel(tier: string | null | undefined): string {
  if (!tier) return "Unranked";
  return tier.charAt(0).toUpperCase() + tier.slice(1).toLowerCase();
}

// pts/session per tier (negative means the player pays); subtitle = tier percentile band.
const TIER_META: Record<string, { pts: number; topPct: string }> = {
  diamond: { pts: 8, topPct: "Top 5% of all players" },
  platinum: { pts: 0, topPct: "Top 10% of all players" },
  gold: { pts: -6, topPct: "Top 25% of all players" },
  silver: { pts: -9, topPct: "Top 50% of all players" },
  bronze: { pts: -12, topPct: "Entry tier — keep climbing" },
};

function DiamondGem({ size }: { size: number }) {
  return (
    <Svg width={size} height={size} viewBox="0 0 100 100">
      <Polygon points="32,14 68,14 60,36 40,36" fill="#C89BE0" />
      <Polygon points="32,14 18,36 40,36" fill="#A56FC9" />
      <Polygon points="68,14 82,36 60,36" fill="#8E57B8" />
      <Polygon points="18,36 50,36 50,92" fill="#8E57B8" />
      <Polygon points="50,36 82,36 50,92" fill="#6B3E86" />
      <Polygon points="40,36 60,36 50,92" fill="#A56FC9" />
      <Polygon points="38,17 62,17 57,33 43,33" fill="#D9B8EC" opacity={0.55} />
    </Svg>
  );
}

function CircleGem({ color, size, gid }: { color: string; size: number; gid: string }) {
  return (
    <Svg width={size} height={size} viewBox="0 0 100 100">
      <Defs>
        <RadialGradient id={gid} cx="38%" cy="32%" r="80%">
          <Stop offset="0" stopColor="#ffffff" stopOpacity="0.9" />
          <Stop offset="0.4" stopColor={color} stopOpacity="1" />
          <Stop offset="1" stopColor={color} stopOpacity="1" />
        </RadialGradient>
      </Defs>
      <Circle cx="50" cy="50" r="46" fill={`url(#${gid})`} />
      <Ellipse cx="37" cy="33" rx="17" ry="11" fill="#ffffff" opacity={0.28} />
    </Svg>
  );
}

function TierGem({ tier, size, gid }: { tier: string; size: number; gid: string }) {
  const t = (tier ?? "").toLowerCase();
  if (t === "diamond") return <DiamondGem size={size} />;
  return <CircleGem color={TIER_COLORS[t] ?? "#A8B0B5"} size={size} gid={gid} />;
}

function initialsFromName(name: string): string {
  const parts = name.replace(/^@/, "").trim().split(/\s+/).filter(Boolean);
  if (parts.length === 0) return "?";
  if (parts.length === 1) return parts[0].charAt(0).toUpperCase();
  return (parts[0].charAt(0) + parts[parts.length - 1].charAt(0)).toUpperCase();
}

const EXPERIENCE_LABELS: Record<string, string> = {
  recreational: "Recreational",
  club: "Club",
  hs_varsity: "High School Varsity",
  college: "College",
  semi_pro: "Semi-Pro",
  pro: "Pro",
};

// "CB" -> "CB · Center Back" (SelectModal labels are "CB — Center Back").
function positionFull(code: string): string {
  const opt = (SPECIFIC_POSITION_OPTIONS as readonly { value: string; label: string }[]).find(
    (o) => o.value === code,
  );
  return opt ? opt.label.replace(" — ", " · ") : code;
}

function ageFromDob(dob: string | null): number | null {
  if (!dob) return null;
  const birth = new Date(dob);
  if (Number.isNaN(birth.getTime())) return null;
  const now = new Date();
  let age = now.getFullYear() - birth.getFullYear();
  const m = now.getMonth() - birth.getMonth();
  if (m < 0 || (m === 0 && now.getDate() < birth.getDate())) age--;
  return age > 0 && age < 100 ? age : null;
}

const MONTHS_SHORT = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

// Parse an ISO "YYYY-MM-DD" without timezone drift -> "Mar 28, 2004".
function formatDob(dob: string | null): string | null {
  if (!dob) return null;
  const m = /^(\d{4})-(\d{2})-(\d{2})/.exec(dob.trim());
  if (m) {
    const year = Number(m[1]);
    const month = Number(m[2]) - 1;
    const day = Number(m[3]);
    if (month >= 0 && month < 12 && day >= 1 && day <= 31) {
      return `${MONTHS_SHORT[month]} ${day}, ${year}`;
    }
  }
  const d = new Date(dob);
  if (Number.isNaN(d.getTime())) return dob;
  return `${MONTHS_SHORT[d.getMonth()]} ${d.getDate()}, ${d.getFullYear()}`;
}

export default function AccountScreen() {
  const router = useRouter();
  const insets = useSafeAreaInsets();
  const { replay: replayAccountIntro } = useAccountIntroReplay();
  const replayOpeningThemeCtx = useReplayOpeningTheme();
  const { session, supabase, isReady, signOut } = useAuth();
  const { enabled: adminModeEnabled, isReady: adminModeReady, setEnabled: setAdminModeEnabled } = useAdminMode();
  const { enabled: reviewModeEnabled, setEnabled: setReviewModeEnabled } = useReviewMode();
  const { isAdmin, isReady: profileAdminReady } = useProfileAdmin();
  const {
    hasPin,
    lockEnabled,
    requestEnrollment,
    changePin,
    removePin,
    biometricsEnabled,
    biometricsAvailable,
    setBiometricsEnabled,
    refreshBiometricAvailability,
    lockNow,
  } = useAppLock();

  const [lockUi, setLockUi] = useState<"idle" | "change" | "remove">("idle");
  const [changeOld, setChangeOld] = useState("");
  const [changeNewA, setChangeNewA] = useState("");
  const [changeNewB, setChangeNewB] = useState("");
  const [removeCurrent, setRemoveCurrent] = useState("");
  const [lockBusy, setLockBusy] = useState(false);
  const [lockMsg, setLockMsg] = useState<string | null>(null);

  const [profile, setProfile] = useState<ProfileRow | null>(null);

  const [editFirstName, setEditFirstName] = useState("");
  const [editLastName, setEditLastName] = useState("");
  const [editPlayingPosition, setEditPlayingPosition] = useState<PositionValue | null>(null);
  const [editPrimaryPosition, setEditPrimaryPosition] = useState<SpecificPositionValue | null>(null);
  const [editSecondaryPositions, setEditSecondaryPositions] = useState<SpecificPositionValue[]>([]);
  const [editExperienceLevel, setEditExperienceLevel] = useState<ExperienceLevelValue | null>(null);
  const [editDateOfBirth, setEditDateOfBirth] = useState("");
  const [editClubName, setEditClubName] = useState("");
  const [editRosterUrl, setEditRosterUrl] = useState("");
  const [editInstagram, setEditInstagram] = useState("");
  const [editPhone, setEditPhone] = useState("");
  const [editZipCode, setEditZipCode] = useState("");
  const [editUsername, setEditUsername] = useState("");
  const [editBusy, setEditBusy] = useState(false);
  const [editMsg, setEditMsg] = useState<string | null>(null);
  const [profileSaveError, setProfileSaveError] = useState<string | null>(null);
  const [editOk, setEditOk] = useState(false);
  const [positionPickerOpen, setPositionPickerOpen] = useState(false);
  const [primaryPositionPickerOpen, setPrimaryPositionPickerOpen] = useState(false);
  const [experienceLevelPickerOpen, setExperienceLevelPickerOpen] = useState(false);
  const [verificationModalOpen, setVerificationModalOpen] = useState(false);

  const [waiverAccepted, setWaiverAccepted] = useState<boolean | null>(null);
  const [waiverVersion, setWaiverVersion] = useState<string | null>(null);
  const [waiverLoading, setWaiverLoading] = useState(true);

  const [reliabilityLoading, setReliabilityLoading] = useState(true);
  const [reliabilityLabel, setReliabilityLabel] = useState<string | null>(null);
  const [reliabilityScorePct, setReliabilityScorePct] = useState<number | null>(null);
  const [reliabilitySubtext, setReliabilitySubtext] = useState<string | null>(null);


  const [deleteAccountBusy, setDeleteAccountBusy] = useState(false);
  const [deleteConfirmModalOpen, setDeleteConfirmModalOpen] = useState(false);
  const [deleteConfirmInput, setDeleteConfirmInput] = useState("");

  const [pushEnabled, setPushEnabled] = useState(true);
  const [pushBusy, setPushBusy] = useState(false);
  const [pushMsg, setPushMsg] = useState<string | null>(null);
  const [marketingPushEnabled, setMarketingPushEnabled] = useState(false);
  const [marketingPushBusy, setMarketingPushBusy] = useState(false);
  const [marketingPushMsg, setMarketingPushMsg] = useState<string | null>(null);
  const [maxDriveMinutes, setMaxDriveMinutes] = useState(DEFAULT_MAX_DRIVE_MINUTES);
  const [maxDriveBusy, setMaxDriveBusy] = useState(false);
  const [maxDriveMsg, setMaxDriveMsg] = useState<string | null>(null);
  const [refreshing, setRefreshing] = useState(false);
  const [hubRegionResolving, setHubRegionResolving] = useState(false);
  const [hubVenueResolveDone, setHubVenueResolveDone] = useState(false);
  const hubResolveKeyRef = useRef<string | null>(null);
  const scrollRef = useRef<ScrollView>(null);
  const verificationSectionY = useRef<number>(0);
  const [aboutTapCount, setAboutTapCount] = useState(0);
  const [reviewCodeModalOpen, setReviewCodeModalOpen] = useState(false);
  const [reviewCodeInput, setReviewCodeInput] = useState("");

  // Profile-view extras (tier, avatar, stats, credits). Additive — existing data flow untouched.
  const [editModalOpen, setEditModalOpen] = useState(false);
  const [avatarUrl, setAvatarUrl] = useState<string | null>(null);
  const [tierInfo, setTierInfo] = useState<{
    tier: string;
    score: number;
    sessions: number;
    percentile: number | null;
  } | null>(null);
  const [winsCount, setWinsCount] = useState<number | null>(null);
  const [lossesCount, setLossesCount] = useState<number | null>(null);
  const [potdCount, setPotdCount] = useState<number | null>(null);
  const [points, setPoints] = useState<number | null>(null);
  const [creditsCount, setCreditsCount] = useState<number | null>(null);
  const settingsSectionY = useRef<number>(0);
  const openEdit = useCallback(() => setEditModalOpen(true), []);

  const appVersion =
    Constants.expoConfig?.version ?? Constants.nativeAppVersion ?? "1.0.0";

  function submitReviewCode() {
    if (reviewCodeInput.trim() === REVIEW_MODE_SECRET) {
      void setReviewModeEnabled(true);
      setReviewCodeModalOpen(false);
      setReviewCodeInput("");
      Alert.alert("Review Mode", "App Review Mode is now active.");
    } else {
      Alert.alert("Review Mode", "Incorrect code.");
    }
  }

  function openReviewCodeEntry() {
    setReviewCodeInput("");
    if (Platform.OS === "ios" && typeof Alert.prompt === "function") {
      Alert.prompt(
        "Review Mode",
        "Enter the review secret code.",
        [
          { text: "Cancel", style: "cancel" },
          {
            text: "Activate",
            onPress: (value) => {
              if (String(value ?? "").trim() === REVIEW_MODE_SECRET) {
                void setReviewModeEnabled(true);
                Alert.alert("Review Mode", "App Review Mode is now active.");
              } else {
                Alert.alert("Review Mode", "Incorrect code.");
              }
            },
          },
        ],
        "secure-text",
      );
      return;
    }
    setReviewCodeModalOpen(true);
  }

  useEffect(() => {
    void refreshBiometricAvailability();
  }, [refreshBiometricAvailability]);

  const accessToken = session?.access_token ?? null;

  const closeDeleteConfirmModal = useCallback(() => {
    setDeleteConfirmModalOpen(false);
    setDeleteConfirmInput("");
  }, []);

  const performDeleteAccount = useCallback(async () => {
    if (deleteConfirmInput !== DELETE_CONFIRM_WORD) return;
    const origin = siteOrigin();
    if (!origin || !accessToken) {
      Alert.alert("Can’t delete account", "Missing server URL or session. Try again after signing in.");
      return;
    }
    setDeleteAccountBusy(true);
    try {
      const r = await fetch(`${origin}/api/account/delete`, {
        method: "DELETE",
        headers: {
          Accept: "application/json",
          Authorization: `Bearer ${accessToken}`,
        },
        cache: "no-store",
      });
      if (!r.ok) {
        const j = (await r.json().catch(() => null)) as { error?: string } | null;
        Alert.alert(
          "Couldn’t delete account",
          typeof j?.error === "string" ? j.error : "Something went wrong. Try again later.",
        );
        return;
      }
      closeDeleteConfirmModal();
      await signOut();
      router.replace("/login");
    } catch {
      Alert.alert("Couldn’t delete account", "Check your connection and try again.");
    } finally {
      setDeleteAccountBusy(false);
    }
  }, [accessToken, closeDeleteConfirmModal, deleteConfirmInput, router, signOut]);

  const startDeleteAccountFlow = useCallback(() => {
    const origin = siteOrigin();
    if (!origin || !accessToken) {
      Alert.alert("Can’t delete account", "Missing server URL or session. Try again after signing in.");
      return;
    }
    Alert.alert(
      "Are you sure you want to delete your account?",
      "You will lose everything — your stats, RSVPs, credits, and profile. This cannot be undone.",
      [
        { text: "Cancel", style: "cancel" },
        {
          text: "Continue",
          onPress: () => {
            setDeleteConfirmInput("");
            setDeleteConfirmModalOpen(true);
          },
        },
      ],
    );
  }, [accessToken]);

  const deleteConfirmMatches = deleteConfirmInput === DELETE_CONFIRM_WORD;

  const usernameAutoFromName = useMemo(
    () => usernameMatchesAutoGeneratedFromNames(editUsername, editFirstName, editLastName),
    [editUsername, editFirstName, editLastName],
  );

  const profileRegionCode = useMemo(
    () => serviceRegionForVenueName(profile?.nearest_venue),
    [profile?.nearest_venue],
  );

  const loadProfile = useCallback(async () => {
    const uid = session?.user?.id;
    if (!isReady || !supabase || !uid) {
      return;
    }
    try {
      let res = await supabase.from("profiles").select(PROFILE_SELECT_WITH_PUSH).eq("id", uid).maybeSingle();
      if (res.error) {
        console.error("[account loadProfile] Supabase error", JSON.stringify(res.error));
        if (
          supabaseLooksLikeMissingColumn(res.error, "push_notifications_enabled") ||
          supabaseLooksLikeMissingColumn(res.error, "marketing_push_enabled") ||
          supabaseLooksLikeMissingColumn(res.error, "max_drive_minutes")
        ) {
          res = await supabase.from("profiles").select(PROFILE_SELECT_WITHOUT_PUSH).eq("id", uid).maybeSingle();
          if (res.error) {
            console.error("[account loadProfile] fallback select error", JSON.stringify(res.error));
            setProfile(null);
            return;
          }
          const row = res.data as Omit<ProfileRow, "push_notifications_enabled"> | null;
          setProfile(
            row
              ? {
                  ...row,
                  push_notifications_enabled: true,
                  marketing_push_enabled: false,
                  max_drive_minutes:
                    row.max_drive_minutes == null
                      ? DEFAULT_MAX_DRIVE_MINUTES
                      : clampMaxDriveMinutes(Number(row.max_drive_minutes)),
                }
              : null,
          );
          return;
        }
        setProfile(null);
        return;
      }
      const row = res.data as ProfileRow | null;
      setProfile(
        row
          ? {
              ...row,
              max_drive_minutes:
                row.max_drive_minutes == null
                  ? DEFAULT_MAX_DRIVE_MINUTES
                  : clampMaxDriveMinutes(Number(row.max_drive_minutes)),
            }
          : null,
      );
    } catch (e) {
      console.error("[account loadProfile] exception", e);
      setProfile(null);
    }
  }, [isReady, supabase, session?.user?.id]);

  useFocusEffect(
    useCallback(() => {
      void loadProfile();
    }, [loadProfile]),
  );

  // Re-fetch when auth/session becomes available after focus (useFocusEffect does not re-run when loadProfile's deps update).
  useEffect(() => {
    void loadProfile();
  }, [loadProfile]);

  // Profile-view stats: tier + sessions (player_ratings), avatar + wins/losses/MOTM (profiles counters).
  const loadStats = useCallback(async () => {
    const uid = session?.user?.id;
    if (!isReady || !supabase || !uid) return;
    try {
      // Tier (player_ratings), profile counters (profiles), and rating deltas
      // (rating_events) are independent — fetch them together.
      const [ratingRes, extrasRes, eventsRes] = await Promise.all([
        supabase.from("player_ratings").select("tier,score,sessions").eq("user_id", uid).maybeSingle(),
        supabase.from("profiles").select("avatar_url,wins_count,losses_count,potd_count").eq("id", uid).maybeSingle(),
        supabase.from("rating_events").select("delta").eq("user_id", uid),
      ]);

      const mine = ratingRes.data as
        | { tier: string | null; score: number | null; sessions: number | null }
        | null;
      if (mine) {
        const myScore = mine.score ?? 0;
        const [{ count: total }, { count: better }] = await Promise.all([
          supabase.from("player_ratings").select("*", { count: "exact", head: true }).gt("sessions", 0),
          supabase.from("player_ratings").select("*", { count: "exact", head: true }).gt("score", myScore),
        ]);
        const percentile =
          total && total > 0 ? Math.min(100, Math.max(1, Math.round(((better ?? 0) / total) * 100))) : null;
        setTierInfo({
          tier: (mine.tier ?? "bronze").toLowerCase(),
          score: myScore,
          sessions: mine.sessions ?? 0,
          percentile,
        });
      } else {
        setTierInfo(null);
      }

      let potd = 0;
      if (extrasRes.error) {
        // Older DBs may not have the session-counter columns yet; still show the avatar.
        const { data: av } = await supabase.from("profiles").select("avatar_url").eq("id", uid).maybeSingle();
        setAvatarUrl((av as { avatar_url: string | null } | null)?.avatar_url?.trim() || null);
      } else if (extrasRes.data) {
        const row = extrasRes.data as {
          avatar_url: string | null;
          wins_count: unknown;
          losses_count: unknown;
          potd_count: unknown;
        };
        setAvatarUrl(row.avatar_url?.trim() || null);
        setWinsCount(Math.max(0, Math.trunc(Number(row.wins_count ?? 0))));
        setLossesCount(Math.max(0, Math.trunc(Number(row.losses_count ?? 0))));
        potd = Math.max(0, Math.trunc(Number(row.potd_count ?? 0)));
        setPotdCount(potd);
      }

      // Points = sum(positive rating deltas) × 30 + MOTM × 100.
      const deltaRows = (eventsRes.data ?? []) as Array<{ delta: number | string | null }>;
      const positiveDelta = deltaRows.reduce((acc, r) => {
        const d = Number(r.delta ?? 0);
        return acc + (Number.isFinite(d) && d > 0 ? d : 0);
      }, 0);
      setPoints(Math.round(positiveDelta * 30) + potd * 100);
    } catch (e) {
      console.error("[account loadStats] exception", e);
    }
  }, [isReady, supabase, session?.user?.id]);

  const loadCredits = useCallback(async () => {
    const origin = siteOrigin();
    if (!origin || !accessToken) {
      setCreditsCount(0);
      return;
    }
    try {
      const r = await fetch(`${origin}/api/pickup/credits`, {
        headers: { Authorization: `Bearer ${accessToken}`, Accept: "application/json" },
        cache: "no-store",
      });
      const j = (await r.json().catch(() => null)) as
        | { credits?: Array<{ is_used?: boolean; is_expired?: boolean }> }
        | null;
      if (r.ok && j && Array.isArray(j.credits)) {
        setCreditsCount(j.credits.filter((c) => !c.is_used && !c.is_expired).length);
      } else {
        setCreditsCount(0);
      }
    } catch {
      setCreditsCount(0);
    }
  }, [accessToken]);

  useEffect(() => {
    void loadStats();
    void loadCredits();
  }, [loadStats, loadCredits]);

  useEffect(() => {
    setHubVenueResolveDone(false);
    hubResolveKeyRef.current = null;
  }, [profile?.zip_code]);

  useEffect(() => {
    if (!profile || !isReady || !supabase) return;
    const uid = session?.user?.id;
    if (!uid) return;

    const zip = String(profile.zip_code ?? "")
      .replace(/\D/g, "")
      .slice(0, 5);
    if (zip.length !== 5) return;
    if (String(profile.nearest_venue ?? "").trim()) {
      setHubVenueResolveDone(true);
      return;
    }

    if (hubResolveKeyRef.current === zip) return;
    hubResolveKeyRef.current = zip;

    let cancelled = false;
    void (async () => {
      setHubRegionResolving(true);
      try {
        const maxMin =
          profile.max_drive_minutes == null
            ? DEFAULT_MAX_DRIVE_MINUTES
            : clampMaxDriveMinutes(Number(profile.max_drive_minutes));
        let nearestVenues: VenueDistanceRow[] = [];
        const origin = siteOrigin();
        if (origin) {
          try {
            nearestVenues = await getNearestVenuesFromApi(zip, origin, accessToken);
          } catch (e) {
            console.error("[account] hub resolve getNearestVenuesFromApi", e);
          }
        }
        if (nearestVenues.length === 0) {
          nearestVenues = getNearestVenues(zip);
        }
        const within = nearestVenues.filter((r) => r.estimatedMinutes <= maxMin);
        const nearestVenue = within[0]?.venue ?? null;
        if (cancelled) return;
        if (!nearestVenue) {
          setHubVenueResolveDone(true);
          return;
        }

        const updatedAt = new Date().toISOString();
        let saved = false;
        if (origin && accessToken) {
          try {
            const r = await fetch(`${origin}/api/account/profile`, {
              method: "PATCH",
              headers: {
                Accept: "application/json",
                "Content-Type": "application/json",
                Authorization: `Bearer ${accessToken}`,
              },
              body: JSON.stringify({ nearest_venue: nearestVenue, updated_at: updatedAt }),
              cache: "no-store",
            });
            if (r.ok) saved = true;
          } catch (e) {
            console.error("[account] hub resolve PATCH profile", e);
          }
        }
        if (!saved) {
          try {
            const { error } = await supabase
              .from("profiles")
              .update({ nearest_venue: nearestVenue, updated_at: updatedAt })
              .eq("id", uid);
            if (error) {
              console.error("[account] hub resolve supabase update", JSON.stringify(error));
              setHubVenueResolveDone(true);
              return;
            }
          } catch (e) {
            console.error("[account] hub resolve supabase exception", e);
            setHubVenueResolveDone(true);
            return;
          }
        }
        setProfile((p) => (p ? { ...p, nearest_venue: nearestVenue } : p));
        setHubVenueResolveDone(true);
      } catch (e) {
        console.error("[account] hub resolve exception", e);
        setHubVenueResolveDone(true);
      } finally {
        if (!cancelled) setHubRegionResolving(false);
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [profile, isReady, supabase, session?.user?.id, accessToken]);

  useEffect(() => {
    if (!profile || editBusy) return;
    setEditFirstName(String(profile.first_name ?? ""));
    setEditLastName(String(profile.last_name ?? ""));
    const rawPos = String(profile.playing_position ?? "").trim();
    setEditPlayingPosition(
      (POSITION_OPTIONS as readonly { value: string }[]).some((o) => o.value === rawPos) ? (rawPos as PositionValue) : null,
    );
    setEditInstagram(profile.instagram ? String(profile.instagram).replace(/^@/, "") : "");
    setEditPhone(String(profile.phone ?? ""));
    setEditZipCode(String(profile.zip_code ?? "").replace(/\D/g, "").slice(0, 5));
    setEditUsername(String(profile.username ?? ""));
    setPushEnabled(profile.push_notifications_enabled !== false);
    setMarketingPushEnabled(profile.marketing_push_enabled === true);
    const storedMax =
      profile.max_drive_minutes == null ? DEFAULT_MAX_DRIVE_MINUTES : Number(profile.max_drive_minutes);
    setMaxDriveMinutes(clampMaxDriveMinutes(storedMax));
    const rawPrimary = String(profile.primary_position ?? "").trim();
    setEditPrimaryPosition(
      (SPECIFIC_POSITION_OPTIONS as readonly { value: string }[]).some((o) => o.value === rawPrimary) ? (rawPrimary as SpecificPositionValue) : null,
    );
    const rawSecondary = Array.isArray(profile.secondary_positions) ? profile.secondary_positions : [];
    setEditSecondaryPositions(rawSecondary.filter((p): p is SpecificPositionValue =>
      (SPECIFIC_POSITION_OPTIONS as readonly { value: string }[]).some((o) => o.value === p)
    ));
    const rawExp = String(profile.experience_level ?? "").trim();
    setEditExperienceLevel(
      (EXPERIENCE_LEVEL_OPTIONS as readonly { value: string }[]).some((o) => o.value === rawExp) ? (rawExp as ExperienceLevelValue) : null,
    );
    setEditDateOfBirth(String(profile.date_of_birth ?? ""));
    setEditClubName(String(profile.club_name ?? ""));
    setEditRosterUrl(String(profile.roster_url ?? ""));
  }, [profile, editBusy]);

  const loadWaiverStatus = useCallback(async (opts?: { silent?: boolean }) => {
    if (!isReady) return;
    const origin = siteOrigin();
    if (!origin || !accessToken) {
      if (!opts?.silent) {
        setWaiverLoading(false);
        setWaiverAccepted(null);
        setWaiverVersion(null);
      }
      return;
    }
    if (!opts?.silent) setWaiverLoading(true);
    try {
      const r = await fetch(`${origin}/api/waiver/status`, {
        method: "GET",
        headers: {
          Accept: "application/json",
          Authorization: `Bearer ${accessToken}`,
        },
        cache: "no-store",
      });
      const j = (await r.json().catch(() => null)) as
        | { accepted?: boolean; currentVersion?: string }
        | null;
      if (!r.ok || !j) {
        setWaiverAccepted(null);
        setWaiverVersion(null);
      } else {
        setWaiverAccepted(Boolean(j.accepted));
        setWaiverVersion(typeof j.currentVersion === "string" ? j.currentVersion : null);
      }
    } catch (e) {
      console.warn("[account] loadWaiverStatus error:", e);
      setWaiverAccepted(null);
      setWaiverVersion(null);
    } finally {
      if (!opts?.silent) setWaiverLoading(false);
    }
  }, [isReady, accessToken]);

  const loadReliability = useCallback(async (opts?: { silent?: boolean }) => {
    if (!isReady) return;
    if (!accessToken) {
      if (!opts?.silent) {
        setReliabilityLoading(false);
        setReliabilityLabel(null);
        setReliabilityScorePct(null);
        setReliabilitySubtext(null);
      }
      return;
    }
    if (!opts?.silent) setReliabilityLoading(true);
    try {
      const r = await fetchPickupStanding(accessToken);
      if (r.ok && r.data?.ok && r.data.reliability) {
        const rel = r.data.reliability;
        setReliabilityLabel(rel.user_label ?? null);
        setReliabilityScorePct(rel.score_pct == null ? null : Math.round(Number(rel.score_pct)));
        setReliabilitySubtext(rel.user_subtext ?? null);
      } else {
        setReliabilityLabel(null);
        setReliabilityScorePct(null);
        setReliabilitySubtext(null);
      }
    } catch (e) {
      console.error("[account loadReliability] exception", e);
      setReliabilityLabel(null);
      setReliabilityScorePct(null);
      setReliabilitySubtext(null);
    } finally {
      if (!opts?.silent) setReliabilityLoading(false);
    }
  }, [isReady, accessToken]);

  useEffect(() => {
    void loadWaiverStatus();
    void loadReliability();
  }, [isReady, accessToken, loadWaiverStatus, loadReliability]);

  const onRefresh = useCallback(async () => {
    setRefreshing(true);
    try {
      await Promise.all([
        loadProfile(),
        loadWaiverStatus({ silent: true }),
        loadReliability({ silent: true }),
        loadStats(),
        loadCredits(),
      ]);
    } finally {
      setRefreshing(false);
    }
  }, [loadProfile, loadWaiverStatus, loadReliability, loadStats, loadCredits]);

  async function onSaveProfile() {
    setEditMsg(null);
    setProfileSaveError(null);
    setEditOk(false);

    if (!supabase) {
      setProfileSaveError("Save failed: Supabase client is not available. Check app configuration.");
      return;
    }

    const userId = session?.user?.id;
    if (!userId) {
      setProfileSaveError("Save failed: Not signed in.");
      return;
    }

    const firstName = editFirstName.trim();
    const lastName = editLastName.trim();
    const playingPosition = editPlayingPosition;
    const instagram = cleanInstagram(editInstagram);
    const phone = editPhone.trim();
    const zipDigits = editZipCode.replace(/\D/g, "").slice(0, 5);
    const usernameRaw = editUsername.trim();
    const storedUsername = (profile?.username ?? "").trim();
    let usernameResolved: string | null = null;
    if (usernameRaw) {
      const matchesStored =
        storedUsername.length > 0 && usernameRaw.toLowerCase() === storedUsername.toLowerCase();
      const norm = normalizeProfileUsername(usernameRaw);
      if (!matchesStored && !norm) {
        setProfileSaveError(
          "Save failed: Username must be 3–30 characters, lowercase letters and numbers only.",
        );
        return;
      }
      usernameResolved = matchesStored ? storedUsername : norm!;
    }

    const zipStored = zipDigits.length === 5 ? zipDigits : null;

    setEditBusy(true);
    try {
      let nearestVenues: VenueDistanceRow[] = [];
      if (zipStored) {
        const originForVenues = siteOrigin();
        if (originForVenues) {
          try {
            nearestVenues = await getNearestVenuesFromApi(zipStored, originForVenues, accessToken);
          } catch (e) {
            console.error("[onSaveProfile] getNearestVenuesFromApi exception", e);
          }
        }
        if (nearestVenues.length === 0) {
          nearestVenues = getNearestVenues(zipStored);
        }
      }
      const maxMin =
        profile?.max_drive_minutes == null
          ? DEFAULT_MAX_DRIVE_MINUTES
          : clampMaxDriveMinutes(Number(profile.max_drive_minutes));
      const nearestVenue =
        nearestVenues.filter((r) => r.estimatedMinutes <= maxMin)[0]?.venue ?? null;

      const updatedAt = new Date().toISOString();
      const coreUpdate = {
        first_name: firstName || null,
        last_name: lastName || null,
        playing_position: playingPosition ?? null,
        instagram: instagram || null,
        phone: phone || null,
        zip_code: zipStored,
        username: usernameResolved,
        updated_at: updatedAt,
        primary_position: editPrimaryPosition ?? null,
        secondary_positions: editSecondaryPositions.length > 0 ? editSecondaryPositions : null,
        experience_level: editExperienceLevel ?? null,
        date_of_birth: editDateOfBirth.trim() || null,
        club_name: editClubName.trim() || null,
        roster_url: editRosterUrl.trim() || null,
      };

      const origin = siteOrigin();
      if (origin && accessToken) {
        try {
          const r = await fetch(`${origin}/api/account/profile`, {
            method: "PATCH",
            headers: {
              Accept: "application/json",
              "Content-Type": "application/json",
              Authorization: `Bearer ${accessToken}`,
            },
            body: JSON.stringify({ ...coreUpdate, nearest_venue: nearestVenue }),
            cache: "no-store",
          });
          const j = (await r.json().catch(() => null)) as { ok?: boolean; error?: string } | null;
          if (!r.ok) {
            const errLine =
              typeof j?.error === "string" && j.error.trim()
                ? j.error.trim()
                : `HTTP ${r.status} ${r.statusText || ""}`.trim();
            setProfileSaveError(`Save failed: ${errLine}`);
            return;
          }
          if (j && j.ok === false && typeof j.error === "string" && j.error.trim()) {
            setProfileSaveError(`Save failed: ${j.error.trim()}`);
            return;
          }
        } catch (e) {
          console.error("[onSaveProfile] /api/account/profile fetch exception", e);
          setProfileSaveError(`Save failed: ${formatProfileSaveError(e)}`);
          return;
        }
      } else {
        let data: { id: string }[] | null = null;
        let error: { message?: string; code?: string } | null = null;

        try {
          const withVenue = await supabase
            .from("profiles")
            .update({ ...coreUpdate, nearest_venue: nearestVenue })
            .eq("id", userId)
            .select("id");
          data = withVenue.data;
          error = withVenue.error;
          if (error && supabaseLooksLikeMissingColumn(error, "nearest_venue")) {
            console.error("[onSaveProfile] retrying without nearest_venue", JSON.stringify(error));
            const noVenue = await supabase.from("profiles").update(coreUpdate).eq("id", userId).select("id");
            data = noVenue.data;
            error = noVenue.error;
          }
        } catch (e) {
          console.error("[onSaveProfile] profiles.update exception", e);
          setProfileSaveError(`Save failed: ${formatProfileSaveError(e)}`);
          return;
        }

        if (error) {
          console.error("[onSaveProfile] supabase.from('profiles').update error", JSON.stringify(error));
          const code = (error as { code?: string }).code;
          const dup =
            code === "23505" ||
            /profiles_username_lower_unique|duplicate key/i.test(error.message ?? "");
          setProfileSaveError(
            `Save failed: ${
              dup ? USERNAME_TAKEN_USER_MESSAGE : formatProfileSaveError(error)
            }`,
          );
          return;
        }

        if (!data?.length) {
          console.error("[onSaveProfile] update returned 0 rows", { userId });
          setProfileSaveError(
            "Save failed: Save did not update any profile row (no match or not permitted). Your account may be missing a profile row.",
          );
          return;
        }
      }

      const nextFields = {
        first_name: firstName || null,
        last_name: lastName || null,
        playing_position: playingPosition ?? null,
        instagram: instagram || null,
        phone: phone || null,
        zip_code: zipDigits.length === 5 ? zipDigits : null,
        username: usernameResolved,
        nearest_venue: nearestVenue,
      };
      setProfile((p) => {
        if (p) {
          return { ...p, ...nextFields };
        }
        return {
          ...nextFields,
          approved: null,
          push_notifications_enabled: pushEnabled,
        };
      });
      setEditFirstName(firstName);
      setEditLastName(lastName);
      setEditPlayingPosition(playingPosition);
      setEditInstagram(instagram || "");
      setEditPhone(phone);
      setEditZipCode(zipDigits.length === 5 ? zipDigits : "");
      setEditUsername(usernameResolved ?? "");
      setEditOk(true);
      setEditMsg("Saved.");
    } catch (e) {
      console.error("[onSaveProfile] exception", e);
      setProfileSaveError(`Save failed: ${formatProfileSaveError(e)}`);
    } finally {
      setEditBusy(false);
    }
  }

  async function onSaveMaxDriveMinutes(nextRaw: number) {
    const next = clampMaxDriveMinutes(nextRaw);
    if (maxDriveBusy) return;
    setMaxDriveMsg(null);
    if (!supabase) {
      setMaxDriveMsg("Supabase client is not available. Check app configuration.");
      return;
    }
    const uid = session?.user?.id;
    if (!uid) {
      setMaxDriveMsg("Sign in again to change this.");
      return;
    }

    const prev = maxDriveMinutes;
    setMaxDriveMinutes(next);
    setMaxDriveBusy(true);
    try {
      const res = await supabase
        .from("profiles")
        .update({
          max_drive_minutes: next,
          updated_at: new Date().toISOString(),
        })
        .eq("id", uid)
        .select("id");
      const { error } = res;
      if (error) {
        setMaxDriveMinutes(prev);
        setMaxDriveMsg(formatProfileSaveError(error));
        return;
      }
      if (!res.data?.length) {
        setMaxDriveMinutes(prev);
        setMaxDriveMsg("Save did not update any profile row.");
        return;
      }
      setProfile((p) => (p ? { ...p, max_drive_minutes: next } : p));
    } catch (e) {
      setMaxDriveMinutes(prev);
      setMaxDriveMsg(formatProfileSaveError(e));
    } finally {
      setMaxDriveBusy(false);
    }
  }

  async function onTogglePushNotifications(next: boolean) {
    if (pushBusy) return;
    setPushMsg(null);
    if (!supabase) {
      setPushMsg("Supabase client is not available. Check app configuration.");
      return;
    }
    if (!accessToken) {
      setPushMsg("Sign in again to change this.");
      return;
    }
    const uid = session?.user?.id;
    if (!uid) {
      setPushMsg("Sign in again to change this.");
      return;
    }

    const prev = pushEnabled;
    setPushEnabled(next);
    setPushBusy(true);
    try {
      let data: { id: string }[] | null = null;
      try {
        const res = await supabase
          .from("profiles")
          .update({
            push_notifications_enabled: next,
            updated_at: new Date().toISOString(),
          })
          .eq("id", uid)
          .select("id");
        data = res.data;
        const { error } = res;
        if (error) {
          console.log("[push-pref] profiles.update Supabase error:", error);
          console.log("[push-pref] profiles.update Supabase error JSON:", JSON.stringify(error));
          setPushEnabled(prev);
          setPushMsg(formatProfileSaveError(error));
          return;
        }
        if (!data?.length) {
          console.log("[push-pref] profiles.update returned 0 rows", { userId: uid });
          setPushEnabled(prev);
          setPushMsg(
            "Save did not update any profile row (no match or not permitted). Your account may be missing a profile row.",
          );
          return;
        }
      } catch (e) {
        console.log("[push-pref] profiles.update exception:", e);
        setPushEnabled(prev);
        setPushMsg(formatProfileSaveError(e));
        return;
      }

      setProfile((p) =>
        p ? { ...p, push_notifications_enabled: next, marketing_push_enabled: next ? p.marketing_push_enabled : false } : p,
      );

      if (!next) {
        setMarketingPushEnabled(false);
        try {
          await supabase
            .from("profiles")
            .update({ marketing_push_enabled: false, updated_at: new Date().toISOString() })
            .eq("id", uid);
        } catch (e) {
          console.log("[push-pref] marketing_push_enabled off exception:", e);
        }
        try {
          const { error: delErr } = await supabase.from("user_push_devices").delete().eq("user_id", uid);
          if (delErr) {
            console.log("[push-pref] user_push_devices.delete Supabase error:", delErr);
            console.log("[push-pref] user_push_devices.delete Supabase error JSON:", JSON.stringify(delErr));
          }
        } catch (e) {
          console.log("[push-pref] user_push_devices.delete exception:", e);
        }
        try {
          const res = await postMobilePushPreference(accessToken, false);
          if (!res.ok) {
            console.log("[push-pref] postMobilePushPreference(false) failed:", res.error);
          }
        } catch (e) {
          console.log("[push-pref] postMobilePushPreference(false) exception:", e);
        }
      } else if (Device.isDevice) {
        try {
          if (!shouldRegisterPushToken()) return;

          const { status: existing } = await Notifications.getPermissionsAsync();
          let finalStatus = existing;
          if (existing !== "granted") {
            const req = await Notifications.requestPermissionsAsync();
            finalStatus = req.status;
          }
          if (finalStatus === "granted") {
            const installationContext = getInstallationContext();
            if (installationContext === "storeClient") return;

            const expoPushToken = await resolveExpoPushTokenForApp();
            const platform = Platform.OS === "ios" ? "ios" : Platform.OS === "android" ? "android" : null;
            if (expoPushToken && platform) {
              const reg = await postMobilePushToken(accessToken, expoPushToken, platform, installationContext);
              if (!reg.ok) {
                console.log("[push-pref] postMobilePushToken failed:", reg.error);
              }
            }
          }
        } catch (e) {
          console.log("[push-pref] token re-register exception:", e);
        }
      }
    } finally {
      setPushBusy(false);
    }
  }

  async function onToggleMarketingPush(next: boolean) {
    if (marketingPushBusy) return;
    setMarketingPushMsg(null);
    if (!pushEnabled && next) {
      setMarketingPushMsg("Turn on push notifications first.");
      return;
    }
    if (!supabase) {
      setMarketingPushMsg("Supabase client is not available. Check app configuration.");
      return;
    }
    if (!accessToken) {
      setMarketingPushMsg("Sign in again to change this.");
      return;
    }
    const uid = session?.user?.id;
    if (!uid) {
      setMarketingPushMsg("Sign in again to change this.");
      return;
    }

    const prev = marketingPushEnabled;
    setMarketingPushEnabled(next);
    setMarketingPushBusy(true);
    try {
      const res = await supabase
        .from("profiles")
        .update({
          marketing_push_enabled: next,
          updated_at: new Date().toISOString(),
        })
        .eq("id", uid)
        .select("id");
      const { error } = res;
      if (error) {
        setMarketingPushEnabled(prev);
        if (supabaseLooksLikeMissingColumn(error, "marketing_push_enabled")) {
          setMarketingPushMsg("Marketing push preference is not available yet. Apply the latest database migration.");
        } else {
          setMarketingPushMsg(formatProfileSaveError(error));
        }
        return;
      }
      if (!res.data?.length) {
        setMarketingPushEnabled(prev);
        setMarketingPushMsg("Save did not update any profile row.");
        return;
      }

      try {
        await supabase
          .from("user_push_devices")
          .update({ marketing_push_enabled: next, updated_at: new Date().toISOString() })
          .eq("user_id", uid);
      } catch (e) {
        console.log("[marketing-push] user_push_devices sync exception:", e);
      }

      setProfile((p) => (p ? { ...p, marketing_push_enabled: next } : p));
    } catch (e) {
      setMarketingPushEnabled(prev);
      setMarketingPushMsg(formatProfileSaveError(e));
    } finally {
      setMarketingPushBusy(false);
    }
  }

  async function onToggleBiometrics(next: boolean) {
    setLockMsg(null);
    if (!next) {
      await setBiometricsEnabled(false);
      return;
    }
    if (!biometricsAvailable) {
      setLockMsg("Biometrics aren’t available on this device.");
      return;
    }
    const r = await LocalAuthentication.authenticateAsync({
      promptMessage: "Turn on Face ID for CT Pickup",
      cancelLabel: "Cancel",
    });
    if (r.success) await setBiometricsEnabled(true);
  }

  if (!isReady || !profileAdminReady) {
    return (
      <View style={styles.center}>
        <ActivityIndicator size="large" color="#fff" />
      </View>
    );
  }

  const signedEmail = session?.user?.email;
  if (!signedEmail) {
    return (
      <View style={styles.center}>
        <ActivityIndicator size="large" color="#fff" />
      </View>
    );
  }

  const myUserId = session?.user?.id ?? null;
  const fullName =
    [profile?.first_name, profile?.last_name].filter(Boolean).join(" ").trim() ||
    (profile?.username ? `@${profile.username}` : "Player");
  const uname = (profile?.username ?? "").trim();
  const currentTier = tierInfo?.tier ?? "bronze";
  const tColor = tierColor(currentTier);
  const tMeta = TIER_META[currentTier] ?? TIER_META.bronze;
  const ptsPerSession = tMeta.pts;
  const ptsPerSessionLabel = `${ptsPerSession > 0 ? "+" : ""}${ptsPerSession} pts / session`;
  const gamesPlayed = (winsCount ?? 0) + (lossesCount ?? 0);
  const winPct = gamesPlayed > 0 ? Math.round(((winsCount ?? 0) / gamesPlayed) * 100) : null;
  const sessionsCount = tierInfo?.sessions ?? 0;

  const primaryPos = (profile?.primary_position ?? "").trim() || null;
  const secondaryPos = Array.isArray(profile?.secondary_positions)
    ? (profile!.secondary_positions as string[]).filter(Boolean)
    : [];
  const expLabel = profile?.experience_level
    ? EXPERIENCE_LABELS[profile.experience_level] ?? profile.experience_level
    : null;
  const dob = profile?.date_of_birth ?? null;
  const dobFormatted = formatDob(dob);
  const age = ageFromDob(dob);
  const club = (profile?.club_name ?? "").trim() || null;
  const hasBackground = !!(primaryPos || secondaryPos.length || expLabel || age || dob || club);
  const isSelfDeclared = profile?.verification_level === "self";

  // Fixed 3×2 grid so the second row is always Age · Date of Birth · Club/Team.
  const soccerTiles: Array<{ icon: React.ComponentProps<typeof FontAwesome>["name"]; label: string; value: string }> = [
    { icon: "shield", label: "Primary Position", value: primaryPos ? positionFull(primaryPos) : "—" },
    { icon: "th", label: "Other Positions", value: secondaryPos.length ? secondaryPos.join(" · ") : "—" },
    { icon: "user", label: "Experience Level", value: expLabel ?? "—" },
    { icon: "calendar", label: "Age", value: age != null ? String(age) : "—" },
    { icon: "calendar-o", label: "Date of Birth", value: dobFormatted ?? "—" },
    { icon: "shield", label: "Club / Team", value: club ?? "—" },
  ];

  const accountRows: Array<{
    icon: React.ComponentProps<typeof FontAwesome>["name"];
    label: string;
    value: string;
  }> = [
    { icon: "envelope", label: "Email", value: signedEmail },
    { icon: "phone", label: "Phone", value: (profile?.phone ?? "").trim() || "Not set" },
    { icon: "user", label: "Username", value: uname ? `@${uname}` : "Not set" },
    { icon: "map-marker", label: "Region", value: profileRegionCode ?? ((profile?.nearest_venue ?? "").trim() || "Not set") },
    { icon: "map-o", label: "ZIP Code", value: (profile?.zip_code ?? "").trim() || "Not set" },
  ];

  return (
    <View style={styles.screen}>
      <Modal
        visible={reviewCodeModalOpen}
        transparent
        animationType="fade"
        onRequestClose={() => setReviewCodeModalOpen(false)}
      >
        <View style={styles.reviewModalBackdrop}>
          <View style={styles.reviewModalCard}>
            <Text style={styles.reviewModalTitle}>Review Mode</Text>
            <Text style={styles.reviewModalSub}>Enter the review secret code.</Text>
            <TextInput
              value={reviewCodeInput}
              onChangeText={setReviewCodeInput}
              autoCapitalize="characters"
              autoCorrect={false}
              secureTextEntry
              placeholder="Secret code"
              placeholderTextColor="rgba(255,255,255,0.35)"
              style={styles.reviewModalInput}
            />
            <View style={styles.reviewModalActions}>
              <Pressable style={styles.reviewModalBtnGhost} onPress={() => setReviewCodeModalOpen(false)}>
                <Text style={styles.reviewModalBtnGhostText}>Cancel</Text>
              </Pressable>
              <Pressable style={styles.reviewModalBtnPrimary} onPress={() => submitReviewCode()}>
                <Text style={styles.reviewModalBtnPrimaryText}>Activate</Text>
              </Pressable>
            </View>
          </View>
        </View>
      </Modal>
      <Modal
        visible={deleteConfirmModalOpen}
        transparent
        animationType="fade"
        onRequestClose={closeDeleteConfirmModal}
      >
        <View style={styles.reviewModalBackdrop}>
          <View style={styles.reviewModalCard}>
            <Text style={styles.reviewModalTitle}>Confirm account deletion</Text>
            <Text style={styles.reviewModalSub}>
              Type <Text style={{ fontWeight: "800", color: "#fff" }}>{DELETE_CONFIRM_WORD}</Text> below to permanently
              delete your account.
            </Text>
            <TextInput
              value={deleteConfirmInput}
              onChangeText={setDeleteConfirmInput}
              autoCapitalize="none"
              autoCorrect={false}
              autoComplete="off"
              placeholder={DELETE_CONFIRM_WORD}
              placeholderTextColor="rgba(255,255,255,0.35)"
              style={styles.reviewModalInput}
              editable={!deleteAccountBusy}
            />
            <View style={styles.reviewModalActions}>
              <Pressable
                style={styles.reviewModalBtnGhost}
                onPress={closeDeleteConfirmModal}
                disabled={deleteAccountBusy}
              >
                <Text style={styles.reviewModalBtnGhostText}>Cancel</Text>
              </Pressable>
              <Pressable
                style={[
                  styles.deleteConfirmModalBtn,
                  (!deleteConfirmMatches || deleteAccountBusy) && styles.deleteConfirmModalBtnDisabled,
                ]}
                onPress={() => void performDeleteAccount()}
                disabled={!deleteConfirmMatches || deleteAccountBusy}
              >
                {deleteAccountBusy ? (
                  <ActivityIndicator color="#fff" size="small" />
                ) : (
                  <Text style={styles.deleteConfirmModalBtnText}>Delete account</Text>
                )}
              </Pressable>
            </View>
          </View>
        </View>
      </Modal>
      <Modal
        visible={editModalOpen}
        animationType="slide"
        presentationStyle="pageSheet"
        onRequestClose={() => setEditModalOpen(false)}
      >
        <View style={[styles.screen, { paddingTop: Platform.OS === "android" ? insets.top : 0 }]}>
          <View style={s.editModalHeader}>
            <Text style={s.editModalTitle}>Edit profile</Text>
            <Pressable onPress={() => setEditModalOpen(false)} hitSlop={12} style={s.editModalClose}>
              <FontAwesome name="close" size={20} color="rgba(255,255,255,0.75)" />
            </Pressable>
          </View>
          <KeyboardAvoidingView style={{ flex: 1 }} behavior={Platform.OS === "ios" ? "padding" : "height"}>
            <ScrollView contentContainerStyle={{ padding: 20, paddingBottom: 80 }} keyboardShouldPersistTaps="handled">
              <ProfileSection
                editFirstName={editFirstName}
                setEditFirstName={setEditFirstName}
                editLastName={editLastName}
                setEditLastName={setEditLastName}
                editPlayingPosition={editPlayingPosition}
                setEditPlayingPosition={setEditPlayingPosition}
                editPrimaryPosition={editPrimaryPosition}
                setEditPrimaryPosition={setEditPrimaryPosition}
                editSecondaryPositions={editSecondaryPositions}
                setEditSecondaryPositions={setEditSecondaryPositions}
                editExperienceLevel={editExperienceLevel}
                setEditExperienceLevel={setEditExperienceLevel}
                editDateOfBirth={editDateOfBirth}
                setEditDateOfBirth={setEditDateOfBirth}
                editClubName={editClubName}
                setEditClubName={setEditClubName}
                editRosterUrl={editRosterUrl}
                setEditRosterUrl={setEditRosterUrl}
                editInstagram={editInstagram}
                setEditInstagram={setEditInstagram}
                editPhone={editPhone}
                setEditPhone={setEditPhone}
                editZipCode={editZipCode}
                setEditZipCode={setEditZipCode}
                editUsername={editUsername}
                setEditUsername={setEditUsername}
                editBusy={editBusy}
                profileNearestVenue={profile?.nearest_venue ?? null}
                profileRegionCode={profileRegionCode}
                profileZipCode={profile?.zip_code ?? null}
                hubRegionResolving={hubRegionResolving}
                hubVenueResolveDone={hubVenueResolveDone}
                usernameAutoFromName={usernameAutoFromName}
                positionPickerOpen={positionPickerOpen}
                setPositionPickerOpen={setPositionPickerOpen}
                primaryPositionPickerOpen={primaryPositionPickerOpen}
                setPrimaryPositionPickerOpen={setPrimaryPositionPickerOpen}
                experienceLevelPickerOpen={experienceLevelPickerOpen}
                setExperienceLevelPickerOpen={setExperienceLevelPickerOpen}
                profileSaveError={profileSaveError}
                editMsg={editMsg}
                editOk={editOk}
                onSave={() => void onSaveProfile()}
              />
            </ScrollView>
          </KeyboardAvoidingView>
        </View>
      </Modal>
      <KeyboardAvoidingView style={styles.scroll} behavior={Platform.OS === "ios" ? "padding" : "height"}>
        <ScrollView ref={scrollRef}
          contentContainerStyle={[styles.content, { paddingTop: insets.top + 4, paddingBottom: 200 }]}
          keyboardShouldPersistTaps="handled"
          refreshControl={
            <RefreshControl
              refreshing={refreshing}
              onRefresh={() => void onRefresh()}
              tintColor={LIME}
            />
          }
        >
          {/* 1. HEADER */}
          <View style={s.header}>
            <View style={s.headerSide} />
            <Text style={s.headerTitle}>Profile</Text>
            <View style={[s.headerSide, { alignItems: "flex-end" }]}>
              <Pressable
                onPress={() => {
                  void hapticTap();
                  scrollRef.current?.scrollTo({ y: settingsSectionY.current, animated: true });
                }}
                hitSlop={12}
                style={({ pressed }) => [s.gearBtn, pressed && { opacity: 0.7 }]}
                accessibilityLabel="Settings"
              >
                <Ionicons name="settings-outline" size={22} color="#fff" />
              </Pressable>
            </View>
          </View>

          {isSelfDeclared && (
            <Pressable
              onPress={() => {
                scrollRef.current?.scrollTo({ y: verificationSectionY.current, animated: true });
              }}
              style={s.actionBanner}
            >
              <View style={{ width: 10, height: 10, borderRadius: 5, backgroundColor: "#ef4444" }} />
              <View style={{ flex: 1 }}>
                <Text style={{ color: "#ef4444", fontWeight: "800", fontSize: 14 }}>Action required</Text>
                <Text style={{ color: "rgba(255,255,255,0.5)", fontSize: 12, marginTop: 2 }}>
                  Your profile is not verified. Scroll down to submit.
                </Text>
              </View>
              <Text style={{ color: "#ef4444", fontSize: 16 }}>↓</Text>
            </Pressable>
          )}

          {/* 2. PROFILE HERO CARD */}
          <View style={s.heroCard}>
            <View style={s.heroTop}>
              <Pressable onPress={openEdit} style={s.avatarWrap} accessibilityLabel="Change profile photo">
                <View style={[s.avatarRing, { borderColor: tColor }]}>
                  {avatarUrl ? (
                    <Image source={{ uri: avatarUrl }} style={s.avatarImg} />
                  ) : (
                    <View style={[s.avatarImg, s.avatarFallback]}>
                      <Text style={[s.avatarFallbackText, { color: tColor }]}>{initialsFromName(fullName)}</Text>
                    </View>
                  )}
                </View>
                <View style={s.cameraBadge}>
                  <FontAwesome name="camera" size={11} color="#0a0a0a" />
                </View>
              </Pressable>

              <View style={s.heroInfo}>
                <Text style={s.heroName} numberOfLines={2}>{fullName}</Text>
                {uname ? <Text style={s.heroUsername} numberOfLines={1}>@{uname}</Text> : null}
                <View style={s.heroBadgeRow}>
                  <View style={[s.tierBadge, { backgroundColor: `${tColor}33`, borderColor: `${tColor}88` }]}>
                    <Text style={[s.tierBadgeDiamond, { color: tColor }]}>◆</Text>
                    <Text style={[s.tierBadgeText, { color: tColor }]}>{tierLabel(currentTier)}</Text>
                  </View>
                  <Text
                    style={[s.ptsPerSession, { color: ptsPerSession >= 0 ? LIME : "#fca5a5" }]}
                    numberOfLines={1}
                  >
                    {ptsPerSessionLabel}
                  </Text>
                </View>
              </View>
            </View>

            {/* Stats row */}
            <View style={s.statsRow}>
              <View style={s.statCell}>
                <FontAwesome name="futbol-o" size={20} color={LIME} />
                <Text style={s.statValue}>{sessionsCount}</Text>
                <Text style={s.statLabel}>Sessions</Text>
              </View>
              <View style={s.statCell}>
                <FontAwesome name="percent" size={18} color={LIME} />
                <Text style={s.statValue}>{winPct == null ? "—" : `${winPct}%`}</Text>
                <Text style={s.statLabel}>Win %</Text>
              </View>
              <View style={s.statCell}>
                <FontAwesome name="trophy" size={20} color={LIME} />
                <Text style={s.statValue}>{winsCount ?? 0}</Text>
                <Text style={s.statLabel}>Wins</Text>
              </View>
              <View style={s.statCell}>
                <FontAwesome name="fire" size={20} color={LIME} />
                <Text style={s.statValue}>{potdCount ?? 0}</Text>
                <Text style={s.statLabel}>MOTM</Text>
              </View>
              <View style={s.statCell}>
                <FontAwesome name="star" size={19} color={LIME} />
                <Text style={s.statValue} numberOfLines={1} adjustsFontSizeToFit>
                  {points == null ? "—" : points.toLocaleString()}
                </Text>
                <Text style={s.statLabel}>Points</Text>
              </View>
            </View>

            {/* Tier progress card */}
            <View style={s.tierProgress}>
              <TierGem tier={currentTier} size={54} gid="accountTierGem" />
              <View style={{ flex: 1, minWidth: 0 }}>
                <Text style={s.tierProgressTitle} numberOfLines={1} adjustsFontSizeToFit>
                  {tierLabel(currentTier)} Tier
                </Text>
                <Text style={s.tierProgressSub}>{tMeta.topPct}</Text>
              </View>
              <Pressable
                onPress={() => myUserId && (router.push as (h: string) => void)(`/player/${myUserId}`)}
                style={({ pressed }) => [s.viewProgressBtn, pressed && { opacity: 0.85 }]}
              >
                <Text style={s.viewProgressBtnText}>View progress →</Text>
              </Pressable>
            </View>
          </View>

          {/* 3. SOCCER BACKGROUND */}
          <View
            style={s.blockCard}
            onLayout={(e) => {
              verificationSectionY.current = e.nativeEvent.layout.y;
            }}
          >
            <View style={s.blockHeader}>
              <Text style={s.blockTitle}>Soccer Background</Text>
              <Pressable onPress={openEdit} hitSlop={8}>
                <Text style={s.editLink}>Edit →</Text>
              </Pressable>
            </View>
            {hasBackground ? (
              <View style={s.tileGrid}>
                {soccerTiles.map((t, i) => (
                  <View key={`${t.label}-${i}`} style={s.tile}>
                    <FontAwesome name={t.icon} size={16} color={LIME} />
                    <Text style={s.tileLabel} numberOfLines={2}>{t.label}</Text>
                    <Text style={s.tileValue} numberOfLines={2}>{t.value}</Text>
                  </View>
                ))}
              </View>
            ) : (
              <View style={s.emptyBackground}>
                <Text style={s.emptyBackgroundText}>
                  Complete your profile to show your position, experience, and club.
                </Text>
                <Pressable onPress={openEdit} style={styles.outlineBtnLime}>
                  <Text style={styles.outlineBtnLimeText}>Complete your profile</Text>
                </Pressable>
              </View>
            )}
            {isSelfDeclared ? (
              <Pressable
                onPress={() => setVerificationModalOpen(true)}
                style={s.verifyPrompt}
              >
                <View style={{ flexDirection: "row", alignItems: "center", gap: 8 }}>
                  <View style={{ width: 9, height: 9, borderRadius: 5, backgroundColor: "#ef4444" }} />
                  <Text style={s.verifyPromptTitle}>NOT VERIFIED</Text>
                </View>
                <Text style={s.verifyPromptSub}>
                  Self-declared players are capped at Gold tier. Submit for verification to unlock Platinum and Diamond. →
                </Text>
              </Pressable>
            ) : null}
          </View>

          {/* 4. ACCOUNT */}
          <View style={s.blockCard}>
            <Text style={[s.blockTitle, { marginBottom: 4 }]}>Account</Text>
            {accountRows.map((row, i) => (
              <Pressable
                key={row.label}
                onPress={openEdit}
                style={[s.listRow, i === accountRows.length - 1 && s.listRowLast]}
              >
                <FontAwesome name={row.icon} size={17} color={LIME} style={s.listRowIcon} />
                <Text style={s.listRowLabel}>{row.label}</Text>
                <Text style={s.listRowValue} numberOfLines={1}>{row.value}</Text>
                <FontAwesome name="chevron-right" size={13} color="rgba(255,255,255,0.3)" />
              </Pressable>
            ))}
          </View>

        {/* 5. PREFERENCES */}
        <View
          style={{ marginTop: 8 }}
          onLayout={(e) => {
            settingsSectionY.current = e.nativeEvent.layout.y;
          }}
        />
        <PreferencesSection
          pushEnabled={pushEnabled}
          pushBusy={pushBusy}
          pushMsg={pushMsg}
          onTogglePush={(v) => void onTogglePushNotifications(v)}
          pushDisabled={!accessToken}
          marketingPushEnabled={marketingPushEnabled}
          marketingPushBusy={marketingPushBusy}
          marketingPushMsg={marketingPushMsg}
          onToggleMarketingPush={(v) => void onToggleMarketingPush(v)}
          marketingPushDisabled={!accessToken}
          maxDriveMinutes={maxDriveMinutes}
          maxDriveBusy={maxDriveBusy}
          maxDriveMsg={maxDriveMsg}
          maxDriveLabel={maxDriveLabel}
          minDrive={MIN_MAX_DRIVE_MINUTES}
          maxDrive={MAX_MAX_DRIVE_MINUTES}
          driveStep={MAX_DRIVE_STEP}
          onMaxDriveChange={setMaxDriveMinutes}
          onMaxDriveCommit={(v) => void onSaveMaxDriveMinutes(v)}
          maxDriveDisabled={!accessToken}
        />

        <ReferralSection accessToken={accessToken} />

        {/* 7. ACCOUNT & APP */}
        <View style={s.blockCard}>
          <Text style={[s.blockTitle, { marginBottom: 4 }]}>Account &amp; App</Text>

          <Pressable style={s.listRow} onPress={() => (router.push as (href: string) => void)("/waiver")}>
            <FontAwesome name="file-text-o" size={17} color={LIME} style={s.listRowIcon} />
            <Text style={s.listRowLabel}>Waiver</Text>
            {waiverLoading ? (
              <Text style={s.listRowValue}>…</Text>
            ) : waiverAccepted ? (
              <Text style={[s.listRowValue, { color: LIME }]}>Accepted</Text>
            ) : (
              <Text style={[s.listRowValue, { color: "#fcd34d" }]}>Required</Text>
            )}
            <FontAwesome name="chevron-right" size={13} color="rgba(255,255,255,0.3)" />
          </Pressable>

          <Pressable style={s.listRow} onPress={openEdit}>
            <FontAwesome name="futbol-o" size={17} color={LIME} style={s.listRowIcon} />
            <Text style={s.listRowLabel}>Soccer Background</Text>
            <Text style={s.listRowValue} />
            <FontAwesome name="chevron-right" size={13} color="rgba(255,255,255,0.3)" />
          </Pressable>

          <View style={s.listRow}>
            <FontAwesome name="line-chart" size={17} color={LIME} style={s.listRowIcon} />
            <Text style={s.listRowLabel}>Reliability</Text>
            <Text style={s.listRowValue}>Coming soon</Text>
            <View style={{ width: 13 }} />
          </View>

          <View style={s.listRow}>
            <FontAwesome name="ticket" size={17} color={LIME} style={s.listRowIcon} />
            <Text style={s.listRowLabel}>Your credits</Text>
            <Text style={[s.listRowValue, { color: (creditsCount ?? 0) > 0 ? LIME : "rgba(255,255,255,0.5)" }]}>
              {creditsCount ?? 0}
            </Text>
            <View style={{ width: 13 }} />
          </View>

          <Pressable
            style={[s.listRow, !isAdmin && s.listRowLast]}
            onPress={() => (router.push as (href: string) => void)("/run-history")}
          >
            <FontAwesome name="history" size={17} color={LIME} style={s.listRowIcon} />
            <Text style={s.listRowLabel}>Run history</Text>
            <Text style={s.listRowValue} />
            <FontAwesome name="chevron-right" size={13} color="rgba(255,255,255,0.3)" />
          </Pressable>

          {isAdmin ? (
            <View style={[s.listRow, s.listRowLast]}>
              <FontAwesome name="shield" size={17} color={LIME} style={s.listRowIcon} />
              <Text style={s.listRowLabel}>Admin mode</Text>
              <Switch
                value={adminModeEnabled}
                onValueChange={(v) => void setAdminModeEnabled(v)}
                disabled={!adminModeReady}
                trackColor={{ false: "rgba(255,255,255,0.18)", true: LIME }}
                thumbColor="#f4f4f5"
              />
            </View>
          ) : null}
        </View>

        {/* 8. SUPPORT & LEGAL */}
        <View style={s.blockCard}>
          <Text style={[s.blockTitle, { marginBottom: 4 }]}>Support &amp; Legal</Text>

          <Pressable style={s.listRow} onPress={() => (router.push as (href: string) => void)("/help")}>
            <FontAwesome name="question-circle" size={17} color={LIME} style={s.listRowIcon} />
            <Text style={s.listRowLabel}>Help</Text>
            <FontAwesome name="chevron-right" size={13} color="rgba(255,255,255,0.3)" />
          </Pressable>

          <Pressable style={s.listRow} onPress={() => void Linking.openURL(SUPPORT_MAILTO)}>
            <FontAwesome name="envelope" size={17} color={LIME} style={s.listRowIcon} />
            <Text style={s.listRowLabel}>Contact support</Text>
            <FontAwesome name="chevron-right" size={13} color="rgba(255,255,255,0.3)" />
          </Pressable>

          <Pressable style={s.listRow} onPress={() => (router.push as (href: string) => void)("/rules")}>
            <FontAwesome name="list-alt" size={17} color={LIME} style={s.listRowIcon} />
            <Text style={s.listRowLabel}>Rules</Text>
            <FontAwesome name="chevron-right" size={13} color="rgba(255,255,255,0.3)" />
          </Pressable>

          <Pressable style={s.listRow} onPress={() => (router.push as (href: string) => void)("/terms")}>
            <FontAwesome name="file-o" size={17} color={LIME} style={s.listRowIcon} />
            <Text style={s.listRowLabel}>Terms of Service</Text>
            <FontAwesome name="chevron-right" size={13} color="rgba(255,255,255,0.3)" />
          </Pressable>

          <Pressable style={s.listRow} onPress={() => (router.push as (href: string) => void)("/privacy-policy")}>
            <FontAwesome name="shield" size={17} color={LIME} style={s.listRowIcon} />
            <Text style={s.listRowLabel}>Privacy Policy</Text>
            <FontAwesome name="chevron-right" size={13} color="rgba(255,255,255,0.3)" />
          </Pressable>

          <Pressable
            style={[s.listRow, s.listRowLast]}
            onPress={() => {
              const next = aboutTapCount + 1;
              setAboutTapCount(next);
              if (next < REVIEW_MODE_TAP_TARGET) return;
              setAboutTapCount(0);
              openReviewCodeEntry();
            }}
          >
            <FontAwesome name="info-circle" size={17} color={LIME} style={s.listRowIcon} />
            <Text style={s.listRowLabel}>About this app</Text>
            <Text style={s.listRowValue}>v{appVersion}</Text>
            <FontAwesome name="chevron-right" size={13} color="rgba(255,255,255,0.3)" />
          </Pressable>
        </View>

        <Text style={styles.sectionTitle}>Security</Text>
        <AppLockSection
          hasPin={hasPin}
          lockEnabled={lockEnabled}
          onEnableAppLock={requestEnrollment}
          lockUi={lockUi}
          setLockUi={setLockUi}
          changeOld={changeOld}
          setChangeOld={setChangeOld}
          changeNewA={changeNewA}
          setChangeNewA={setChangeNewA}
          changeNewB={changeNewB}
          setChangeNewB={setChangeNewB}
          removeCurrent={removeCurrent}
          setRemoveCurrent={setRemoveCurrent}
          lockBusy={lockBusy}
          setLockBusy={setLockBusy}
          lockMsg={lockMsg}
          setLockMsg={setLockMsg}
          biometricsEnabled={biometricsEnabled}
          biometricsAvailable={biometricsAvailable}
          onToggleBiometrics={(v) => void onToggleBiometrics(v)}
          changePin={changePin}
          removePin={removePin}
          lockNow={lockNow}
        />

      {__DEV__ ? (
        <>
          <Pressable
            style={styles.devReplayRow}
            onPress={() => {
              void replayAccountIntro();
            }}
          >
            <Text style={styles.devReplayText}>Replay Account intro (dev only)</Text>
          </Pressable>
          <Pressable
            style={[styles.devReplayRow, styles.devReplayRowGap]}
            onPress={() => void replayOpeningThemeCtx?.replayOpeningTheme()}
          >
            <Text style={styles.devReplayText}>Replay opening theme (dev only)</Text>
          </Pressable>
        </>
      ) : null}
        <Pressable style={styles.aboutRow} onPress={() => void signOut()}>
          <View style={styles.aboutLeft}>
            <View style={styles.aboutIconWrap}>
              <FontAwesome name="sign-out" size={18} color="rgba(255,255,255,0.75)" />
            </View>
            <Text style={styles.aboutText}>Sign out</Text>
          </View>
          <FontAwesome name="chevron-right" size={14} color="rgba(255,255,255,0.35)" />
        </Pressable>

        {reviewModeEnabled ? (
          <Pressable
            style={[styles.aboutRow, styles.reviewModeOffRow]}
            onPress={() => {
              Alert.alert("Turn off Review Mode?", "Client approval bypass will be disabled.", [
                { text: "Cancel", style: "cancel" },
                { text: "Turn off", onPress: () => void setReviewModeEnabled(false) },
              ]);
            }}
          >
            <Text style={styles.reviewModeOffText}>Turn off App Review Mode</Text>
          </Pressable>
        ) : null}

        <Text style={[styles.sectionTitle, styles.dangerSectionTitle]}>Danger zone</Text>
        <Text style={styles.sectionSub}>
          Permanently remove your account and associated data from CT Pickup.
        </Text>
        <Pressable
          style={[styles.deleteAccountBtn, { backgroundColor: "#ef4444" }, deleteAccountBusy && styles.disabled]}
          disabled={deleteAccountBusy || !accessToken}
          onPress={startDeleteAccountFlow}
        >
          {deleteAccountBusy ? (
            <View style={styles.deleteAccountBtnBusy}>
              <ActivityIndicator color="#fff" />
              <Text style={styles.deleteAccountBtnText}>Deleting…</Text>
            </View>
          ) : (
            <Text style={styles.deleteAccountBtnText}>Delete account</Text>
          )}
        </Pressable>
        </ScrollView>
      <VerificationRequestModal
        visible={verificationModalOpen}
        onClose={() => setVerificationModalOpen(false)}
        onSubmitted={() => void loadProfile()}
      />
      </KeyboardAvoidingView>
    </View>
  );
}

const CARD_BG = "rgba(255,255,255,0.04)";
const CARD_BORDER = "rgba(255,255,255,0.08)";

const s = StyleSheet.create({
  /* header */
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  headerSide: { width: 40, justifyContent: "center" },
  headerTitle: { flex: 1, textAlign: "center", color: "#fff", fontSize: 20, fontWeight: "800", letterSpacing: 0.2 },
  gearBtn: { padding: 4 },

  actionBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "rgba(239,68,68,0.08)",
    borderWidth: 1.5,
    borderColor: "#ef4444",
    borderRadius: 12,
    padding: 14,
    marginBottom: 4,
    marginTop: 4,
  },

  /* hero */
  heroCard: {
    marginTop: 12,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: CARD_BORDER,
    padding: 16,
  },
  heroTop: { flexDirection: "row", alignItems: "center", gap: 16 },
  avatarWrap: { width: 84, height: 84 },
  avatarRing: { width: 84, height: 84, borderRadius: 42, borderWidth: 2.5, padding: 3 },
  avatarImg: { width: "100%", height: "100%", borderRadius: 40 },
  avatarFallback: { backgroundColor: "rgba(255,255,255,0.06)", alignItems: "center", justifyContent: "center" },
  avatarFallbackText: { fontSize: 28, fontWeight: "800" },
  cameraBadge: {
    position: "absolute",
    bottom: 0,
    left: 0,
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: LIME,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#0a0a0a",
  },
  heroInfo: { flex: 1, minWidth: 0 },
  heroName: { color: "#fff", fontSize: 22, fontWeight: "900", letterSpacing: -0.4 },
  heroUsername: { color: LIME, fontSize: 14, fontWeight: "700", marginTop: 2 },
  heroBadgeRow: { flexDirection: "row", alignItems: "center", gap: 8, marginTop: 8, flexWrap: "wrap" },
  tierBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 999,
    borderWidth: 1,
  },
  tierBadgeDiamond: { fontSize: 11 },
  tierBadgeText: { fontSize: 12, fontWeight: "800", letterSpacing: 0.3 },
  ptsPerSession: { fontSize: 12, fontWeight: "700", flexShrink: 1 },

  /* stats */
  statsRow: {
    flexDirection: "row",
    marginTop: 18,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: CARD_BORDER,
  },
  statCell: { flex: 1, alignItems: "center", gap: 5 },
  statValue: { color: "#fff", fontSize: 18, fontWeight: "900", letterSpacing: -0.3 },
  statLabel: { color: "rgba(255,255,255,0.45)", fontSize: 11, fontWeight: "600" },

  /* tier progress */
  tierProgress: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginTop: 16,
    padding: 12,
    borderRadius: 14,
    backgroundColor: "rgba(0,0,0,0.25)",
    borderWidth: 1,
    borderColor: CARD_BORDER,
  },
  tierProgressTitle: { color: "#fff", fontSize: 14, fontWeight: "800" },
  tierProgressSub: { color: "rgba(255,255,255,0.5)", fontSize: 11, lineHeight: 15, marginTop: 2 },
  viewProgressBtn: {
    flexShrink: 0,
    borderWidth: 1,
    borderColor: LIME,
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  viewProgressBtnText: { color: LIME, fontWeight: "800", fontSize: 12 },

  /* generic block card */
  blockCard: {
    marginTop: 16,
    backgroundColor: CARD_BG,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: CARD_BORDER,
    padding: 16,
  },
  blockHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 12 },
  blockTitle: { color: "#fff", fontSize: 17, fontWeight: "800", letterSpacing: -0.2 },
  editLink: { color: LIME, fontSize: 14, fontWeight: "800" },

  /* soccer tile grid */
  tileGrid: { flexDirection: "row", flexWrap: "wrap", marginHorizontal: -6 },
  tile: {
    width: "33.333%",
    paddingHorizontal: 6,
    paddingVertical: 10,
    gap: 6,
  },
  tileLabel: { color: "rgba(255,255,255,0.45)", fontSize: 11, fontWeight: "600", marginTop: 4 },
  tileValue: { color: "#fff", fontSize: 13, fontWeight: "700" },
  emptyBackground: { gap: 12 },
  emptyBackgroundText: { color: "rgba(255,255,255,0.55)", fontSize: 14, lineHeight: 20 },
  verifyPrompt: {
    marginTop: 14,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: "#ef4444",
    backgroundColor: "rgba(239,68,68,0.06)",
    padding: 12,
    gap: 6,
  },
  verifyPromptTitle: { color: "#ef4444", fontWeight: "800", fontSize: 13, letterSpacing: 0.3 },
  verifyPromptSub: { color: "rgba(255,255,255,0.6)", fontSize: 12, lineHeight: 17 },

  /* list rows */
  listRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.06)",
  },
  listRowLast: { borderBottomWidth: 0 },
  listRowIcon: { width: 26 },
  listRowLabel: { flex: 1, color: "#fff", fontSize: 15, fontWeight: "600" },
  listRowValue: { color: "rgba(255,255,255,0.5)", fontSize: 14, marginRight: 10, maxWidth: "48%", textAlign: "right" },

  /* edit modal */
  editModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: CARD_BORDER,
  },
  editModalTitle: { color: "#fff", fontSize: 18, fontWeight: "800" },
  editModalClose: { padding: 4 },
});

