export type ProfileGender = "male" | "female" | "other";

export const PROFILE_GENDER_LABELS: Record<ProfileGender, string> = {
  male: "Male",
  female: "Female",
  other: "Other",
};

export const PROFILE_GENDER_OTHER_MAX_LEN = 64;
export const PROFILE_PLAYING_POSITION_MAX_LEN = 64;
export const PROFILE_USERNAME_MIN_LEN = 3;
/** Stored usernames: lowercase letters and digits only. */
export const PROFILE_USERNAME_MAX_LEN = 30;

export const USERNAME_TAKEN_USER_MESSAGE =
  "That username is already taken. Try adding numbers or a nickname.";

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/**
 * Base handle from first + last name: lowercase, strip spaces and non-alphanumeric,
 * max {@link PROFILE_USERNAME_MAX_LEN}. Pads with "player" if needed to reach min length.
 */
export function slugUsernameBaseFromNames(firstName: string, lastName: string): string {
  const cleanPart = (raw: string) =>
    raw
      .normalize("NFD")
      .replace(/\p{M}/gu, "")
      .toLowerCase()
      .replace(/[^a-z0-9]/g, "");
  const combined = `${cleanPart(firstName)}${cleanPart(lastName)}`.slice(0, PROFILE_USERNAME_MAX_LEN);
  let base = combined;
  if (base.length < PROFILE_USERNAME_MIN_LEN) {
    base = (base + "player").slice(0, PROFILE_USERNAME_MIN_LEN).slice(0, PROFILE_USERNAME_MAX_LEN);
  }
  return base.slice(0, PROFILE_USERNAME_MAX_LEN);
}

/** True if `username` equals the auto slug from names, or that slug with a numeric suffix (e.g. omeedpooya2). */
export function usernameMatchesAutoGeneratedFromNames(
  username: string | null | undefined,
  firstName: string,
  lastName: string,
): boolean {
  const u = String(username ?? "").trim().toLowerCase();
  if (u.length < PROFILE_USERNAME_MIN_LEN) return false;
  const base = slugUsernameBaseFromNames(firstName.trim(), lastName.trim());
  if (u === base) return true;
  return new RegExp("^" + escapeRegExp(base) + "(\\d+)$").test(u);
}

/** Lowercase handle: 3–30 chars, letters and digits only (stored form). */
export function normalizeProfileUsername(raw: string | null | undefined): string | null {
  const t = String(raw ?? "")
    .trim()
    .toLowerCase()
    .replace(/\s+/g, "")
    .slice(0, PROFILE_USERNAME_MAX_LEN);
  if (t.length < PROFILE_USERNAME_MIN_LEN) return null;
  if (!/^[a-z0-9]+$/.test(t)) return null;
  return t;
}

export function parseProfileGender(raw: string | null | undefined): ProfileGender | null {
  if (raw === "male" || raw === "female" || raw === "other") return raw;
  return null;
}

export function normalizeGenderOther(raw: string | null | undefined): string | null {
  const t = String(raw ?? "")
    .trim()
    .slice(0, PROFILE_GENDER_OTHER_MAX_LEN);
  return t.length > 0 ? t : null;
}

export function normalizePlayingPosition(raw: string | null | undefined): string | null {
  const t = String(raw ?? "")
    .trim()
    .slice(0, PROFILE_PLAYING_POSITION_MAX_LEN);
  return t.length > 0 ? t : null;
}

export function profileIdentityColumns(args: {
  firstName: string;
  lastName: string;
  sex: ProfileGender;
  gender: ProfileGender;
  genderOther: string;
  playingPosition: string;
}): {
  first_name: string;
  last_name: string;
  sex: ProfileGender;
  gender: ProfileGender;
  gender_other: string | null;
  playing_position: string;
} {
  return {
    first_name: args.firstName.trim(),
    last_name: args.lastName.trim(),
    sex: args.sex,
    gender: args.gender,
    gender_other: args.gender === "other" ? normalizeGenderOther(args.genderOther) : null,
    playing_position: normalizePlayingPosition(args.playingPosition) ?? "",
  };
}

