import { Platform, StyleSheet } from "react-native";


import { headline, themeColor } from "@/theme";
function make_accountStyles() {
  return StyleSheet.create({
  screen: { flex: 1, backgroundColor: themeColor().bg },
  scroll: { flex: 1, backgroundColor: themeColor().bg },
  content: { padding: 20, paddingBottom: 40 },
  center: { flex: 1, backgroundColor: themeColor().bg, justifyContent: "center", alignItems: "center" },
  title: { fontSize: 40, ...headline, color: themeColor().text,},
  sub: { marginTop: 8, color: themeColor().muted, fontSize: 14, fontFamily: "Inter_400Regular", lineHeight: 20 },
  sectionTitle: { marginTop: 28, fontSize: 20, ...headline, color: themeColor().text },
  /** Sub-heading inside a Settings section: sentence case, Inter 600. */
  settingsSubTitle: { marginTop: 12, fontSize: 14, fontFamily: "Inter_600SemiBold", fontWeight: "600", color: themeColor().text },
  sectionSub: { marginTop: 8, color: themeColor().muted, fontSize: 14, fontFamily: "Inter_400Regular", lineHeight: 20 },
  card: {
    marginTop: 12,
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: themeColor().line,
    backgroundColor: themeColor().card,
  },
  cardLime: {
    borderColor: themeColor().pitch,
    backgroundColor: themeColor().pitchPanel,
  },
  signedLabel: { fontSize: 13, fontFamily: "Inter_700Bold", fontWeight: "800", color: themeColor().pitchText },
  email: { marginTop: 8, fontSize: 20, ...headline, color: themeColor().text },
  signedAssist: { marginTop: 8, fontSize: 14, fontFamily: "Inter_400Regular", color: themeColor().muted, lineHeight: 20 },
  fieldLabel: { fontSize: 13, fontFamily: "Inter_700Bold", fontWeight: "700", color: themeColor().muted },
  fieldLabelStrong: { fontSize: 13, fontFamily: "Inter_700Bold", fontWeight: "800", color: themeColor().text },
  input: {
    marginTop: 8,
    borderWidth: 1,
    borderColor: themeColor().line,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 16, fontFamily: "Inter_400Regular",
    color: themeColor().text,
    backgroundColor: themeColor().overlaySubtle,
  },
  selectTrigger: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  selectPlaceholder: { fontSize: 16, fontFamily: "Inter_400Regular", color: themeColor().muted },
  selectValue: { fontSize: 16, fontFamily: "Inter_400Regular", color: themeColor().text },
  selectChevron: { fontSize: 14, fontFamily: "Inter_400Regular", color: themeColor().pitchText, marginLeft: 8 },
  primaryBtn: {
    marginTop: 16,
    backgroundColor: themeColor().pitch,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: "center",
  },
  primaryBtnText: { color: themeColor().onPitch, fontWeight: "700", fontSize: 16, fontFamily: "Inter_700Bold" },
  saveBtnBusy: { flexDirection: "row", alignItems: "center", gap: 8 },
  disabled: { opacity: 0.5 },
  outlineBtnLime: {
    marginTop: 16,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: themeColor().accent,
    backgroundColor: themeColor().pitchPanel,
    alignItems: "center",
  },
  outlineBtnLimeText: { color: themeColor().accent, fontWeight: "700", fontSize: 16, fontFamily: "Inter_700Bold" },
  bioHint: { marginTop: 4, fontSize: 13, fontFamily: "Inter_400Regular", color: themeColor().muted },
  zipLabelRow: {
    marginTop: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  zipLocationBtn: { fontSize: 13, fontFamily: "Inter_600SemiBold", fontWeight: "600", color: themeColor().pitchText },
  zipLocationBtnDisabled: { opacity: 0.5 },
  zipHelper: { marginTop: 4, fontSize: 13, fontFamily: "Inter_400Regular", lineHeight: 18, color: themeColor().muted },
  zipLocationError: { marginTop: 4, fontSize: 13, fontFamily: "Inter_400Regular", color: themeColor().coralText },
  zipNearestHint: { marginTop: 8, fontSize: 13, fontFamily: "Inter_400Regular", lineHeight: 18, color: themeColor().muted },
  usernameAtPreview: { marginTop: 4, fontSize: 16, fontFamily: "Inter_700Bold", fontWeight: "700", color: themeColor().pitchText },
  msg: { marginTop: 12, color: themeColor().coralText, fontSize: 14, fontFamily: "Inter_400Regular" },
  msgMuted: { color: themeColor().coralText },
  msgOk: { color: themeColor().pitchText },
  saveFailedText: { marginTop: 12, color: themeColor().coralText, fontSize: 14, fontFamily: "Inter_400Regular", lineHeight: 20 },
  rowBetween: { flexDirection: "row", alignItems: "center", marginBottom: 16 },
  marketingPushRow: { marginTop: 16 },
  maxDriveBlock: { marginTop: 20, paddingTop: 20, borderTopWidth: 1, borderTopColor: themeColor().line },
  maxDriveHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 },
  maxDriveValue: { fontSize: 14, fontFamily: "Inter_700Bold", fontWeight: "700", color: themeColor().pitchText },
  maxDriveSlider: { width: "100%", height: 40, marginTop: 8 },
  maxDriveTicks: { flexDirection: "row", justifyContent: "space-between", marginTop: 4 },
  maxDriveTick: { fontSize: 13, fontFamily: "Inter_400Regular", color: themeColor().muted },
  maxDriveSaving: { flexDirection: "row", alignItems: "center", gap: 8, marginTop: 8 },
  cardLoadingRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  cardLoadingText: { color: themeColor().muted, fontSize: 14, fontFamily: "Inter_400Regular" },
  cardMuted: { color: themeColor().muted, fontSize: 14, fontFamily: "Inter_400Regular", lineHeight: 20 },
  cardSubtle: { marginTop: 8, color: themeColor().muted, fontSize: 14, fontFamily: "Inter_400Regular", lineHeight: 20 },
  reliabilityHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8 },
  reliabilityLabel: { color: themeColor().text, fontSize: 16, fontFamily: "Inter_700Bold", fontWeight: "700", flexShrink: 1 },
  scorePill: {
    paddingVertical: 4,
    paddingHorizontal: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: themeColor().pitch,
    backgroundColor: themeColor().pitchPanel,
  },
  scorePillText: { color: themeColor().onPitchPanel, fontSize: 14, fontFamily: "Inter_700Bold", fontWeight: "800",},
  secondaryBtn: {
    marginTop: 12,
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: themeColor().line,
    alignItems: "center",
  },
  secondaryBtnText: { color: themeColor().text, fontWeight: "600", fontSize: 16, fontFamily: "Inter_600SemiBold" },
  textBtn: { marginTop: 12, alignItems: "center" },
  textBtnLabel: { color: themeColor().muted, fontSize: 14, fontFamily: "Inter_400Regular" },
  warn: { marginTop: 8, fontSize: 13, fontFamily: "Inter_400Regular", color: themeColor().muted },
  deleteAccountBtn: {
    marginTop: 12,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: themeColor().coral,
    backgroundColor: themeColor().overlaySubtle,
  },
  deleteAccountBtnBusy: { flexDirection: "row", alignItems: "center", gap: 8 },
  deleteAccountBtnText: { color: themeColor().coralText, fontWeight: "800", fontSize: 16, fontFamily: "Inter_700Bold" },
  dangerSectionTitle: { marginTop: 32, color: themeColor().coralText },
  statusRow: { flexDirection: "row", marginBottom: 12 },
  statusPill: { paddingVertical: 4, paddingHorizontal: 12, borderRadius: 999, borderWidth: 1 },
  statusPillGreen: { borderColor: themeColor().pitch, backgroundColor: themeColor().pitchPanel },
  statusPillAmber: { borderColor: themeColor().line, backgroundColor: themeColor().card },
  statusPillText: { fontSize: 13, fontFamily: "Inter_700Bold", fontWeight: "800",},
  statusPillTextGreen: { color: themeColor().pitchText },
  statusPillTextAmber: { color: themeColor().muted },
  referralCode: { marginTop: 8, fontSize: 24, ...headline, color: themeColor().pitchText },
  regionValue: { marginTop: 8, fontSize: 16, fontFamily: "Inter_700Bold", fontWeight: "700", color: themeColor().text },
  regionMuted: { marginTop: 8, fontSize: 16, fontFamily: "Inter_400Regular", color: themeColor().muted, lineHeight: 20 },
  regionResolvingRow: { marginTop: 8, flexDirection: "row", alignItems: "center", gap: 8 },
  regionResolvingText: { fontSize: 14, fontFamily: "Inter_400Regular", color: themeColor().muted },
  creditActive: { marginTop: 8, fontSize: 16, fontFamily: "Inter_700Bold", fontWeight: "700", color: themeColor().pitchText },
  creditUsed: {
    marginTop: 8,
    fontSize: 14, fontFamily: "Inter_400Regular",
    color: themeColor().muted,
    textDecorationLine: "line-through",
  },
  creditExpired: { marginTop: 8, fontSize: 14, fontFamily: "Inter_400Regular", color: themeColor().coralText },
  modalRoot: { flex: 1 },
  modalBackdrop: { ...StyleSheet.absoluteFill, backgroundColor: themeColor().scrim },
  modalCardWrap: { ...StyleSheet.absoluteFill, justifyContent: "center", paddingHorizontal: 28 },
  modalCard: {
    backgroundColor: themeColor().card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: themeColor().pitch,
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  modalTitle: { fontSize: 16, fontFamily: "Inter_700Bold", fontWeight: "800", color: themeColor().pitchText, paddingHorizontal: 16, paddingVertical: 12 },
  modalRow: { paddingVertical: 12, paddingHorizontal: 16, borderRadius: 10, marginHorizontal: 4 },
  modalRowSelected: { backgroundColor: themeColor().pitchPanel },
  modalRowText: { fontSize: 16, fontFamily: "Inter_400Regular", color: themeColor().text },
  modalRowTextSelected: { color: themeColor().pitchText, fontWeight: "700" },
  modalCancel: { marginTop: 4, paddingVertical: 12, alignItems: "center" },
  modalCancelText: { fontSize: 16, fontFamily: "Inter_600SemiBold", fontWeight: "600", color: themeColor().muted },
  aboutRow: {
    marginTop: 16,
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: themeColor().line,
    backgroundColor: themeColor().card,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  aboutLeft: { flexDirection: "row", alignItems: "center", gap: 8 },
  aboutIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: themeColor().overlaySubtle,
    borderWidth: 1,
    borderColor: themeColor().line,
  },
  aboutText: { fontSize: 16, fontFamily: "Inter_700Bold", fontWeight: "700", color: themeColor().text },
  aboutVersionSub: { fontSize: 13, fontFamily: "Inter_400Regular", color: themeColor().muted, marginTop: 4 },
  reviewModeOffRow: {
    marginTop: 8,
    justifyContent: "center",
    borderColor: themeColor().pitch,
    backgroundColor: themeColor().pitchPanel,
  },
  reviewModeOffText: { fontSize: 14, fontFamily: "Inter_700Bold", fontWeight: "700", color: themeColor().pitchText, textAlign: "center", flex: 1 },
  reviewModalBackdrop: {
    flex: 1,
    backgroundColor: themeColor().scrim,
    justifyContent: "center",
    padding: 24,
  },
  reviewModalCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: themeColor().line,
    backgroundColor: themeColor().card,
    padding: 20,
  },
  reviewModalTitle: { fontSize: 20, ...headline, color: themeColor().text },
  reviewModalSub: { fontSize: 14, fontFamily: "Inter_400Regular", color: themeColor().muted, marginTop: 4, marginBottom: 12 },
  reviewModalInput: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: themeColor().line,
    backgroundColor: themeColor().overlaySubtle,
    color: themeColor().text,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 16, fontFamily: "Inter_400Regular",
  },
  reviewModalActions: { flexDirection: "row", justifyContent: "flex-end", gap: 8, marginTop: 16 },
  reviewModalBtnGhost: { paddingVertical: 8, paddingHorizontal: 12 },
  reviewModalBtnGhostText: { color: themeColor().muted, fontWeight: "600" },
  reviewModalBtnPrimary: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 10,
    backgroundColor: themeColor().pitch,
  },
  reviewModalBtnPrimaryText: { color: themeColor().onPitch, fontWeight: "800" },
  deleteConfirmModalBtn: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: themeColor().coral,
    backgroundColor: themeColor().overlaySubtle,
    minWidth: 120,
    alignItems: "center",
    justifyContent: "center",
  },
  deleteConfirmModalBtnDisabled: { opacity: 0.4 },
  deleteConfirmModalBtnText: { color: themeColor().coralText, fontWeight: "800" },
  devReplayRow: {
    marginTop: 20,
    paddingVertical: 12,
    alignItems: "center",
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: themeColor().line,
    backgroundColor: themeColor().card,
  },
  devReplayText: { fontSize: 13, fontFamily: "Inter_600SemiBold", color: themeColor().text, fontWeight: "600" },
  devReplayRowGap: { marginTop: 12 },
  bgRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingVertical: 4 },
  bgLabel: { fontSize: 13, fontFamily: "Inter_600SemiBold", color: themeColor().muted, fontWeight: "600", },
  bgValue: { fontSize: 14, fontFamily: "Inter_600SemiBold", color: themeColor().text, fontWeight: "600", flexShrink: 1, textAlign: "right", maxWidth: "65%" },
  ghostBtn: { paddingVertical: 8, paddingHorizontal: 12, borderRadius: 10, borderWidth: 1, borderColor: themeColor().line, alignItems: "center" },
  ghostBtnText: { fontSize: 14, fontFamily: "Inter_600SemiBold", color: themeColor().muted, fontWeight: "600" },
});
}
export let accountStyles = make_accountStyles();
export function publish_accountStyles() {
  accountStyles = make_accountStyles();
}


export const POSITION_OPTIONS = [
  { value: "Goalkeeper" as const, label: "Goalkeeper" },
  { value: "Defender" as const, label: "Defender" },
  { value: "Midfielder" as const, label: "Midfielder" },
  { value: "Attacker" as const, label: "Attacker" },
] as const;

export type PositionValue = (typeof POSITION_OPTIONS)[number]["value"];

export const SPECIFIC_POSITION_OPTIONS = [
  { value: "GK" as const, label: "GK — Goalkeeper" },
  { value: "CB" as const, label: "CB — Center Back" },
  { value: "RB" as const, label: "RB — Right Back" },
  { value: "LB" as const, label: "LB — Left Back" },
  { value: "CDM" as const, label: "CDM — Defensive Mid" },
  { value: "CM" as const, label: "CM — Central Mid" },
  { value: "CAM" as const, label: "CAM — Attacking Mid" },
  { value: "LW" as const, label: "LW — Left Wing" },
  { value: "RW" as const, label: "RW — Right Wing" },
  { value: "ST" as const, label: "ST — Striker" },
] as const;

export type SpecificPositionValue = (typeof SPECIFIC_POSITION_OPTIONS)[number]["value"];

export const EXPERIENCE_LEVEL_OPTIONS = [
  { value: "recreational" as const, label: "Recreational" },
  { value: "club" as const, label: "Club" },
  { value: "hs_varsity" as const, label: "High School Varsity" },
  { value: "college" as const, label: "College" },
  { value: "semi_pro" as const, label: "Semi-Pro" },
  { value: "pro" as const, label: "Pro" },
] as const;

export type ExperienceLevelValue = (typeof EXPERIENCE_LEVEL_OPTIONS)[number]["value"];
